(()=>{
'use strict';
const $=id=>document.getElementById(id);
const KEY='tqb_quotes_v3',SET='tqb_settings_v2';
let quotes=[],settings={businessName:'Your Business Name',abn:'',businessPhone:'',businessEmail:'',businessAddress:'',defaultRate:90},currentQuote=null,editingId=null;
const money=n=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function getLS(k){try{const v=localStorage.getItem(k);return v?JSON.parse(v):null}catch(e){return null}}
function saveLS(){try{localStorage.setItem(KEY,JSON.stringify(quotes));localStorage.setItem(SET,JSON.stringify(settings));return true}catch(e){return false}}
function load(){quotes=getLS(KEY)||getLS('tqb_quotes_v2')||getLS('tqb_quotes_v1')||[];const s=getLS(SET);if(s)settings={...settings,...s};renderDashboard()}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.screen===id));if(id==='dashboard')renderDashboard();if(id==='saved')renderSaved();if(id==='settings')loadSettings();window.scrollTo(0,0)}
function calc(){const materials=[...document.querySelectorAll('.item-amount')].reduce((s,x)=>s+(Number(x.value)||0),0);const labour=(Number($('labourHours')?.value)||0)*(Number($('hourlyRate')?.value)||0);const subtotal=materials+labour;const gst=$('gstEnabled')?.checked?subtotal*.1:0;const total=subtotal+gst;if($('subtotal'))$('subtotal').textContent=money(subtotal);if($('gst'))$('gst').textContent=money(gst);if($('grandTotal'))$('grandTotal').textContent=money(total);return{materials,labour,subtotal,gst,total}}
function addItem(desc='',amount=''){const r=document.createElement('div');r.className='item';r.innerHTML=`<input class="item-desc" placeholder="Material or other cost" value="${esc(desc)}"><input class="item-amount" type="number" min="0" step="0.01" placeholder="$" value="${esc(amount)}"><button type="button" aria-label="Remove item">✕</button>`;r.querySelector('button').onclick=()=>{r.remove();calc()};r.querySelectorAll('input').forEach(x=>x.oninput=calc);$('lineItems').appendChild(r)}
function reset(){editingId=null;currentQuote=null;$('quoteFormEl').reset();$('lineItems').innerHTML='';addItem();$('hourlyRate').value=settings.defaultRate||90;calc();$('quoteFormTitle').textContent='New quote';$('saveQuoteBtn').textContent='Save & Preview Quote'}
function collect(){const c=calc();const items=[...document.querySelectorAll('.item')].map(r=>({description:r.querySelector('.item-desc').value.trim(),amount:Number(r.querySelector('.item-amount').value)||0})).filter(x=>x.description||x.amount);return{id:editingId||String(Date.now())+'-'+Math.random().toString(16).slice(2),number:currentQuote?.number||'Q-'+String(Date.now()).slice(-6),date:currentQuote?.date||new Date().toLocaleDateString('en-AU'),savedAt:Date.now(),customerName:$('customerName').value.trim(),customerPhone:$('customerPhone').value.trim(),customerEmail:$('customerEmail').value.trim(),jobDescription:$('jobDescription').value.trim(),items,labourHours:Number($('labourHours').value)||0,hourlyRate:Number($('hourlyRate').value)||0,...c}}
function card(q){return`<div class="quote-card" data-id="${esc(q.id)}"><div class="row"><b>${esc(q.customerName||'Unnamed customer')}</b><b>${money(q.total)}</b></div><small>${esc(q.number)} · ${esc(q.date)}</small><div class="desc">${esc(q.jobDescription||'')}</div></div>`}
function bindCards(){document.querySelectorAll('.quote-card').forEach(x=>x.onclick=()=>{currentQuote=quotes.find(q=>q.id===x.dataset.id);if(currentQuote){renderPreview(currentQuote);show('preview')}})}
function renderDashboard(){if(!$('quoteCount'))return;$('quoteCount').textContent=quotes.length;$('totalQuoted').textContent=money(quotes.reduce((s,q)=>s+(Number(q.total)||0),0));$('recentQuotes').innerHTML=quotes.length?quotes.slice(0,5).map(card).join(''):'<div class="empty">No quotes yet.<br><br>Tap <b>New Quote</b> to create your first one.</div>';bindCards()}
function renderSaved(){$('allQuotes').innerHTML=quotes.length?quotes.map(card).join(''):'<div class="empty">No saved quotes yet.</div>';bindCards()}
const logo='<svg class="logo" viewBox="0 0 100 100"><rect x="2" y="2" width="96" height="96" rx="20" fill="#171717" stroke="#ffb000" stroke-width="4"/><path d="M27 35l18-18 28 28-7 7-28-28-11 11z" fill="#d8d8d8"/><path d="M45 19l13-7 31 31-7 7z" fill="#ffb000"/><text x="50" y="70" text-anchor="middle" font-size="13" font-weight="900" fill="#fff">TRADIE</text><rect x="19" y="73" width="62" height="14" rx="5" fill="#ffb000"/><text x="50" y="84" text-anchor="middle" font-size="9" font-weight="900" fill="#111">QUOTE BUDDY</text></svg>';
function renderPreview(q){$('quotePreview').innerHTML=`<div class="paper-head"><div>${logo}<h1>${esc(settings.businessName||'Your Business Name')}</h1><div>${esc(settings.businessAddress||'')}</div><div>${esc(settings.businessPhone||'')} ${settings.businessEmail?'· '+esc(settings.businessEmail):''}</div><div>${settings.abn?'ABN '+esc(settings.abn):''}</div></div><div class="paper-meta"><h2>QUOTE</h2><b>${esc(q.number)}</b><div>${esc(q.date)}</div></div></div><div><b>Quote for</b><div>${esc(q.customerName)}</div><div>${esc(q.customerPhone)}</div><div>${esc(q.customerEmail)}</div></div><p class="job"><b>Job description</b><br>${esc(q.jobDescription).replace(/\n/g,'<br>')}</p><table><thead><tr><th>Description</th><th>Amount</th></tr></thead><tbody>${q.items.map(i=>`<tr><td>${esc(i.description)}</td><td>${money(i.amount)}</td></tr>`).join('')}${q.labourHours?`<tr><td>Labour (${q.labourHours} hrs × ${money(q.hourlyRate)}/hr)</td><td>${money(q.labour)}</td></tr>`:''}</tbody></table><div class="paper-total"><div><span>Subtotal</span><span>${money(q.subtotal)}</span></div><div><span>GST</span><span>${money(q.gst)}</span></div><div class="grand"><span>Total</span><span>${money(q.total)}</span></div></div><p class="thanks">Thank you for the opportunity to quote on your job.</p>`)}
function edit(q){editingId=q.id;$('quoteFormTitle').textContent='Edit quote';$('saveQuoteBtn').textContent='Update Quote';$('customerName').value=q.customerName||'';$('customerPhone').value=q.customerPhone||'';$('customerEmail').value=q.customerEmail||'';$('jobDescription').value=q.jobDescription||'';$('labourHours').value=q.labourHours||0;$('hourlyRate').value=q.hourlyRate||settings.defaultRate||90;$('gstEnabled').checked=Number(q.gst)>0;$('lineItems').innerHTML='';(q.items||[]).forEach(i=>addItem(i.description,i.amount));if(!q.items?.length)addItem();calc();show('quoteForm')}
async function makePDF(){if(!currentQuote)return;try{if(typeof html2pdf==='function'){const blob=await html2pdf().set({margin:.2,image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true,backgroundColor:'#fff'},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'}}).from($('quotePreview')).outputPdf('blob');const file=new File([blob],currentQuote.number+'.pdf',{type:'application/pdf'});if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({title:'Quote '+currentQuote.number,files:[file]});return}const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=currentQuote.number+'.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}else window.print()}catch(e){if(e.name!=='AbortError')window.print()}}
function loadSettings(){['businessName','abn','businessPhone','businessEmail','businessAddress','defaultRate'].forEach(k=>$(k).value=settings[k]??'')}
function backup(){const blob=new Blob([JSON.stringify({version:3,quotes,settings},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='tradie-quote-buddy-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function wire(){
$('newQuoteBtn').onclick=()=>{reset();show('quoteForm')};
$('addItemBtn').onclick=()=>addItem();
$('settingsBtn').onclick=()=>show('settings');
$('viewAllBtn').onclick=()=>show('saved');
$('printBtn').onclick=makePDF;
$('editQuoteBtn').onclick=()=>currentQuote&&edit(currentQuote);
$('deleteQuoteBtn').onclick=()=>currentQuote&&$('confirmModal').classList.add('show');
$('cancelDelete').onclick=()=>$('confirmModal').classList.remove('show');
$('confirmDelete').onclick=()=>{quotes=quotes.filter(q=>q.id!==currentQuote?.id);saveLS();currentQuote=null;show('saved')};
$('quoteFormEl').onsubmit=e=>{e.preventDefault();const q=collect();const i=quotes.findIndex(x=>x.id===editingId);if(i>=0)quotes[i]=q;else quotes.unshift(q);currentQuote=q;if(!saveLS())alert('Could not save on this device.');renderPreview(q);show('preview')};
$('settingsForm').onsubmit=e=>{e.preventDefault();settings={businessName:$('businessName').value.trim(),abn:$('abn').value.trim(),businessPhone:$('businessPhone').value.trim(),businessEmail:$('businessEmail').value.trim(),businessAddress:$('businessAddress').value.trim(),defaultRate:Number($('defaultRate').value)||0};saveLS();alert('Business settings saved');show('dashboard')};
$('backupBtn').onclick=backup;
$('restoreBtn').onclick=()=>$('restoreFile').click();
$('restoreFile').onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(r.result);if(!Array.isArray(d.quotes))throw Error();quotes=d.quotes;settings={...settings,...(d.settings||{})};saveLS();alert('Restored '+quotes.length+' quote'+(quotes.length===1?'':'s')+'.');show('dashboard')}catch(x){alert('That backup file could not be restored.')}};r.readAsText(f);e.target.value=''};
$('subscribeBtn')?.addEventListener('click',()=>location.href='subscription.html');
document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>show('dashboard'));
document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>{if(n.dataset.screen==='quoteForm')reset();show(n.dataset.screen)});
$('labourHours').oninput=calc;$('hourlyRate').oninput=calc;$('gstEnabled').onchange=calc;
reset();show('dashboard');load();
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wire,{once:true});else wire();
})();
