const KEY='tqb_quotes_v2',OLD='tqb_quotes_v1',SET='tqb_settings_v1',DB='tradie_quote_buddy',VER=2,STORE='quotes';
let quotes=[],settings={businessName:'Your Business Name',abn:'',businessPhone:'',businessEmail:'',businessAddress:'',defaultRate:90},currentQuote=null,editingId=null;
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(Number(n)||0),esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function openDB(){return new Promise((res,rej)=>{if(!indexedDB)return rej(Error('IndexedDB unavailable'));let r=indexedDB.open(DB,VER);r.onupgradeneeded=()=>{let d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
async function getDB(){let d=await openDB();return new Promise((res,rej)=>{let r=d.transaction(STORE,'readonly').objectStore(STORE).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error)})}
async function putDB(a){let d=await openDB();return new Promise((res,rej)=>{let t=d.transaction(STORE,'readwrite'),s=t.objectStore(STORE);s.clear();a.forEach(q=>s.put(q));t.oncomplete=res;t.onerror=()=>rej(t.error)})}
function getLS(k){try{let v=localStorage.getItem(k);return v?JSON.parse(v):null}catch(e){return null}}
function merge(a,b){let m=new Map();[...(Array.isArray(a)?a:[]),...(Array.isArray(b)?b:[])].forEach(q=>q&&q.id&&m.set(q.id,q));return [...m.values()].sort((a,b)=>(b.savedAt||0)-(a.savedAt||0))}
async function load(){let a=getLS(KEY)||getLS(OLD)||[],b=[];try{b=await getDB()}catch(e){}quotes=merge(a,b);if(quotes.length){try{localStorage.setItem(KEY,JSON.stringify(quotes))}catch(e){}try{await putDB(quotes)}catch(e){}}let s=getLS(SET);if(s)settings={...settings,...s};renderDashboard()}
async function persist(){let data=JSON.stringify(quotes),ok=false;try{localStorage.setItem(KEY,data);ok=localStorage.getItem(KEY)===data}catch(e){}try{await putDB(quotes);ok=true}catch(e){}try{if(navigator.storage?.persist)navigator.storage.persist()}catch(e){}if(!ok)throw Error('Storage unavailable')}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.screen===id));if(id==='dashboard')renderDashboard();if(id==='saved')renderSaved();if(id==='settings')loadSettings();scrollTo(0,0)}
function addItem(d='',a=''){let r=document.createElement('div');r.className='item';r.innerHTML=`<input class="item-desc" placeholder="Material or other cost" value="${esc(d)}"><input class="item-amount" type="number" min="0" step="0.01" placeholder="$" value="${esc(a)}"><button type="button">✕</button>`;r.querySelector('button').onclick=()=>{r.remove();calc()};r.querySelectorAll('input').forEach(x=>x.oninput=calc);$('lineItems').appendChild(r)}
function calc(){let mat=[...document.querySelectorAll('.item-amount')].reduce((s,x)=>s+(+x.value||0),0),lab=(+$('labourHours').value||0)*(+$('hourlyRate').value||0),sub=mat+lab,gst=$('gstEnabled').checked?sub*.1:0,total=sub+gst;$('subtotal').textContent=money(sub);$('gst').textContent=money(gst);$('grandTotal').textContent=money(total);return{materials:mat,labour:lab,subtotal:sub,gst,total}}
function reset(){editingId=null;currentQuote=null;$('quoteFormEl').reset();$('lineItems').innerHTML='';addItem();$('hourlyRate').value=settings.defaultRate||90;calc();$('quoteFormTitle').textContent='New quote';$('saveQuoteBtn').textContent='Save & Preview Quote'}
function edit(q){editingId=q.id;$('quoteFormTitle').textContent='Edit quote';$('saveQuoteBtn').textContent='Update Quote';$('customerName').value=q.customerName||'';$('customerPhone').value=q.customerPhone||'';$('customerEmail').value=q.customerEmail||'';$('jobDescription').value=q.jobDescription||'';$('labourHours').value=q.labourHours||0;$('hourlyRate').value=q.hourlyRate||90;$('gstEnabled').checked=+q.gst>0;$('lineItems').innerHTML='';(q.items||[]).forEach(i=>addItem(i.description,i.amount));if(!q.items?.length)addItem();calc();show('quoteForm')}
function collect(){let c=calc(),items=[...document.querySelectorAll('.item')].map(r=>({description:r.querySelector('.item-desc').value.trim(),amount:+r.querySelector('.item-amount').value||0})).filter(x=>x.description||x.amount);return{id:editingId||crypto.randomUUID(),number:currentQuote?.number||'Q-'+String(Date.now()).slice(-6),date:currentQuote?.date||new Date().toLocaleDateString('en-AU'),savedAt:Date.now(),customerName:$('customerName').value.trim(),customerPhone:$('customerPhone').value.trim(),customerEmail:$('customerEmail').value.trim(),jobDescription:$('jobDescription').value.trim(),items,labourHours:+$('labourHours').value||0,hourlyRate:+$('hourlyRate').value||0,...c}}
function card(q){return`<div class="quote-card" data-id="${q.id}"><div class="row"><b>${esc(q.customerName||'Unnamed customer')}</b><b>${money(q.total)}</b></div><small>${esc(q.number)} · ${esc(q.date)}</small><div class="desc">${esc(q.jobDescription||'')}</div></div>`}
function bind(){document.querySelectorAll('.quote-card').forEach(x=>x.onclick=()=>{currentQuote=quotes.find(q=>q.id===x.dataset.id);if(currentQuote){preview(currentQuote);show('preview')}})}
function renderDashboard(){$('quoteCount').textContent=quotes.length;$('totalQuoted').textContent=money(quotes.reduce((s,q)=>s+(+q.total||0),0));$('recentQuotes').innerHTML=quotes.length?quotes.slice(0,5).map(card).join(''):'<div class="empty">No quotes yet.<br><br>Tap <b>New Quote</b> to create your first one.</div>';bind()}
function renderSaved(){$('allQuotes').innerHTML=quotes.length?quotes.map(card).join(''):'<div class="empty">No saved quotes yet.</div>';bind()}
const logo='<svg class="logo" viewBox="0 0 100 100"><rect x="2" y="2" width="96" height="96" rx="20" fill="#171717" stroke="#ffb000" stroke-width="4"/><path d="M27 35l18-18 28 28-7 7-28-28-11 11z" fill="#d8d8d8"/><path d="M45 19l13-7 31 31-7 7z" fill="#ffb000"/><text x="50" y="70" text-anchor="middle" font-size="13" font-weight="900" fill="#fff">TRADIE</text><rect x="19" y="73" width="62" height="14" rx="5" fill="#ffb000"/><text x="50" y="84" text-anchor="middle" font-size="9" font-weight="900" fill="#111">QUOTE BUDDY</text></svg>';
function preview(q){$('quotePreview').innerHTML=`<div class="paper-head"><div>${logo}<h1>${esc(settings.businessName||'Your Business Name')}</h1><div>${esc(settings.businessAddress||'')}</div><div>${esc(settings.businessPhone||'')} ${settings.businessEmail?'· '+esc(settings.businessEmail):''}</div><div>${settings.abn?'ABN '+esc(settings.abn):''}</div></div><div class="paper-meta"><h2>QUOTE</h2><b>${esc(q.number)}</b><div>${esc(q.date)}</div></div></div><div><b>Quote for</b><div>${esc(q.customerName)}</div><div>${esc(q.customerPhone)}</div><div>${esc(q.customerEmail)}</div></div><p class="job"><b>Job description</b><br>${esc(q.jobDescription).replace(/\n/g,'<br>')}</p><table><thead><tr><th>Description</th><th>Amount</th></tr></thead><tbody>${q.items.map(i=>`<tr><td>${esc(i.description)}</td><td>${money(i.amount)}</td></tr>`).join('')}${q.labourHours?`<tr><td>Labour (${q.labourHours} hrs × ${money(q.hourlyRate)}/hr)</td><td>${money(q.labour)}</td></tr>`:''}</tbody></table><div class="paper-total"><div><span>Subtotal</span><span>${money(q.subtotal)}</span></div><div><span>GST</span><span>${money(q.gst)}</span></div><div class="grand"><span>Total</span><span>${money(q.total)}</span></div></div><p class="thanks">Thank you for the opportunity to quote on your job.</p>`)}
async function pdf(){if(!currentQuote)return;let b=$('printBtn'),old=b.textContent;try{b.textContent='Creating PDF…';let blob=await html2pdf().set({margin:.2,image:{type:'jpeg',quality:.98},html2canvas:{scale:2,useCORS:true,backgroundColor:'#fff'},jsPDF:{unit:'mm',format:'a4',orientation:'portrait'}}).from($('quotePreview')).outputPdf('blob'),file=new File([blob],currentQuote.number+'.pdf',{type:'application/pdf'});if(navigator.share){try{if(navigator.canShare&&!navigator.canShare({files:[file]}))throw Error('File sharing unavailable');await navigator.share({title:'Quote '+currentQuote.number,files:[file]});return}catch(e){if(e.name==='AbortError')return}}let u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=currentQuote.number+'.pdf';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}catch(e){if(e.name!=='AbortError')alert('Could not create or download the PDF. Please try again.')}finally{b.textContent=old}}
function loadSettings(){[['businessName','businessName'],['abn','abn'],['businessPhone','businessPhone'],['businessEmail','businessEmail'],['businessAddress','businessAddress'],['defaultRate','defaultRate']].forEach(([i,k])=>$(i).value=settings[k]??'')}
$('newQuoteBtn').onclick=()=>{reset();show('quoteForm')};$('addItemBtn').onclick=()=>addItem();$('quoteFormEl').onsubmit=async e=>{e.preventDefault();let q=collect();if(editingId){let i=quotes.findIndex(x=>x.id===editingId);if(i>=0)quotes[i]=q}else quotes.unshift(q);currentQuote=q;try{await persist();preview(q);show('preview')}catch(e){alert('The quote could not be saved. Browser storage is unavailable.')}};$('settingsBtn').onclick=()=>show('settings');$('viewAllBtn').onclick=()=>show('saved');$('printBtn').onclick=pdf;$('editQuoteBtn').onclick=()=>currentQuote&&edit(currentQuote);$('deleteQuoteBtn').onclick=()=>currentQuote&&$('confirmModal').classList.add('show');$('cancelDelete').onclick=()=>$('confirmModal').classList.remove('show');$('confirmDelete').onclick=async()=>{quotes=quotes.filter(q=>q.id!==currentQuote?.id);$('confirmModal').classList.remove('show');try{await persist();currentQuote=null;show('saved')}catch(e){alert('Could not save the deletion.')}};
$('settingsForm').onsubmit=e=>{e.preventDefault();settings={businessName:$('businessName').value.trim(),abn:$('abn').value.trim(),businessPhone:$('businessPhone').value.trim(),businessEmail:$('businessEmail').value.trim(),businessAddress:$('businessAddress').value.trim(),defaultRate:+$('defaultRate').value||0};try{localStorage.setItem(SET,JSON.stringify(settings))}catch(e){}alert('Business settings saved');show('dashboard')};$('backupBtn').onclick=()=>{let blob=new Blob([JSON.stringify({version:2,quotes,settings},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='tradie-quote-buddy-backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};$('restoreBtn').onclick=()=>$('restoreFile').click();$('restoreFile').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader;r.onload=async()=>{try{let d=JSON.parse(r.result);if(!Array.isArray(d.quotes))throw Error();quotes=merge(d.quotes,[]);if(d.settings)settings={...settings,...d.settings};localStorage.setItem(SET,JSON.stringify(settings));await persist();alert('Restored '+quotes.length+' quote'+(quotes.length===1?'':'s')+'.');show('dashboard')}catch(x){alert('That backup file could not be restored.')}};r.readAsText(f);e.target.value=''};
$('subscribeBtn')?.addEventListener('click',()=>location.href='subscription.html');document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>show('dashboard'));document.querySelectorAll('.nav').forEach(n=>n.onclick=()=>{if(n.dataset.screen==='quoteForm')reset();show(n.dataset.screen)});$('labourHours').oninput=calc;$('hourlyRate').oninput=calc;$('gstEnabled').onchange=calc;
show('dashboard');addItem();load();
if('serviceWorker' in navigator) window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
