(function(){
'use strict';
function q(s){return document.querySelector(s)}
function qa(s){return Array.prototype.slice.call(document.querySelectorAll(s))}
function read(k,f){try{var v=JSON.parse(localStorage.getItem(k)||'');return v==null?f:v}catch(e){return f}}
function money(v){return new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(Number(v)||0)}
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'}[c]})}
function ensureScreen(id,title,sub){var s=document.getElementById(id);if(!s){s=document.createElement('section');s.id=id;s.className='screen biz-screen';s.innerHTML='<div class="biz-wrap"><div class="biz-head"><div><p class="eyebrow">DUSTYBOOTS</p><h1>'+title+'</h1><p>'+sub+'</p></div></div><div class="biz-card" id="'+id+'Content"></div></div>';q('main').appendChild(s)}return s}
function openBusiness(id){var info={itemsServices:['Items & Services','Save your common materials, services and labour rates for faster quoting.'],payments:['Payments','Keep track of what has been paid and what still needs chasing.'],reports:['Reports','A clear view of your quoting, invoicing and cash position.']}[id];if(!info)return;var s=ensureScreen(id,info[0],info[1]);qa('.screen').forEach(function(x){x.classList.toggle('active',x===s)});qa('.nav').forEach(function(x){x.classList.toggle('active',x.getAttribute('data-screen')===id)});window.scrollTo(0,0);if(id==='itemsServices')renderItems(s);if(id==='payments')renderPayments(s);if(id==='reports'){if(window.tqbBuildReports){window.tqbBuildReports()}else{renderReports(s)}}}
function renderItems(s){var list=read('tqb_items_services_v1',[]);if(!Array.isArray(list))list=[];var c=q('#itemsServicesContent');c.innerHTML='<div class="biz-toolbar"><input id="fixedItemSearch" placeholder="Search items & services..."><button class="secondary" id="fixedAddItem" type="button">＋ Add item</button></div><div id="fixedItemTable"></div>';function paint(){var term=(q('#fixedItemSearch').value||'').toLowerCase();var a=list.filter(function(x){return String(x.name||'').toLowerCase().indexOf(term)>=0||String(x.description||'').toLowerCase().indexOf(term)>=0});q('#fixedItemTable').innerHTML=a.length?'<table class="biz-table"><thead><tr><th>Name</th><th>Type</th><th>Unit</th><th>Price</th><th></th></tr></thead><tbody>'+a.map(function(x){return '<tr><td><b>'+esc(x.name)+'</b><div class="biz-muted">'+esc(x.description||'')+'</div></td><td>'+esc(x.type||'Service')+'</td><td>'+esc(x.unit||'each')+'</td><td>'+money(x.price)+'</td><td><button class="biz-mini" data-e="'+esc(x.id)+'">Edit</button> <button class="biz-mini danger" data-d="'+esc(x.id)+'">Delete</button></td></tr>'}).join('')+'</tbody></table>':'<div class="biz-empty">No items or services yet.</div>';qa('#fixedItemTable [data-e]').forEach(function(b){b.onclick=function(){edit(b.dataset.e)}});qa('#fixedItemTable [data-d]').forEach(function(b){b.onclick=function(){if(confirm('Delete this item or service?')){list=list.filter(function(x){return String(x.id)!==String(b.dataset.d)});localStorage.setItem('tqb_items_services_v1',JSON.stringify(list));paint()}}})}function edit(id){var x=list.find(function(v){return String(v.id)===String(id)})||{name:'',type:'Service',unit:'each',price:0};var name=prompt('Item or service name:',x.name);if(name===null)return;var price=prompt('Price:',String(Number(x.price)||0));if(price===null)return;var unit=prompt('Unit:',x.unit||'each');if(unit===null)return;var type=prompt('Type: Material, Service or Labour',x.type||'Service');if(type===null)return;var obj={id:id||String(Date.now()),name:name.trim(),type:type||'Service',unit:unit||'each',price:Number(price)||0,description:x.description||''};if(!obj.name)return;if(id)list=list.map(function(v){return String(v.id)===String(id)?obj:v});else list.unshift(obj);localStorage.setItem('tqb_items_services_v1',JSON.stringify(list));paint()}q('#fixedItemSearch').oninput=paint;q('#fixedAddItem').onclick=function(){edit(null)};paint()}
function renderPayments(s){var a=read('tqb_invoices_v1',[]);if(!Array.isArray(a))a=[];var paid=a.filter(function(x){return String(x.status||'').toLowerCase()==='paid'}),out=a.filter(function(x){return String(x.status||'').toLowerCase()!=='paid'}),p=paid.reduce(function(t,x){return t+(Number(x.total)||0)},0),o=out.reduce(function(t,x){return t+(Number(x.total)||0)},0);q('#paymentsContent').innerHTML='<div class="biz-kpis"><div class="biz-kpi green"><span>Paid</span><b>'+money(p)+'</b></div><div class="biz-kpi red"><span>Outstanding</span><b>'+money(o)+'</b></div><div class="biz-kpi"><span>Paid invoices</span><b>'+paid.length+'</b></div><div class="biz-kpi yellow"><span>Awaiting payment</span><b>'+out.length+'</b></div></div><div class="biz-card"><h2>Payment history</h2><table class="biz-table"><thead><tr><th>Invoice</th><th>Customer</th><th>Date</th><th>Status</th><th>Amount</th></tr></thead><tbody>'+(a.length?a.map(function(x){return '<tr><td>'+esc(x.number||'')+'</td><td>'+esc(x.customerName||'')+'</td><td>'+esc(x.invoiceDate||'')+'</td><td>'+esc(x.status||'Unpaid')+'</td><td>'+money(x.total)+'</td></tr>'}).join(''):'<tr><td colspan="5" class="biz-empty">No invoices yet.</td></tr>')+'</tbody></table></div>'}
function renderReports(s){var a=read('tqb_invoices_v1',[]),qs=read('tqb_quotes_v6',[]);if(!Array.isArray(a))a=[];if(!Array.isArray(qs))qs=[];var p=a.filter(function(x){return String(x.status||'').toLowerCase()==='paid'}),total=a.reduce(function(t,x){return t+(Number(x.total)||0)},0),paid=p.reduce(function(t,x){return t+(Number(x.total)||0)},0),accepted=qs.filter(function(x){return String(x.status||x.quoteStatus||'').toLowerCase().indexOf('accept')>=0}).length;s.querySelector('#reportsContent').innerHTML='<div class="biz-kpis"><div class="biz-kpi"><span>Total invoiced</span><b>'+money(total)+'</b></div><div class="biz-kpi green"><span>Total paid</span><b>'+money(paid)+'</b></div><div class="biz-kpi red"><span>Outstanding</span><b>'+money(total-paid)+'</b></div><div class="biz-kpi yellow"><span>Quote conversion</span><b>'+(qs.length?Math.round(accepted/qs.length*100):0)+'%</b></div></div><div class="biz-card"><h2>Business snapshot</h2><p>Quotes: <b>'+qs.length+'</b> &nbsp; Accepted: <b>'+accepted+'</b> &nbsp; Invoices: <b>'+a.length+'</b></p></div>'}
function wire(){if(window.__dustyBusinessFixed)return;window.__dustyBusinessFixed=true;document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('.nav[data-screen]');if(!b)return;var id=b.getAttribute('data-screen');if(id!=='itemsServices'&&id!=='payments'&&id!=='reports')return;e.preventDefault();e.stopImmediatePropagation();openBusiness(id)},true)}
function init(){wire()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();