(function(){
'use strict';
if(window.__dustyBusinessNavFixLoaded)return;
window.__dustyBusinessNavFixLoaded=true;
function load(src){var s=document.createElement('script');s.src=src;s.defer=true;s.onerror=function(){console.error('DustyBoots failed to load',src)};document.head.appendChild(s)}
function $(id){return document.getElementById(id)}
function read(k){try{var x=JSON.parse(localStorage.getItem(k)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function write(k,x){try{localStorage.setItem(k,JSON.stringify(x));return true}catch(e){alert('Could not save customer. Please check browser storage.');return false}}
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'})[c]})}
function money(v){return new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(Number(v)||0)}
function active(id){document.querySelectorAll('.screen').forEach(function(s){s.classList.toggle('active',s.id===id)});document.querySelectorAll('.nav').forEach(function(n){n.classList.toggle('active',n.getAttribute('data-screen')===id)});window.scrollTo(0,0)}
function ensure(id,title,sub){var s=$(id);if(!s){var m=document.querySelector('main');if(!m)return null;s=document.createElement('section');s.id=id;s.className='screen';m.appendChild(s)}if(!s.querySelector('.db-data-page'))s.innerHTML='<div class="db-data-page" style="max-width:1120px;margin:0 auto"><p class="eyebrow" style="margin:0 0 5px">DUSTYBOOTS</p><h1 style="margin:0;font-size:30px">'+title+'</h1><p style="margin:6px 0 22px;color:#69717c">'+sub+'</p><div id="'+id+'Data"></div></div>';return s}
function customers(){var saved=read('tqb_customers_v1'),quotes=read('tqb_quotes_v6'),invoices=read('tqb_invoices_v1'),map={};saved.forEach(function(c){if(c&&c.name)map[String(c.name).trim().toLowerCase()]=Object.assign({},c)});quotes.concat(invoices).forEach(function(r){var name=String(r.customerName||'').trim();if(!name)return;var k=name.toLowerCase();if(!map[k])map[k]={id:'cust-'+k,name:name,phone:r.customerPhone||'',email:r.customerEmail||'',address:r.customerAddress||''};else{if(!map[k].phone)map[k].phone=r.customerPhone||'';if(!map[k].email)map[k].email=r.customerEmail||'';if(!map[k].address)map[k].address=r.customerAddress||''}});return Object.keys(map).map(function(k){var c=map[k];var qs=quotes.filter(function(q){return String(q.customerName||'').trim().toLowerCase()===k}),ins=invoices.filter(function(i){return String(i.customerName||'').trim().toLowerCase()===k});c.quoteCount=qs.length;c.invoiceCount=ins.length;c.totalInvoiced=ins.reduce(function(a,x){return a+(Number(x.total)||0)},0);c.totalPaid=ins.filter(function(x){return String(x.status||'').toLowerCase()==='paid'}).reduce(function(a,x){return a+(Number(x.total)||0)},0);c.outstanding=c.totalInvoiced-c.totalPaid;return c}).sort(function(a,b){return a.name.localeCompare(b.name)})}
function addCustomerForm(c){var d=$('customersData');d.innerHTML='<div style="background:#fff;border:1px solid #e4e8ed;border-radius:15px;padding:20px"><h2 style="margin:0 0 18px">Add Customer</h2><div style="display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px"><label style="grid-column:1/-1">Customer name<input id="newCustomerName" placeholder="e.g. John Smith"></label><label>Phone<input id="newCustomerPhone" placeholder="04xx xxx xxx"></label><label>Email<input id="newCustomerEmail" type="email" placeholder="customer@email.com"></label><label style="grid-column:1/-1">Address<textarea id="newCustomerAddress" rows="2" placeholder="Street, suburb, state, postcode"></textarea></label><label style="grid-column:1/-1">Private notes<textarea id="newCustomerNotes" rows="3" placeholder="Optional notes"></textarea></label></div><div style="display:flex;gap:10px;margin-top:18px"><button class="secondary" id="cancelNewCustomer" style="flex:1">Cancel</button><button class="primary" id="saveNewCustomer" style="flex:1">Save Customer</button></div></div>';$('cancelNewCustomer').onclick=function(){customerPage()};$('saveNewCustomer').onclick=function(){var name=$('newCustomerName').value.trim();if(!name){alert('Please enter a customer name.');$('newCustomerName').focus();return}var list=read('tqb_customers_v1');var obj={id:'cust-'+Date.now()+'-'+Math.random().toString(16).slice(2),name:name,phone:$('newCustomerPhone').value.trim(),email:$('newCustomerEmail').value.trim(),address:$('newCustomerAddress').value.trim(),notes:$('newCustomerNotes').value.trim(),createdAt:Date.now()};list.unshift(obj);if(write('tqb_customers_v1',list)){customerPage();setTimeout(function(){var cards=document.querySelectorAll('#customersData [data-customer-name]');cards.forEach(function(card){if(card.getAttribute('data-customer-name')===name)card.scrollIntoView({block:'center'})})},50)}}}
function customerPage(){var s=ensure('customers','Customers','Your customers, quotes and account history.');if(!s)return;var list=customers(),c=$('customersData');c.innerHTML='<div style="background:#fff;border:1px solid #e4e8ed;border-radius:15px;padding:20px"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:16px"><div><b style="font-size:18px">Customer list</b><div style="font-size:12px;color:#69717c;margin-top:3px">Add and manage your customer records.</div></div><button class="primary" id="addCustomerButton">＋ Add Customer</button></div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px">'+(list.length?list.map(function(x){return '<div data-customer-name="'+esc(x.name)+'" style="border:1px solid #edf0f3;border-radius:12px;padding:16px"><div style="display:flex;justify-content:space-between;gap:10px"><b>'+esc(x.name)+'</b><b>'+money(x.totalInvoiced)+'</b></div><div style="font-size:12px;color:#69717c;margin-top:5px">'+esc(x.phone||x.email||'No contact details')+'</div><div style="font-size:12px;margin-top:12px">Quotes: <b>'+x.quoteCount+'</b> &nbsp; Invoices: <b>'+x.invoiceCount+'</b> &nbsp; Paid: <b>'+money(x.totalPaid)+'</b> &nbsp; Due: <b>'+money(x.outstanding)+'</b></div></div>'}).join(''):'<div style="text-align:center;padding:45px 20px;color:#69717c">No customers found yet. Add your first customer above.</div>')+'</div></div>';if($('addCustomerButton'))$('addCustomerButton').onclick=function(){addCustomerForm()};active('customers')}
function invoicePage(){var s=ensure('invoices','Invoices','Create, track and manage your customer invoices.');if(!s)return;var list=read('tqb_invoices_v1'),c=$('invoicesData');c.innerHTML='<div class="tqb-mobile-invoice-list" style="background:#fff;border:1px solid #e4e8ed;border-radius:15px;padding:14px"><div style="display:grid;gap:14px">'+(list.length?list.map(function(x){return '<div class="tqb-mobile-invoice-card" data-invoice-id="'+esc(x.id)+'" style="border:1px solid #e1e5eb;border-radius:14px;padding:20px;display:flex;justify-content:space-between;gap:18px;align-items:center;min-height:150px;cursor:pointer;touch-action:manipulation"><div style="min-width:0;flex:1"><b style="display:block;font-size:25px;line-height:1.05;color:#111827">'+esc(x.number||'Invoice')+'</b><div style="color:#69717c;font-size:17px;margin-top:8px">'+esc(x.customerName||'Unnamed customer')+'</div><div style="font-size:28px;font-weight:800;line-height:1.1;margin-top:8px;color:#111827">'+money(x.total)+'</div><div style="color:#69717c;font-size:17px;margin-top:8px">'+esc(x.invoiceDate||x.date||'')+'</div><div style="font-size:17px;margin-top:6px">'+esc(x.status||'Unpaid')+'</div></div><div aria-hidden="true" style="font-size:42px;line-height:1;color:#69717c;font-weight:300">›</div></div>'}).join(''):'<div style="text-align:center;padding:45px 20px;color:#69717c">No invoices yet. Accepted quotes will appear here when converted to an invoice.</div>')+'</div></div>';active('invoices')}
function businessPage(id){if(window.tqbOpenBusiness){try{window.tqbOpenBusiness(id);return}catch(e){console.error('DustyBoots business page',e)}}}
function go(id){if(id==='customers'){customerPage();return}if(id==='invoices'){invoicePage();return}if(id==='itemsServices'||id==='payments'||id==='reports'){businessPage(id);return}if($(id))active(id)}
function order(){var n=document.querySelector('.bottom-nav');if(!n)return;['dashboard','quoteForm','saved','invoices','customers','itemsServices','payments','reports','settings'].forEach(function(id){var b=n.querySelector('[data-screen="'+id+'");if(b)n.appendChild(b)})}
function init(){load('./invoice-nav-bridge.js?v=6');load('./business-pages-preload.js?v=10');order();document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('.bottom-nav .nav[data-screen]');if(!b)return;var id=b.getAttribute('data-screen');if(['customers','invoices','itemsServices','payments','reports'].indexOf(id)<0)return;e.preventDefault();e.stopImmediatePropagation();go(id)},true);setTimeout(order,100);setTimeout(order,500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
