(function(){
'use strict';
var STATUS='https://cychngcvhgtfuahavlqq.supabase.co/functions/v1/stripe-subscription-status';
var URL='https://cychngcvhgtfuahavlqq.supabase.co/rest/v1/rpc/tqb_cloud_sync';
var KEY='tqb_square_owner_key_v1',QUOTES='tqb_quotes_v6',SETTINGS='tqb_settings_v6',PUBLISHABLE='sb_publishable_nc_WEOT-I9hR5oH9hEMURQ_mG92V_VA';
var timer=null,lastSnapshot='';
function $(id){return document.getElementById(id)}
function owner(){try{return localStorage.getItem(KEY)||''}catch(e){return''}}
function read(k,f){try{var r=localStorage.getItem(k);return r?JSON.parse(r):f}catch(e){return f}}
function write(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch(e){return false}}
function rpc(action,quotes,settings){var body={p_owner_key:owner(),p_action:action};if(action==='put'){body.p_quotes=quotes;body.p_settings=settings}return fetch(URL,{method:'POST',headers:{'Content-Type':'application/json','apikey':PUBLISHABLE,'Authorization':'Bearer '+PUBLISHABLE},body:JSON.stringify(body)}).then(function(r){return r.text().then(function(raw){var d={};try{d=raw?JSON.parse(raw):{}}catch(_){d={}}if(!r.ok){var msg=(d&&d.message)||((d&&d.error)||'Cloud sync request failed.');throw new Error(msg)}return d})})}
function checkPro(){var k=owner();if(!k)return Promise.reject(new Error('This device does not have an owner key.'));return fetch(STATUS,{headers:{'x-owner-key':k},cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('Could not check Pro status.');return r.json()}).then(function(d){if(!d||d.plan!=='pro')throw new Error('Pro subscription required.');return d})}
function snapshot(){return JSON.stringify({quotes:read(QUOTES,[]),settings:read(SETTINGS,{})})}
function setMessage(text,good){var el=$('cloudSyncMessage');if(!el)return;el.textContent=text;el.style.color=good?'#166534':'#991b1b'}
function refreshState(){checkPro().then(function(){var s=$('cloudSyncStatus');if(s){s.textContent='✓ Pro cloud sync is enabled';s.style.color='#166534'}var b=$('cloudUploadBtn'),r=$('cloudRestoreBtn');if(b)b.disabled=false;if(r)r.disabled=false}).catch(function(e){var s=$('cloudSyncStatus');if(s){s.textContent='🔒 '+(e.message||'Pro subscription required');s.style.color='#991b1b'}var b=$('cloudUploadBtn'),r=$('cloudRestoreBtn');if(b)b.disabled=true;if(r)r.disabled=true})}
function upload(silent){var quotes=read(QUOTES,[]),settings=read(SETTINGS,{});return checkPro().then(function(){return rpc('put',quotes,settings)}).then(function(){lastSnapshot=snapshot();if(!silent)setMessage('✓ Saved to the cloud.',true)}).catch(function(e){if(!silent)setMessage(e.message||'Cloud save failed.',false);throw e})}
function restore(){setMessage('Checking cloud data…',true);checkPro().then(function(){return rpc('get')}).then(function(d){if(!d||!d.found){setMessage('No cloud backup exists yet. Upload this device first.',false);return}if(!confirm('Restore your cloud data to this device? Local quotes and settings will be replaced.')){setMessage('Restore cancelled.',false);return}if(!write(QUOTES,d.quotes||[])||!write(SETTINGS,d.settings||{}))throw new Error('Could not write the restored data to this device.');lastSnapshot=snapshot();setMessage('✓ Cloud data restored. Reloading…',true);setTimeout(function(){location.reload()},500)}).catch(function(e){setMessage(e.message||'Cloud restore failed.',false)})}
function build(){if($('cloudSyncCard'))return;var square=$('squarePaymentsBlock'),form=$('settingsForm');if(!form)return;var card=document.createElement('div');card.id='cloudSyncCard';card.className='feature-card';card.style.marginTop='24px';card.innerHTML='<h3>☁️ Pro Cloud Sync</h3><p>Keep your quotes and business settings backed up in the cloud. Pro status is checked by the server before cloud data can be read or saved.</p><div id="cloudSyncStatus" style="font-size:13px;font-weight:700;margin:10px 0;color:#666">Checking Pro access…</div><div class="backup-row"><button type="button" class="primary" id="cloudUploadBtn">☁️ Sync now</button><button type="button" class="secondary" id="cloudRestoreBtn">⬇️ Restore cloud</button></div><p id="cloudSyncMessage" class="storage-note" style="margin:10px 0 0">Cloud sync is a Pro feature.</p>';if(square&&square.parentNode)square.parentNode.insertBefore(card,square.nextSibling);else form.insertBefore(card,form.firstChild);$('cloudUploadBtn').onclick=function(){setMessage('Saving to cloud…',true);upload(false)};$('cloudRestoreBtn').onclick=restore;refreshState();lastSnapshot=snapshot();if(timer)clearInterval(timer);timer=setInterval(function(){if(document.visibilityState==='hidden')return;var now=snapshot();if(now!==lastSnapshot){checkPro().then(function(){return upload(true)}).catch(function(){})}},15000)}
function init(){build();window.addEventListener('storage',function(e){if(e.key===QUOTES||e.key===SETTINGS)lastSnapshot=''});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
