(function(){
'use strict';
if(window.__dustyCloudSyncV2Loaded)return;
window.__dustyCloudSyncV2Loaded=true;
var API='https://cychngcvhgtfuahavlqq.supabase.co/rest/v1/rpc/tqb_cloud_sync';
var STATUS='https://cychngcvhgtfuahavlqq.supabase.co/functions/v1/stripe-subscription-status';
var ANON='sb_publishable_nc_WEOT-I9hR5oH9hEMURQ_mG92V_VA',OWNER_KEY='tqb_square_owner_key_v1';
var timer=null,last='';
function owner(){return localStorage.getItem(OWNER_KEY)||''}
function read(k,f){try{var x=localStorage.getItem(k);return x?JSON.parse(x):f}catch(e){return f}}
function allData(){var d={};for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i);if(k&&k.indexOf('tqb_')===0&&k!==OWNER_KEY)d[k]=localStorage.getItem(k)}return d}
function snapshot(){return JSON.stringify(allData())}
function rpc(body){return fetch(API,{method:'POST',headers:{'Content-Type':'application/json','apikey':ANON,'Authorization':'Bearer '+ANON},body:JSON.stringify(body),cache:'no-store'}).then(function(r){return r.text().then(function(t){var d={};try{d=t?JSON.parse(t):{}}catch(e){}if(!r.ok)throw new Error(d.message||d.error||'Cloud sync failed.');return d})})}
function activePro(){var k=owner();if(!k)return Promise.reject(new Error('No DustyBoots device key found.'));return fetch(STATUS,{headers:{'x-owner-key':k},cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('Could not check Pro status.');return r.json()}).then(function(d){if(!d||d.plan!=='pro')throw new Error('Pro subscription required.');return d})}
function setMsg(t,good){var e=document.getElementById('dbCloudV2Msg');if(e){e.textContent=t;e.style.color=good?'#166534':'#991b1b'}}
function put(silent){var k=owner(),d=allData();return activePro().then(function(){return rpc({p_owner_key:k,p_action:'put',p_quotes:read('tqb_quotes_v6',[]),p_settings:read('tqb_settings_v6',{}),p_data:d})}).then(function(){last=snapshot();if(!silent)setMsg('✓ All DustyBoots data is synced.',true)}).catch(function(e){if(!silent)setMsg(e.message||'Cloud sync failed.',false);throw e})}
function restore(){setMsg('Restoring your DustyBoots data…',true);activePro().then(function(){return rpc({p_owner_key:owner(),p_action:'get'})}).then(function(d){if(!d||!d.found){setMsg('No cloud backup exists yet.',false);return}var data=d.data&&typeof d.data==='object'?d.data:{};Object.keys(data).forEach(function(k){if(k&&k.indexOf('tqb_')===0&&k!==OWNER_KEY)localStorage.setItem(k,String(data[k]))});if(d.quotes)localStorage.setItem('tqb_quotes_v6',JSON.stringify(d.quotes));if(d.settings)localStorage.setItem('tqb_settings_v6',JSON.stringify(d.settings));last=snapshot();setMsg('✓ Data restored. Reloading…',true);setTimeout(function(){location.reload()},700)}).catch(function(e){setMsg(e.message||'Cloud restore failed.',false)})}
function style(){if(document.getElementById('dbCloudV2Style'))return;var s=document.createElement('style');s.id='dbCloudV2Style';s.textContent='.db-cloud-v2{margin:24px 0;padding:20px;border:1px solid #e1e5ea;border-radius:14px;background:#fff}.db-cloud-v2 h3{margin:0 0 7px}.db-cloud-v2 p{font-size:13px;color:#69717c;line-height:1.45}.db-cloud-v2-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:13px}.db-cloud-v2 button{border:0;border-radius:9px;padding:11px 15px;font-weight:800;cursor:pointer}.db-cloud-v2 .primary{background:#171717;color:#fff}.db-cloud-v2 .secondary{background:#f1f3f5;color:#171717}';document.head.appendChild(s)}
function build(){if(document.getElementById('db-cloud-v2'))return;var form=document.getElementById('settingsForm');if(!form)return;var card=document.createElement('section');card.id='db-cloud-v2';card.className='db-cloud-v2';card.innerHTML='<h3>☁️ DustyBoots Cloud Sync</h3><p>One DustyBoots business across your devices. Pro members can sync quotes, invoices, customers, items, payments and settings.</p><div class="db-cloud-v2-actions"><button type="button" class="primary" id="dbCloudV2Sync">Sync now</button><button type="button" class="secondary" id="dbCloudV2Restore">Restore cloud</button></div><div id="dbCloudV2Msg" style="margin-top:10px;font-size:13px;font-weight:700">Cloud sync is a Pro feature.</div>';form.appendChild(card);document.getElementById('dbCloudV2Sync').onclick=function(){setMsg('Saving all DustyBoots data…',true);put(false)};document.getElementById('dbCloudV2Restore').onclick=function(){if(confirm('Restore the cloud copy to this device? This replaces local DustyBoots data.'))restore()};last=snapshot();if(timer)clearInterval(timer);timer=setInterval(function(){if(document.visibilityState==='hidden')return;var now=snapshot();if(now!==last)put(true).catch(function(){});},15000)}
function init(){style();build()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();setTimeout(init,500);setTimeout(init,1500)
})();
