(function(){
'use strict';
if(window.__dustyCloudSyncV2Loaded)return;
window.__dustyCloudSyncV2Loaded=true;
var API='https://cychngcvhgtfuahavlqq.supabase.co/rest/v1/rpc/tqb_cloud_sync';
var STATUS='https://cychngcvhgtfuahavlqq.supabase.co/functions/v1/stripe-subscription-status';
var ANON='sb_publishable_nc_WEOT-I9hR5oH9hEMURQ_mG92V_VA',OWNER_KEY='tqb_square_owner_key_v1';
var timer=null,last='',lastCloudUpdated='',busy=false;
function owner(){try{return localStorage.getItem(OWNER_KEY)||''}catch(e){return''}}
function validOwner(k){return /^[a-f0-9]{64}$/i.test(String(k||''))}
function read(k,f){try{var x=localStorage.getItem(k);return x?JSON.parse(x):f}catch(e){return f}}
function allData(){var d={};for(var i=0;i<localStorage.length;i++){var k=localStorage.key(i);if(k&&k.indexOf('tqb_')===0&&k!==OWNER_KEY)d[k]=localStorage.getItem(k)}return d}
function snapshot(){return JSON.stringify(allData())}
function rpc(body){return fetch(API,{method:'POST',headers:{'Content-Type':'application/json','apikey':ANON,'Authorization':'Bearer '+ANON},body:JSON.stringify(body),cache:'no-store'}).then(function(r){return r.text().then(function(t){var d={};try{d=t?JSON.parse(t):{}}catch(e){}if(!r.ok)throw new Error(d.message||d.error||'Cloud sync failed.');return d})})}
function activePro(){var k=owner();if(!validOwner(k))return Promise.reject(new Error('No DustyBoots device key found.'));return fetch(STATUS,{headers:{'x-owner-key':k},cache:'no-store'}).then(function(r){if(!r.ok)throw new Error('Could not check Pro status.');return r.json()}).then(function(d){if(!d||d.plan!=='pro')throw new Error('Pro subscription required.');return d})}
function setMsg(t,good){var e=document.getElementById('dbCloudV2Msg');if(e){e.textContent=t;e.style.color=good?'#166534':'#991b1b'}}
function itemKey(x){if(!x||typeof x!=='object')return '';return String(x.id||x.number||x.quoteNumber||x.invoiceNumber||x.code||x.name||'')}
function mergeArrays(local,cloud){var out=[],seen={};function add(x,prefer){var k=itemKey(x);if(k){if(seen[k]!==undefined){if(prefer)out[seen[k]]=x;return}seen[k]=out.length}out.push(x)};(Array.isArray(cloud)?cloud:[]).forEach(function(x){add(x,true)});(Array.isArray(local)?local:[]).forEach(function(x){add(x,false)});return out}
function mergeData(local,cloud){var out={};Object.keys(local||{}).forEach(function(k){out[k]=local[k]});Object.keys(cloud||{}).forEach(function(k){var cv=cloud[k],lv=out[k];try{var ca=JSON.parse(cv),la=lv?JSON.parse(lv):null;if(Array.isArray(ca)||Array.isArray(la)){out[k]=JSON.stringify(mergeArrays(la,ca));continue}if(k==='tqb_settings_v6'&&ca&&typeof ca==='object'){var merged=Object.assign({},la||{},ca);out[k]=JSON.stringify(merged);continue}}catch(e){}if(lv==null)out[k]=cv});return out}
function writeData(data){Object.keys(data||{}).forEach(function(k){if(k&&k.indexOf('tqb_')===0&&k!==OWNER_KEY){try{localStorage.setItem(k,String(data[k]))}catch(e){}}})}
function writeCloudToLocal(d){writeData(d&&d.data&&typeof d.data==='object'?d.data:{});if(d&&d.quotes)localStorage.setItem('tqb_quotes_v6',JSON.stringify(d.quotes));if(d&&d.settings)localStorage.setItem('tqb_settings_v6',JSON.stringify(d.settings));last=snapshot();lastCloudUpdated=d.updated_at||''}
function getCloud(){return rpc({p_owner_key:owner(),p_action:'get'})}
function put(silent){if(busy)return Promise.resolve();busy=true;var k=owner(),d=allData();return activePro().then(function(){return rpc({p_owner_key:k,p_action:'put',p_quotes:read('tqb_quotes_v6',[]),p_settings:read('tqb_settings_v6',{}),p_data:d})}).then(function(r){last=snapshot();lastCloudUpdated=r.updated_at||new Date().toISOString();if(!silent)setMsg('✓ All DustyBoots data is synced.',true)}).catch(function(e){if(!silent)setMsg(e.message||'Cloud sync failed.',false);throw e}).finally(function(){busy=false})}
function bootstrap(){if(busy)return Promise.resolve();busy=true;return activePro().then(getCloud).then(function(d){if(!d||!d.found){busy=false;return put(true)}var local=allData(),cloud=d.data&&typeof d.data==='object'?d.data:{},merged=mergeData(local,cloud);writeData(merged);if(d.quotes)localStorage.setItem('tqb_quotes_v6',JSON.stringify(mergeArrays(read('tqb_quotes_v6',[]),d.quotes)));if(d.settings)localStorage.setItem('tqb_settings_v6',JSON.stringify(Object.assign({},read('tqb_settings_v6',{}),d.settings)));last=snapshot();lastCloudUpdated=d.updated_at||'';busy=false;return put(true)}).catch(function(e){busy=false;throw e})}
function pull(silent){if(busy)return Promise.resolve();busy=true;return activePro().then(getCloud).then(function(d){if(!d||!d.found){busy=false;return put(silent)}var cloudTime=d.updated_at||'';if(cloudTime&&(!lastCloudUpdated||new Date(cloudTime)>new Date(lastCloudUpdated))){writeCloudToLocal(d);if(!silent){setMsg('✓ Latest DustyBoots data loaded from cloud.',true);setTimeout(function(){location.reload()},350)}}else if(!silent){setMsg('✓ DustyBoots is up to date.',true)}}).catch(function(e){if(!silent)setMsg(e.message||'Cloud sync failed.',false);throw e}).finally(function(){busy=false})}
function syncNow(){var now=snapshot();if(now!==last)return put(false);return pull(false)}
function restore(){setMsg('Refreshing your DustyBoots data…',true);pull(false)}
function style(){if(document.getElementById('dbCloudV2Style'))return;var s=document.createElement('style');s.id='dbCloudV2Style';s.textContent='.db-cloud-v2{margin:24px 0;padding:20px;border:1px solid #e1e5ea;border-radius:14px;background:#fff}.db-cloud-v2 h3{margin:0 0 7px}.db-cloud-v2 p{font-size:13px;color:#69717c;line-height:1.45}.db-cloud-v2-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:13px}.db-cloud-v2 button{border:0;border-radius:9px;padding:11px 15px;font-weight:800;cursor:pointer}.db-cloud-v2 .primary{background:#171717;color:#fff}.db-cloud-v2 .secondary{background:#f1f3f5;color:#171717}';document.head.appendChild(s)}
function build(){if(document.getElementById('db-cloud-v2'))return;var form=document.getElementById('settingsForm');if(!form)return;var card=document.createElement('section');card.id='db-cloud-v2';card.className='db-cloud-v2';card.innerHTML='<h3>☁️ DustyBoots Cloud Sync</h3><p>One DustyBoots business across your devices. Pro members can sync quotes, invoices, customers, items, payments and settings automatically.</p><div class="db-cloud-v2-actions"><button type="button" class="primary" id="dbCloudV2Sync">Sync now</button><button type="button" class="secondary" id="dbCloudV2Restore">Refresh from cloud</button></div><div id="dbCloudV2Msg" style="margin-top:10px;font-size:13px;font-weight:700">Cloud sync is a Pro feature.</div>';form.appendChild(card);document.getElementById('dbCloudV2Sync').onclick=syncNow;document.getElementById('dbCloudV2Restore').onclick=function(){if(confirm('Refresh this device from the latest cloud copy?'))restore()};last=snapshot();if(timer)clearInterval(timer);timer=setInterval(function(){if(document.visibilityState==='hidden'||busy)return;var now=snapshot();if(now!==last){put(true).catch(function(){})}else{pull(true).catch(function(){})}},15000)}
function init(){style();build();if(owner())bootstrap().catch(function(){})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();setTimeout(init,500);setTimeout(init,1500)
})();
