(function(){
'use strict';
var EMAILJS_SERVICE_ID='service_wmpq4cq';
var EMAILJS_CUSTOMER_TEMPLATE_ID='template_9kx2gib';
var EMAILJS_PUBLIC_KEY='dyBjG4ATAJjl1LYSQ';
var RESPONSE_BASE='https://bushtrophyroom.github.io/Tradie-Quote-Buddy/respond-v2.html?data=';
var SUPABASE_FUNCTION_URL='https://cychngcvhgtfuahavlqq.supabase.co/functions/v1/create-quote-pdf';
var JS_PDF_URL='https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js';
var AUTO_TABLE_URL='https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.8.4/jspdf.plugin.autotable.min.js';
function $(id){return document.getElementById(id)}
function enc(data){var json=JSON.stringify(data),b=btoa(unescape(encodeURIComponent(json)));return b.replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function money(v){return new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(Number(v)||0)}
function settings(){try{return JSON.parse(localStorage.getItem('tqb_settings_v6')||'{}')}catch(e){return {}}}
function getQuotes(){try{var q=JSON.parse(localStorage.getItem('tqb_quotes_v6')||'[]');return Array.isArray(q)?q:[]}catch(e){return[]}}
function saveQuotes(q){try{localStorage.setItem('tqb_quotes_v6',JSON.stringify(q))}catch(e){}}
function getCurrentQuote(){if(window.currentQuote)return window.currentQuote;var preview=$('quotePreview');if(!preview)return null;var n=preview.querySelector('.paper-meta b');var num=n?(n.textContent||'').trim():'';return getQuotes().find(function(q){return String(q.number||'')===num})||null}
function makeToken(){return (window.crypto&&crypto.randomUUID)?crypto.randomUUID():(Date.now()+'-'+Math.random().toString(36).slice(2))}
function buildPayload(q,token){
  var s=settings(),items=Array.isArray(q.items)?q.items:[],lines=[];
  items.forEach(function(item){item=item||{};var qty=item.qty==null?1:Number(item.qty)||0,unit=item.unitPrice==null?Number(item.amount)||0:Number(item.unitPrice)||0,amount=qty*unit;if(item.description||amount||qty)lines.push(String(item.description||'')+' | Qty: '+qty+' | Unit: '+money(unit)+' | Amount: '+money(amount))});
  var labour=Number(q.labourHours)>0?'Labour | Hours: '+Number(q.labourHours)+' | Rate: '+money(q.hourlyRate)+'/hr | Amount: '+money(q.labour):'';
  return {quote_number:String(q.number||''),business_name:String(s.businessName||'Tradie Quote Buddy'),business_email:String(s.businessEmail||''),business_phone:String(s.businessPhone||''),business_address:String(s.businessAddress||''),customer_name:String(q.customerName||''),customer_phone:String(q.customerPhone||''),customer_email:String(q.customerEmail||''),customer_address:String(q.customerAddress||''),job_description:String(q.jobDescription||''),item_details:lines.join('\n')||'No materials or other charges',materials_details:lines.join('\n')||'No materials or other charges',labour_details:labour||'No labour added',subtotal:money(q.subtotal),discount:Number(q.discount)>0?'-'+money(q.discount):'None',gst:money(q.gst),total:money(q.total),quote_total:money(q.total),response_token:token,quote_status:String(q.status||'Pending')};
}
function responseUrl(payload,decision){var d={};Object.keys(payload).forEach(function(k){d[k]=payload[k]});d.decision=decision;d.quote_status=decision;d.responded_at=new Date().toLocaleString('en-AU');return RESPONSE_BASE+enc(d)}
function loadScript(src){return new Promise(function(resolve,reject){var existing=document.querySelector('script[src="'+src+'"]');if(existing){if(src.indexOf('jspdf.umd')!==-1&&window.jspdf)return resolve();if(src.indexOf('autotable')!==-1&&window.jspdf&&window.jspdf.jsPDF&&window.jspdf.jsPDF.API&&window.jspdf.jsPDF.API.autoTable)return resolve();existing.addEventListener('load',resolve,{once:true});existing.addEventListener('error',reject,{once:true});return}var s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.head.appendChild(s)})}
function ensurePdfLibraries(){var p=Promise.resolve();if(!window.jspdf||!window.jspdf.jsPDF)p=p.then(function(){return loadScript(JS_PDF_URL)});return p.then(function(){if(window.jspdf&&window.jspdf.jsPDF&&window.jspdf.jsPDF.API&&window.jspdf.jsPDF.API.autoTable)return;return loadScript(AUTO_TABLE_URL)})}
function parseItemLine(line){var parts=line.split('|').map(function(x){return x.trim()});if(parts.length>=4){return [parts[0].replace(/^Description\s*:\s*/i,''),(parts[1].match(/Qty\s*:\s*(.*)/i)||[])[1]||'',(parts[2].match(/Unit\s*:\s*(.*)/i)||[])[1]||'',(parts[3].match(/Amount\s*:\s*(.*)/i)||[])[1]||'']}return [line,'','','']}
function parseLabourLine(line){var parts=line.split('|').map(function(x){return x.trim()}),hours='',rate='',amount='';parts.forEach(function(p){var m=p.match(/^Hours\s*:\s*(.*)$/i);if(m)hours=m[1].trim();m=p.match(/^Rate\s*:\s*(.*)$/i);if(m)rate=m[1].trim();m=p.match(/^Amount\s*:\s*(.*)$/i);if(m)amount=m[1].trim()});return ['Labour',hours?hours+' hrs':'',rate,amount]}
function makePdf(d,acceptUrl,declineUrl){
  if(!window.jspdf||!window.jspdf.jsPDF)throw new Error('PDF library unavailable');
  var doc=new window.jspdf.jsPDF({unit:'mm',format:'a4',orientation:'portrait'}),margin=16,pageW=210,pageH=297,contentW=pageW-margin*2,y=margin;
  function clean(v){return String(v==null?'':v).replace(/\r/g,'').trim()}
  function ensure(h){if(y+h>pageH-margin){doc.addPage();y=margin}}
  function wrapped(text,x,maxW,size,bold){doc.setFont('helvetica',bold?'bold':'normal');doc.setFontSize(size||10);var lines=doc.splitTextToSize(clean(text),maxW);doc.text(lines,x,y);y+=lines.length*((size||10)*0.42)+2}
  doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('TRADIE QUOTE BUDDY',margin,y);y+=7;doc.setFontSize(19);doc.text(clean(d.business_name||'Tradie Quote Buddy'),margin,y);
  doc.setFont('helvetica','normal');doc.setFontSize(9);y+=6;var business=[d.business_address,d.business_phone,d.business_email].map(clean).filter(Boolean).join('\n');if(business)doc.text(doc.splitTextToSize(business,105),margin,y);
  var rightX=pageW-margin-55;doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('QUOTE',rightX,y-6);doc.setFontSize(17);doc.text(clean(d.quote_number),rightX,y+1);doc.setFontSize(9);doc.setFont('helvetica','normal');doc.text('Pending',rightX,y+8);
  y+=22;doc.setLineWidth(.5);doc.line(margin,y,pageW-margin,y);y+=8;
  ensure(24);wrapped('CUSTOMER',margin,contentW,9,true);wrapped(clean(d.customer_name),margin,contentW,11,true);var cust=[d.customer_phone,d.customer_email,d.customer_address].map(clean).filter(Boolean).join('\n');if(cust)wrapped(cust,margin,contentW,9,false);y+=3;
  ensure(22);wrapped('JOB DESCRIPTION',margin,contentW,9,true);wrapped(d.job_description||'No job description supplied.',margin,contentW,10,false);y+=3;
  ensure(45);wrapped('MATERIALS & OTHER COSTS',margin,contentW,9,true);var raw=String(d.materials_details||d.item_details||'').split(/\n+/).map(function(x){return x.trim()}).filter(Boolean),rows=[];raw.forEach(function(line){rows.push(parseItemLine(line))});if(d.labour_details)rows.push(parseLabourLine(d.labour_details));if(!rows.length)rows=[['No item breakdown supplied.','','','']];
  if(doc.autoTable){doc.autoTable({startY:y,margin:{left:margin,right:margin},head:[['Description','Qty','Unit','Amount']],body:rows,theme:'grid',styles:{font:'helvetica',fontSize:8,cellPadding:2.5,textColor:[23,23,23]},headStyles:{fontStyle:'bold',fillColor:[35,35,35],textColor:[255,255,255]},columnStyles:{0:{cellWidth:92},1:{cellWidth:24,halign:'right'},2:{cellWidth:30,halign:'right'},3:{cellWidth:32,halign:'right'}}});y=doc.lastAutoTable.finalY+8;}
  ensure(40);var totalsX=pageW-margin-70;doc.setFontSize(9);function totalRow(label,val,bold){doc.setFont('helvetica',bold?'bold':'normal');doc.text(label,totalsX,y);doc.text(clean(val),pageW-margin,y,{align:'right'});y+=6}totalRow('Subtotal',d.subtotal,false);if(clean(d.discount)&&clean(d.discount)!=='$0.00'&&clean(d.discount)!=='0'&&clean(d.discount)!=='None')totalRow('Discount',d.discount,false);totalRow('GST',d.gst,false);doc.setLineWidth(.6);doc.line(totalsX,y-2,pageW-margin,y-2);y+=3;doc.setFontSize(12);totalRow('TOTAL',d.total||d.quote_total,true);
  ensure(42);y+=7;doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text('CUSTOMER RESPONSE',margin,y);y+=7;doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text('Choose one option below to send your decision to the business.',margin,y);y+=10;
  function button(label,x,w,fill,url){doc.setFillColor(fill[0],fill[1],fill[2]);doc.roundedRect(x,y-7,w,12,2,2,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text(label,x+w/2,y+1,{align:'center'});doc.link(x,y-7,w,12,{url:url});doc.setTextColor(23,23,23)}
  button('ACCEPT QUOTE',margin,78,[22,128,60],acceptUrl);button('DECLINE QUOTE',pageW-margin-78,78,[229,57,53],declineUrl);y+=20;doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(100,100,100);doc.text('No payment is taken when you respond to this quote.',margin,y);doc.setTextColor(23,23,23);
  return doc.output('datauristring');
}
function createSecurePdf(payload){var acceptUrl=responseUrl(payload,'Accepted'),declineUrl=responseUrl(payload,'Declined');return ensurePdfLibraries().then(function(){var pdfDataUri=makePdf(payload,acceptUrl,declineUrl);return fetch(SUPABASE_FUNCTION_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pdfDataUri:pdfDataUri,quoteNumber:payload.quote_number,responseToken:payload.response_token})}).then(function(r){return r.json().then(function(x){if(!r.ok||!x.pdfUrl)throw new Error(x.error||'Could not create secure PDF link');return x.pdfUrl})})})}
function addButton(){var actions=$('editQuoteBtn')&&$('editQuoteBtn').parentElement;if(!actions||$('sendCustomerBtn'))return;var b=document.createElement('button');b.type='button';b.className='primary';b.id='sendCustomerBtn';b.textContent='📧 Send Quote to Customer';actions.appendChild(b);b.addEventListener('click',send)}
function statusButton(text){var b=$('sendCustomerBtn');if(b){b.disabled=true;b.textContent=text}}
function send(){
  var q=getCurrentQuote();if(!q){alert('Please open a saved quote first.');return}if(!q.customerEmail){alert('This quote needs the customer email address before it can be sent.');return}if(!window.emailjs){alert('Email service is still loading. Please try again.');return}
  var token=q.responseToken||makeToken();q.responseToken=token;q.status='Pending';q.quoteStatus='Pending';var qs=getQuotes();for(var i=0;i<qs.length;i++){if(String(qs[i].id)===String(q.id)){qs[i]=q;break}}saveQuotes(qs);window.currentQuote=q;
  var d=buildPayload(q,token);statusButton('⏳ Preparing PDF…');
  createSecurePdf(d).then(function(pdfUrl){statusButton('⏳ Sending email…');var params={quote_number:d.quote_number,business_name:d.business_name,business_email:d.business_email,business_phone:d.business_phone,customer_name:d.customer_name,customer_phone:d.customer_phone,customer_email:d.customer_email,customer_address:d.customer_address,job_description:d.job_description,item_details:d.item_details,materials_details:d.materials_details,labour_details:d.labour_details,subtotal:d.subtotal,discount:d.discount,gst:d.gst,quote_total:d.quote_total,total:d.total,quote_status:'Pending',response_link:responseUrl(d,'Accepted'),quote_pdf:pdfUrl,quote_pdf_file:pdfUrl};return emailjs.send(EMAILJS_SERVICE_ID,EMAILJS_CUSTOMER_TEMPLATE_ID,params)}).then(function(){statusButton('✓ Quote Sent');setTimeout(function(){var b=$('sendCustomerBtn');if(b){b.disabled=false;b.textContent='📧 Send Quote to Customer'}},2500);alert('Quote '+q.number+' was emailed to '+q.customerEmail+'. The customer can Accept or Decline from the quote PDF.')}).catch(function(err){console.error(err);statusButton('⚠️ Send failed');setTimeout(function(){var b=$('sendCustomerBtn');if(b){b.disabled=false;b.textContent='📧 Send Quote to Customer'}},2500);alert('We could not send the quote. '+(err&&err.message?err.message:'Please check your EmailJS customer template and try again.'))})
}
function start(){if(!window.emailjs)return;emailjs.init({publicKey:EMAILJS_PUBLIC_KEY});addButton();var p=$('quotePreview');if(p){new MutationObserver(function(){addButton()}).observe(p,{childList:true,subtree:true})}document.addEventListener('click',function(e){if(e.target.closest&&e.target.closest('#sendCustomerBtn'))return;setTimeout(addButton,100)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
