(function(){
'use strict';
var SERVICE='service_wmpq4cq',TEMPLATE='template_9kx2gib',PUBLIC_KEY='dyBjG4ATAJjl1LYSQ';
var RESPONSE_BASE='https://bushtrophyroom.github.io/Tradie-Quote-Buddy/respond-v2.html?data=';
var SUPABASE_FUNCTION_URL='https://cychngcvhgtfuahavlqq.supabase.co/functions/v1/create-quote-pdf';
var PDF_URL='https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js',TABLE_URL='https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.8.4/jspdf.plugin.autotable.min.js';
function $(id){return document.getElementById(id)}
function money(v){return new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(Number(v)||0)}
function enc(o){var s=JSON.stringify(o),b=btoa(unescape(encodeURIComponent(s)));return b.replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function settings(){try{return JSON.parse(localStorage.getItem('tqb_settings_v6')||'{}')}catch(e){return{}}}
function quotes(){try{var q=JSON.parse(localStorage.getItem('tqb_quotes_v6')||'[]');return Array.isArray(q)?q:[]}catch(e){return[]}}
function saveQuotes(q){localStorage.setItem('tqb_quotes_v6',JSON.stringify(q))}
function currentQuote(){if(window.currentQuote)return window.currentQuote;var p=$('quotePreview');if(!p)return null;var n=p.querySelector('.paper-meta b'),num=n?(n.textContent||'').trim():'';return quotes().find(function(q){return String(q.number||'')===num})||null}
function token(){return window.crypto&&crypto.randomUUID?crypto.randomUUID():Date.now()+'-'+Math.random().toString(36).slice(2)}
function payload(q,t){var s=settings(),lines=[];(q.items||[]).forEach(function(x){x=x||{};var qty=x.qty==null?1:Number(x.qty)||0,unit=x.unitPrice==null?Number(x.amount)||0:Number(x.unitPrice)||0;if(x.description||qty)lines.push(String(x.description||'')+' | Qty: '+qty+' | Unit: '+money(unit)+' | Amount: '+money(qty*unit))});var labour=Number(q.labourHours)>0?'Labour | Hours: '+Number(q.labourHours)+' | Rate: '+money(q.hourlyRate)+'/hr | Amount: '+money(q.labour):'';return{quote_number:String(q.number||''),business_name:String(s.businessName||'Tradie Quote Buddy'),business_email:String(s.businessEmail||''),business_phone:String(s.businessPhone||''),business_address:String(s.businessAddress||''),customer_name:String(q.customerName||''),customer_phone:String(q.customerPhone||''),customer_email:String(q.customerEmail||''),customer_address:String(q.customerAddress||''),job_description:String(q.jobDescription||''),item_details:lines.join('\n')||'No materials or other charges',materials_details:lines.join('\n')||'No materials or other charges',labour_details:labour||'No labour added',subtotal:money(q.subtotal),discount:Number(q.discount)>0?'-'+money(q.discount):'None',gst:money(q.gst),total:money(q.total),quote_total:money(q.total),response_token:t,quote_status:'Pending'}}
function responseUrl(d,decision){var x={};Object.keys(d).forEach(function(k){x[k]=d[k]});x.decision=decision;x.quote_status=decision;x.responded_at=new Date().toLocaleString('en-AU');return RESPONSE_BASE+enc(x)}
function load(src){return new Promise(function(ok,no){var old=document.querySelector('script[src="'+src+'"]');if(old){if(src.indexOf('jspdf.')>=0&&window.jspdf)return ok();if(src.indexOf('autotable')>=0&&window.jspdf&&window.jspdf.jsPDF&&window.jspdf.jsPDF.API.autoTable)return ok();old.addEventListener('load',ok,{once:true});old.addEventListener('error',no,{once:true});return}var s=document.createElement('script');s.src=src;s.onload=ok;s.onerror=no;document.head.appendChild(s)})}
function pdfLibs(){return load(PDF_URL).then(function(){return load(TABLE_URL)})}
function lines(v){return String(v||'').split(/\n+/).map(function(x){return x.trim()}).filter(Boolean)}
function itemLine(v){var p=v.split('|').map(function(x){return x.trim()});return[p[0]||'',(p[1]||'').replace(/^Qty:\s*/i,''),(p[2]||'').replace(/^Unit:\s*/i,''),(p[3]||'').replace(/^Amount:\s*/i,'')]}
function labourLine(v){var h='',r='',a='';v.split('|').forEach(function(p){p=p.trim();var m=p.match(/^Hours:\s*(.*)/i);if(m)h=m[1];m=p.match(/^Rate:\s*(.*)/i);if(m)r=m[1];m=p.match(/^Amount:\s*(.*)/i);if(m)a=m[1]});return['Labour',h?h+' hrs':'',r,a]}
function makePdf(d,accept,decline){var doc=new window.jspdf.jsPDF({unit:'mm',format:'a4'}),M=16,W=210,H=297,y=M,C=W-M*2;function clean(v){return String(v==null?'':v).replace(/\r/g,'').trim()}function wrap(t,x,w,size,b){doc.setFont('helvetica',b?'bold':'normal');doc.setFontSize(size||10);var a=doc.splitTextToSize(clean(t),w);doc.text(a,x,y);y+=a.length*((size||10)*.42)+2}function ensure(h){if(y+h>H-M){doc.addPage();y=M}}
doc.setFont('helvetica','bold');doc.setFontSize(9);doc.text('TRADIE QUOTE BUDDY',M,y);y+=7;doc.setFontSize(19);doc.text(clean(d.business_name),M,y);y+=6;doc.setFont('helvetica','normal');doc.setFontSize(9);var biz=[d.business_address,d.business_phone,d.business_email].map(clean).filter(Boolean).join('\n');if(biz)doc.text(doc.splitTextToSize(biz,105),M,y);var rx=W-M-55;doc.setFont('helvetica','bold');doc.text('QUOTE',rx,y-6);doc.setFontSize(17);doc.text(clean(d.quote_number),rx,y+1);doc.setFontSize(9);doc.setFont('helvetica','normal');doc.text('Pending',rx,y+8);y+=22;doc.line(M,y,W-M,y);y+=8;
wrap('CUSTOMER',M,C,9,true);wrap(d.customer_name,M,C,11,true);var cust=[d.customer_phone,d.customer_email,d.customer_address].map(clean).filter(Boolean).join('\n');if(cust)wrap(cust,M,C,9,false);y+=3;wrap('JOB DESCRIPTION',M,C,9,true);wrap(d.job_description||'No job description supplied.',M,C,10,false);y+=3;ensure(45);wrap('MATERIALS & OTHER COSTS',M,C,9,true);var rows=lines(d.materials_details||d.item_details).map(itemLine);if(d.labour_details)rows.push(labourLine(d.labour_details));if(!rows.length)rows=[['No item breakdown supplied.','','','']];doc.autoTable({startY:y,margin:{left:M,right:M},head:[['Description','Qty','Unit','Amount']],body:rows,theme:'grid',styles:{font:'helvetica',fontSize:8,cellPadding:2.5},headStyles:{fontStyle:'bold',fillColor:[35,35,35],textColor:[255,255,255]},columnStyles:{0:{cellWidth:92},1:{cellWidth:24,halign:'right'},2:{cellWidth:30,halign:'right'},3:{cellWidth:32,halign:'right'}}});y=doc.lastAutoTable.finalY+8;
ensure(42);var tx=W-M-70;doc.setFontSize(9);function tr(l,v,b){doc.setFont('helvetica',b?'bold':'normal');doc.text(l,tx,y);doc.text(clean(v),W-M,y,{align:'right'});y+=6}tr('Subtotal',d.subtotal,false);if(d.discount&&d.discount!=='None'&&d.discount!=='$0.00')tr('Discount',d.discount,false);tr('GST',d.gst,false);doc.line(tx,y-2,W-M,y-2);y+=3;doc.setFontSize(12);tr('TOTAL',d.total,true);
ensure(42);y+=8;doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text('CUSTOMER RESPONSE',M,y);y+=7;doc.setFont('helvetica','normal');doc.setFontSize(9);doc.text('Choose one option below to send your decision to the business.',M,y);y+=10;function btn(label,x,url,fill){doc.setFillColor(fill[0],fill[1],fill[2]);doc.roundedRect(x,y-7,78,12,2,2,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(10);doc.text(label,x+39,y+1,{align:'center'});doc.link(x,y-7,78,12,{url:url});doc.setTextColor(23,23,23)}btn('ACCEPT QUOTE',M,accept,[22,128,60]);btn('DECLINE QUOTE',W-M-78,decline,[229,57,53]);y+=20;doc.setFont('helvetica','normal');doc.setFontSize(8);doc.setTextColor(100,100,100);doc.text('No payment is taken when you respond to this quote.',M,y);return doc.output('datauristring')}
function addButton(){var a=$('editQuoteBtn')&&$('editQuoteBtn').parentElement;if(!a||$('sendCustomerBtn'))return;var b=document.createElement('button');b.type='button';b.className='primary';b.id='sendCustomerBtn';b.textContent='📧 Send Quote to Customer';a.appendChild(b);b.onclick=send}
function state(t){var b=$('sendCustomerBtn');if(b){b.disabled=true;b.textContent=t}}
function send(){var q=currentQuote();if(!q)return alert('Please open a saved quote first.');if(!q.customerEmail)return alert('This quote needs the customer email address before it can be sent.');if(!window.emailjs)return alert('Email service is still loading. Please try again.');var t=q.responseToken||token();q.responseToken=t;q.status='Pending';q.quoteStatus='Pending';var qs=quotes();for(var i=0;i<qs.length;i++)if(String(qs[i].id)===String(q.id))qs[i]=q;saveQuotes(qs);window.currentQuote=q;var d=payload(q,t),accept=responseUrl(d,'Accepted'),decline=responseUrl(d,'Declined');state('⏳ Creating PDF…');pdfLibs().then(function(){var pdf=makePdf(d,accept,decline);state('⏳ Storing PDF…');return fetch(SUPABASE_FUNCTION_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pdfDataUri:pdf,quoteNumber:d.quote_number,responseToken:d.response_token,decision:'Pending',customerName:d.customer_name})}).then(function(r){return r.json().then(function(x){if(!r.ok||!x.pdfUrl)throw new Error(x.error||'Could not create secure PDF link');return x.pdfUrl})}).then(function(pdfUrl){state('⏳ Sending email…');return emailjs.send(SERVICE,TEMPLATE,{quote_number:d.quote_number,business_name:d.business_name,business_email:d.business_email,business_phone:d.business_phone,customer_name:d.customer_name,customer_phone:d.customer_phone,customer_email:d.customer_email,customer_address:d.customer_address,job_description:d.job_description,item_details:d.item_details,materials_details:d.materials_details,labour_details:d.labour_details,subtotal:d.subtotal,discount:d.discount,gst:d.gst,total:d.total,quote_total:d.total,quote_status:'Pending',response_link:accept,accept_link:accept,decline_link:decline,quote_pdf:pdfUrl})})}).then(function(){state('✓ Quote Sent');setTimeout(addButton,2500);alert('Quote '+q.number+' was emailed to '+q.customerEmail+'. The email contains a secure PDF link, and the PDF has Accept and Decline buttons.')}).catch(function(e){console.error(e);state('⚠️ Send failed');setTimeout(addButton,2500);alert('We could not send the quote. '+(e&&e.message?e.message:'Please try again.'))})}
function start(){if(!window.emailjs)return;emailjs.init({publicKey:PUBLIC_KEY});addButton();var p=$('quotePreview');if(p)new MutationObserver(addButton).observe(p,{childList:true,subtree:true});document.addEventListener('click',function(e){if(!(e.target.closest&&e.target.closest('#sendCustomerBtn')))setTimeout(addButton,100)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
