(function(){
'use strict';
var EMAILJS_SERVICE_ID='service_wmpq4cq';
var EMAILJS_CUSTOMER_TEMPLATE_ID='REPLACE_CUSTOMER_TEMPLATE_ID';
var EMAILJS_PUBLIC_KEY='dyBjG4ATAJjl1LYSQ';
var RESPONSE_BASE='./respond-v2.html?data=';
function $(id){return document.getElementById(id)}
function enc(data){var json=JSON.stringify(data),b=btoa(unescape(encodeURIComponent(json)));return b.replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function money(v){return new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(Number(v)||0)}
function settings(){try{return JSON.parse(localStorage.getItem('tqb_settings_v6')||'{}')}catch(e){return {}}}
function getCurrentQuote(){if(window.currentQuote)return window.currentQuote;var preview=$('quotePreview');if(!preview)return null;var n=preview.querySelector('.paper-meta b');var num=n?(n.textContent||'').trim():'';try{var list=JSON.parse(localStorage.getItem('tqb_quotes_v6')||'[]');return list.find(function(q){return String(q.number||'')===num})||null}catch(e){return null}}
function buildData(q){var s=settings(),token=(window.crypto&&crypto.randomUUID)?crypto.randomUUID():(Date.now()+'-'+Math.random().toString(36).slice(2));var items=Array.isArray(q.items)?q.items:[],lines=[];items.forEach(function(item){var qty=item.qty==null?1:Number(item.qty)||0,unit=item.unitPrice==null?Number(item.amount)||0:Number(item.unitPrice)||0,amount=qty*unit;if(item.description||amount||qty)lines.push(String(item.description||'')+' | Qty: '+qty+' | Unit: '+money(unit)+' | Amount: '+money(amount))});var labour=Number(q.labourHours)>0?'Labour | Hours: '+Number(q.labourHours)+' | Rate: '+money(q.hourlyRate)+'/hr | Amount: '+money(q.labour):'';return {quote_number:String(q.number||''),business_name:String(s.businessName||'Tradie Quote Buddy'),business_email:String(s.businessEmail||''),business_phone:String(s.businessPhone||''),business_address:String(s.businessAddress||''),customer_name:String(q.customerName||''),customer_phone:String(q.customerPhone||''),customer_email:String(q.customerEmail||''),customer_address:String(q.customerAddress||''),job_description:String(q.jobDescription||''),item_details:lines.join('\n')||'No materials or other charges',materials_details:lines.join('\n')||'No materials or other charges',labour_details:labour||'No labour added',subtotal:money(q.subtotal),discount:Number(q.discount)>0?'-'+money(q.discount):'None',gst:money(q.gst),quote_total:money(q.total),response_link:RESPONSE_BASE+enc({quote_number:q.number,business_name:s.businessName,business_email:s.businessEmail,business_phone:s.businessPhone,business_address:s.businessAddress,customer_name:q.customerName,customer_phone:q.customerPhone,customer_email:q.customerEmail,customer_address:q.customerAddress,job_description:q.jobDescription,item_details:lines.join('\n'),materials_details:lines.join('\n'),labour_details:labour,subtotal:money(q.subtotal),discount:Number(q.discount)>0?'-'+money(q.discount):'',gst:money(q.gst),total:money(q.total),quote_total:money(q.total),response_token:token,quote_status:'Pending'} )};}
function addButton(){var actions=$('editQuoteBtn')&&$('editQuoteBtn').parentElement;if(!actions||$('sendCustomerBtn'))return;var b=document.createElement('button');b.type='button';b.className='primary';b.id='sendCustomerBtn';b.textContent='📧 Send Quote to Customer';actions.appendChild(b);b.addEventListener('click',send)}
function statusButton(text){var b=$('sendCustomerBtn');if(b){b.disabled=true;b.textContent=text}}
function send(){var q=getCurrentQuote();if(!q){alert('Please open a saved quote first.');return}if(!q.customerEmail){alert('This quote needs the customer email address before it can be sent.');return}if(EMAILJS_CUSTOMER_TEMPLATE_ID==='REPLACE_CUSTOMER_TEMPLATE_ID'){alert('Customer email template is not connected yet. Create the new EmailJS customer template, then add its Template ID to customer-send.js.');return}if(!window.emailjs){alert('Email service is still loading. Please try again.');return}var d=buildData(q),s=settings();statusButton('⏳ Sending…');emailjs.send(EMAILJS_SERVICE_ID,EMAILJS_CUSTOMER_TEMPLATE_ID,d).then(function(){statusButton('✓ Quote Sent');setTimeout(function(){var b=$('sendCustomerBtn');if(b){b.disabled=false;b.textContent='📧 Send Quote to Customer'}},2500);alert('Quote '+q.number+' was emailed to '+q.customerEmail+'.')}).catch(function(err){console.error(err);statusButton('⚠️ Send failed');setTimeout(function(){var b=$('sendCustomerBtn');if(b){b.disabled=false;b.textContent='📧 Send Quote to Customer'}},2500);alert('We could not send the quote. Please check the EmailJS customer template and try again.')})}
function start(){if(!window.emailjs)return;emailjs.init({publicKey:EMAILJS_PUBLIC_KEY});addButton();var p=$('quotePreview');if(p){new MutationObserver(function(){addButton()}).observe(p,{childList:true,subtree:true})}document.addEventListener('click',function(e){if(e.target.closest&&e.target.closest('#sendCustomerBtn'))return;setTimeout(addButton,100)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
