(function(){
'use strict';
var CUSTOMERS_KEY='tqb_customers_v1',INVOICES_KEY='tqb_invoices_v1',QUOTES_KEY='tqb_quotes_v6',DELETED_KEY='tqb_deleted_customers_v1';
function read(key){try{var x=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function save(key,x){try{localStorage.setItem(key,JSON.stringify(x))}catch(e){}}
function readCustomers(){return read(CUSTOMERS_KEY)}
function readInvoices(){return read(INVOICES_KEY)}
function readQuotes(){return read(QUOTES_KEY)}
function norm(v){return String(v||'').trim().toLowerCase().replace(/\s+/g,' ')}
function phoneKey(v){var d=String(v||'').replace(/\D/g,'');if(d.indexOf('61')===0&&d.length===11)d='0'+d.slice(2);return d}
function key(c){var e=norm(c.email),p=phoneKey(c.phone),n=norm(c.name);if(p&&e)return e+'|'+p;if(p)return p;if(e)return e+'|'+n;return n}
function deleted(){return read(DELETED_KEY)}
function clearRecreated(){var d=deleted();if(!d.length)return;var records=readQuotes().concat(readInvoices()),changed=false;d=d.filter(function(x){var recreated=records.some(function(r){var created=Number(r.createdAt||0);return key({name:r.name||r.customerName,email:r.email||r.customerEmail,phone:r.phone||r.customerPhone})===x.key&&created>Number(x.deletedAt||0)});if(recreated){changed=true;return false}return true});if(changed)save(DELETED_KEY,d)}
function rememberDeleted(c){var list=deleted(),k=key(c),now=Date.now(),found=false;list=list.map(function(x){if(x.key===k){found=true;return{x:key(c),deletedAt:now,name:c.name||'',email:c.email||'',phone:c.phone||''}}return x});if(!found)list.push({key:k,deletedAt:now,name:c.name||'',email:c.email||'',phone:c.phone||''});save(DELETED_KEY,list)}
function isDeleted(c){return deleted().some(function(x){return x.key===key(c)})}
function findCustomer(){var detail=document.getElementById('customerDetail');if(!detail)return null;var h=detail.querySelector('h3');if(!h)return null;var name=(h.textContent||'').trim(),nodes=detail.querySelectorAll('.customer-detail-head div div'),email='',phone='';for(var i=0;i<nodes.length;i++){var t=(nodes[i].textContent||'').trim();if(t.indexOf('@')>=0)email=t;else if(/\d/.test(t)&&t.length<=20)phone=t}var list=readCustomers(),c=list.find(function(x){return key(x)===key({name:name,email:email,phone:phone})});if(!c)c=list.find(function(x){return norm(x.name)===norm(name)});return c||{id:'detail',name:name,email:email,phone:phone,address:''}}
function hideDeletedCards(){clearRecreated();var list=document.querySelectorAll('.customer-card');for(var i=0;i<list.length;i++){var card=list[i],name='',phone='',email='';var b=card.querySelector('.row b'),small=card.querySelector('small');if(b)name=(b.textContent||'').trim();if(small){var t=(small.textContent||'').trim();if(t.indexOf('@')>=0)email=t;else phone=t}if(isDeleted({name:name,email:email,phone:phone})){card.remove()}}}
function inject(){var detail=document.getElementById('customerDetail');if(!detail)return;var head=detail.querySelector('.customer-detail-head');if(!head||head.querySelector('#tqbDeleteCustomerBtn'))return;var edit=head.querySelector('#editCustomerBtn');var wrap=document.createElement('div');wrap.style.cssText='display:flex;gap:8px;flex-wrap:wrap';if(edit){edit.parentNode.insertBefore(wrap,edit);wrap.appendChild(edit)}else head.appendChild(wrap);var btn=document.createElement('button');btn.id='tqbDeleteCustomerBtn';btn.type='button';btn.className='secondary';btn.textContent='🗑 Delete';btn.style.cssText='background:#fff0f0;color:#b42318;border:1px solid #f3b6b6;white-space:nowrap';wrap.appendChild(btn);btn.onclick=function(){var c=findCustomer();if(!c)return;var linked=readInvoices().filter(function(inv){return key({name:inv.customerName,email:inv.customerEmail,phone:inv.customerPhone})===key(c)}).length;var linkedQuotes=readQuotes().filter(function(q){return key({name:q.customerName,email:q.customerEmail,phone:q.customerPhone})===key(c)}).length;var msg='Delete '+(c.name||'this customer')+' from your customer list?\n\nTheir customer profile will be removed, but existing quotes and invoices will NOT be deleted.';if(linked||linkedQuotes)msg+='\n\nLinked records: '+linkedQuotes+' quote'+(linkedQuotes===1?'':'s')+' and '+linked+' invoice'+(linked===1?'':'s')+'.';msg+='\n\nA new quote for this customer later will add them back to the customer list.';if(!window.confirm(msg))return;rememberDeleted(c);save(CUSTOMERS_KEY,readCustomers().filter(function(x){return String(x.id)!==String(c.id)}));detail.innerHTML='';hideDeletedCards();if(typeof window.dispatchEvent==='function')window.dispatchEvent(new Event('customerDeleted'))}}
function start(){inject();hideDeletedCards();setInterval(function(){inject();hideDeletedCards()},500);document.addEventListener('click',function(e){if(e.target.closest&&e.target.closest('.customer-card,[data-screen="customers"]'))setTimeout(function(){inject();hideDeletedCards()},50)});window.addEventListener('focus',function(){inject();hideDeletedCards()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
