(function(){
'use strict';
var CUSTOMERS_KEY='tqb_customers_v1',DELETED_KEY='tqb_deleted_customers_v2';
function read(key){try{var x=JSON.parse(localStorage.getItem(key)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function save(key,x){try{localStorage.setItem(key,JSON.stringify(x))}catch(e){}}
function norm(v){return String(v||'').trim().toLowerCase().replace(/\s+/g,' ')}
function phoneKey(v){var d=String(v||'').replace(/\D/g,'');if(d.indexOf('61')===0&&d.length===11)d='0'+d.slice(2);return d}
function key(c){var e=norm(c.email),p=phoneKey(c.phone),n=norm(c.name);if(p&&e)return e+'|'+p;if(p)return p;if(e)return e+'|'+n;return n}
function deleted(){return read(DELETED_KEY)}
function rememberDeleted(c){var list=deleted(),item={id:String(c.id||''),key:key(c),name:String(c.name||''),email:String(c.email||''),phone:String(c.phone||''),deletedAt:Date.now()};list=list.filter(function(x){return String(x.id||'')!==item.id&&String(x.key||'')!==item.key});list.push(item);save(DELETED_KEY,list)}
function isDeleted(c){var k=key(c),n=norm(c.name),p=phoneKey(c.phone),e=norm(c.email);return deleted().some(function(x){return (x.id&&c.id&&String(x.id)===String(c.id))||(x.key&&x.key===k)||(!x.key&&norm(x.name)===n&&phoneKey(x.phone)===p&&norm(x.email)===e)})}
function currentCustomer(){var detail=document.getElementById('customerDetail');if(!detail)return null;var h=detail.querySelector('h3');if(!h)return null;var name=(h.textContent||'').trim(),email='',phone='',nodes=detail.querySelectorAll('.customer-detail-head div div');for(var i=0;i<nodes.length;i++){var t=(nodes[i].textContent||'').trim();if(t.indexOf('@')>=0)email=t;else if(/^\+?[\d ()-]{8,20}$/.test(t))phone=t}var list=read(CUSTOMERS_KEY),c=list.find(function(x){return key(x)===key({name:name,email:email,phone:phone})});if(!c)c=list.find(function(x){return norm(x.name)===norm(name)});return c||{id:'',name:name,email:email,phone:phone}}
function removeDeletedCards(){var cards=document.querySelectorAll('.customer-card');for(var i=0;i<cards.length;i++){var card=cards[i],name='',contact='',email='',phone='';var b=card.querySelector('.row b'),s=card.querySelector('small');if(b)name=(b.textContent||'').trim();if(s)contact=(s.textContent||'').trim();if(contact.indexOf('@')>=0)email=contact;else phone=contact;if(isDeleted({name:name,email:email,phone:phone,id:card.getAttribute('data-customer-id')}))card.remove()}}
function removeSavedCustomer(c){var list=read(CUSTOMERS_KEY);save(CUSTOMERS_KEY,list.filter(function(x){return String(x.id)!==String(c.id)&&key(x)!==key(c)}))}
function inject(){var detail=document.getElementById('customerDetail');if(!detail)return;var head=detail.querySelector('.customer-detail-head');if(!head)return;var old=head.querySelector('#tqbDeleteCustomerBtn');if(old)return;var edit=head.querySelector('#editCustomerBtn'),wrap=document.createElement('div');wrap.style.cssText='display:flex;gap:8px;flex-wrap:wrap';if(edit){edit.parentNode.insertBefore(wrap,edit);wrap.appendChild(edit)}else head.appendChild(wrap);var btn=document.createElement('button');btn.id='tqbDeleteCustomerBtn';btn.type='button';btn.className='secondary';btn.textContent='🗑 Delete';btn.style.cssText='background:#fff0f0;color:#b42318;border:1px solid #f3b6b6;white-space:nowrap';wrap.appendChild(btn);btn.onclick=function(){var c=currentCustomer();if(!c)return;var linked=0;try{var inv=JSON.parse(localStorage.getItem('tqb_invoices_v1')||'[]');linked=Array.isArray(inv)?inv.filter(function(x){return key({name:x.customerName,email:x.customerEmail,phone:x.customerPhone})===key(c)}).length:0}catch(e){}var msg='Delete '+(c.name||'this customer')+' from your customer list?\n\nTheir customer profile will be removed, but existing quotes and invoices will NOT be deleted.';if(linked)msg+='\n\nLinked invoices: '+linked+'.';msg+='\n\nThe customer will stay deleted until you create/add them again.';if(!window.confirm(msg))return;rememberDeleted(c);removeSavedCustomer(c);var card=document.querySelector('.customer-card[data-customer-id="'+String(c.id).replace(/"/g,'\\"')+'"]');if(card)card.remove();detail.innerHTML='';removeDeletedCards();setTimeout(removeDeletedCards,0);setTimeout(removeDeletedCards,100);setTimeout(removeDeletedCards,500);if(typeof window.dispatchEvent==='function')window.dispatchEvent(new Event('customerDeleted'))}}
function start(){inject();removeDeletedCards();setInterval(function(){inject();removeDeletedCards()},250);document.addEventListener('click',function(e){if(e.target.closest&&e.target.closest('.customer-card,[data-screen="customers"]'))setTimeout(function(){inject();removeDeletedCards()},25)});window.addEventListener('focus',function(){inject();removeDeletedCards()});if(window.MutationObserver){var obs=new MutationObserver(function(){removeDeletedCards()});obs.observe(document.body,{childList:true,subtree:true})}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
