(function(){
'use strict';
var CUSTOMERS_KEY='tqb_customers_v1',INVOICES_KEY='tqb_invoices_v1';
function readCustomers(){try{var x=JSON.parse(localStorage.getItem(CUSTOMERS_KEY)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function saveCustomers(x){try{localStorage.setItem(CUSTOMERS_KEY,JSON.stringify(x))}catch(e){}}
function readInvoices(){try{var x=JSON.parse(localStorage.getItem(INVOICES_KEY)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function norm(v){return String(v||'').trim().toLowerCase().replace(/\s+/g,' ')}
function phoneKey(v){var p=String(v||'').replace(/\D/g,'');if(p.indexOf('61')===0&&p.length>=10)p='0'+p.slice(2);return p}
function key(c){var e=norm(c.email),p=phoneKey(c.phone),n=norm(c.name);if(p&&e)return e+'|'+p;if(p)return p;if(e)return e+'|'+n;return n}
function findCustomer(){var detail=document.getElementById('customerDetail');if(!detail)return null;var h=detail.querySelector('h3');if(!h)return null;var name=(h.textContent||'').trim(),nodes=detail.querySelectorAll('.customer-detail-head div div'),email='',phone='';for(var i=0;i<nodes.length;i++){var t=(nodes[i].textContent||'').trim();if(t.indexOf('@')>=0)email=t;else if(/\d/.test(t)&&t.length<=20)phone=t}var list=readCustomers(),c=list.find(function(x){return key(x)===key({name:name,email:email,phone:phone})});if(!c)c=list.find(function(x){return norm(x.name)===norm(name)});return c||null}
function inject(){var detail=document.getElementById('customerDetail');if(!detail)return;var head=detail.querySelector('.customer-detail-head');if(!head||head.querySelector('#tqbDeleteCustomerBtn'))return;var edit=head.querySelector('#editCustomerBtn');var wrap=document.createElement('div');wrap.style.cssText='display:flex;gap:8px;flex-wrap:wrap';if(edit){edit.parentNode.insertBefore(wrap,edit);wrap.appendChild(edit)}else{head.appendChild(wrap)}var btn=document.createElement('button');btn.id='tqbDeleteCustomerBtn';btn.type='button';btn.className='secondary';btn.textContent='🗑 Delete';btn.style.cssText='background:#fff0f0;color:#b42318;border:1px solid #f3b6b6;white-space:nowrap';wrap.appendChild(btn);btn.onclick=function(){var c=findCustomer();if(!c)return;var linked=readInvoices().filter(function(inv){return key({name:inv.customerName,email:inv.customerEmail,phone:inv.customerPhone})===key(c)}).length;var msg='Delete '+(c.name||'this customer')+' from your customer list?\n\nThis removes the saved customer contact only. Existing quotes and invoices will NOT be deleted.';if(linked)msg+='\n\nThey currently have '+linked+' linked invoice'+(linked===1?'':'s')+'.';if(!window.confirm(msg))return;saveCustomers(readCustomers().filter(function(x){return String(x.id)!==String(c.id)}));detail.innerHTML='';var cards=document.querySelectorAll('.customer-card');for(var i=0;i<cards.length;i++){if(String(cards[i].getAttribute('data-customer-id'))===String(c.id))cards[i].remove()}}}
function start(){inject();setInterval(inject,500);document.addEventListener('click',function(e){if(e.target.closest&&e.target.closest('.customer-card,[data-screen="customers"]'))setTimeout(inject,50)});window.addEventListener('focus',inject)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
