(function(){
'use strict';
var KEY='tqb_customers_v1',QUOTES='tqb_quotes_v6',INVOICES='tqb_invoices_v1';
function $(id){return document.getElementById(id)}
function money(v){return new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(Number(v)||0)}
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'})[c]})}
function read(k){try{var x=JSON.parse(localStorage.getItem(k)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function write(k,x){try{localStorage.setItem(k,JSON.stringify(x))}catch(e){}}
function norm(v){return String(v||'').trim().toLowerCase().replace(/\s+/g,' ')}
function keyFor(x){return norm(x.email)||norm(x.phone)||norm(x.name)}
function records(){return read(QUOTES).concat(read(INVOICES))}
function build(){var saved=read(KEY),map={},out=[];saved.forEach(function(c){if(c&&c.id)map[c.id]=Object.assign({},c)});records().forEach(function(r){var name=String(r.customerName||'').trim();if(!name)return;var k=keyFor({name:name,email:r.customerEmail,phone:r.customerPhone}),found=null;Object.keys(map).some(function(id){var c=map[id];var ck=keyFor({name:c.name,email:c.email,phone:c.phone});if(ck&&ck===k){found=c;return true}return false});if(!found){found={id:'cust-'+Date.now()+'-'+Math.random().toString(16).slice(2),name:name,email:String(r.customerEmail||'').trim(),phone:String(r.customerPhone||'').trim(),address:String(r.customerAddress||'').trim(),notes:'',createdAt:Date.now()};map[found.id]=found}else{if(!found.name)found.name=name;if(!found.email&&r.customerEmail)found.email=String(r.customerEmail).trim();if(!found.phone&&r.customerPhone)found.phone=String(r.customerPhone).trim();if(!found.address&&r.customerAddress)found.address=String(r.customerAddress).trim()}});Object.keys(map).forEach(function(id){var c=map[id],qs=read(QUOTES).filter(function(q){return keyFor({name:q.customerName,email:q.customerEmail,phone:q.customerPhone})===keyFor(c)}),ins=read(INVOICES).filter(function(i){return keyFor({name:i.customerName,email:i.customerEmail,phone:i.customerPhone})===keyFor(c)});c.quoteCount=qs.length;c.invoiceCount=ins.length;c.totalInvoiced=ins.reduce(function(a,i){return a+(Number(i.total)||0)},0);c.totalPaid=ins.filter(function(i){return String(i.status||'').toLowerCase()==='paid'}).reduce(function(a,i){return a+(Number(i.total)||0)},0);c.outstanding=Math.max(0,c.totalInvoiced-c.totalPaid);out.push(c)});out.sort(function(a,b){return norm(a.name).localeCompare(norm(b.name))});write(KEY,out);return out}
function styles(){if($('tqb-customers-style'))return;var s=document.createElement('style');s.id='tqb-customers-style';s.textContent='.customers-wrap{max-width:1100px;margin:0 auto}.customers-toolbar{display:flex;gap:10px;margin-bottom:14px}.customers-toolbar input{margin:0;flex:1}.customer-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.customer-card{background:#fff;border:1px solid #e6eaf0;border-radius:14px;padding:18px;cursor:pointer;box-shadow:0 3px 14px #1720330b}.customer-card:hover{background:#fafcff}.customer-card .row{display:flex;justify-content:space-between;gap:12px}.customer-card small{display:block;color:#667085;margin-top:5px}.customer-metrics{display:flex;gap:16px;flex-wrap:wrap;margin-top:14px;font-size:12px;color:#475467}.customer-metrics b{color:#111}.customer-detail{margin-top:14px;background:#fff;border-radius:14px;padding:20px;border:1px solid #e6eaf0}.customer-detail-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.customer-detail h3{margin:0 0 5px;font-size:22px}.customer-record{padding:12px 0;border-top:1px solid #eee;display:flex;justify-content:space-between;gap:12px}.customer-record small{color:#667085}.customer-stat-row{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:16px 0}.customer-stat{background:#f8fafc;border:1px solid #e5e7eb;border-radius:11px;padding:13px}.customer-stat span{display:block;color:#667085;font-size:11px}.customer-stat b{display:block;margin-top:5px;font-size:17px}.customer-form{margin-top:14px;background:#fff;border:1px solid #e6eaf0;border-radius:14px;padding:18px}.customer-form-actions{display:flex;gap:10px}.customer-form-actions button{flex:1}@media(max-width:650px){.customer-grid{grid-template-columns:1fr}.customer-stat-row{grid-template-columns:1fr 1fr}.customers-toolbar{flex-direction:column}}';document.head.appendChild(s)}
function ensureScreen(){if($('customers'))return;var main=document.querySelector('main');if(!main)return;var sec=document.createElement('section');sec.id='customers';sec.className='screen';sec.innerHTML='<div class="section-head"><button class="back-btn" data-back>← Back</button><h2>Customers</h2><button class="primary" id="newCustomerBtn">＋ Add Customer</button></div><div class="customers-wrap"><div class="customers-toolbar"><input id="customerSearch" placeholder="Search customers by name, phone or email"><button class="secondary" id="refreshCustomersBtn">Refresh</button></div><div id="customerList"></div><div id="customerDetail"></div></div>';main.appendChild(sec)}
function ensureNav(){var n=document.querySelector('.bottom-nav');if(!n)return;if(n.querySelector('[data-screen="customers"]'))return;var b=document.createElement('button');b.className='nav';b.setAttribute('data-screen','customers');b.innerHTML='👥<span>Customers</span>';var settings=n.querySelector('[data-screen="settings"]');n.insertBefore(b,settings||null);var st=document.createElement('style');st.id='tqb-customer-nav-style';st.textContent='.bottom-nav .nav[data-screen="customers"]:before{content:"👥"!important}.bottom-nav .nav[data-screen="settings"]:before{content:"⚙"!important}@media(max-width:800px){.bottom-nav{grid-template-columns:repeat(6,1fr)!important}.bottom-nav .nav{padding-left:2px!important;padding-right:2px!important;gap:2px!important}.bottom-nav .nav span{font-size:9px!important}}';document.head.appendChild(st)}
function show(){ensureScreen();ensureNav();document.querySelectorAll('.screen').forEach(function(x){x.classList.toggle('active',x.id==='customers')});document.querySelectorAll('.nav').forEach(function(x){x.classList.toggle('active',x.getAttribute('data-screen')==='customers')});window.scrollTo(0,0);render()}
function render(){var list=build(),search=norm($('customerSearch')&&$('customerSearch').value),filtered=list.filter(function(c){return !search||[c.name,c.email,c.phone,c.address].some(function(v){return norm(v).indexOf(search)>=0})}),el=$('customerList');if(!el)return;if(!filtered.length){el.innerHTML='<div class="empty">No customers found.<br><br>Customers are created automatically from your quotes and invoices.</div>'}else{el.innerHTML='<div class="customer-grid">'+filtered.map(function(c){return '<div class="customer-card" data-customer-id="'+esc(c.id)+'"><div class="row"><b>'+esc(c.name)+'</b><b>'+money(c.totalInvoiced)+'</b></div><small>'+esc(c.phone||c.email||'No contact details')+'</small><div class="customer-metrics"><span>Quotes <b>'+c.quoteCount+'</b></span><span>Invoices <b>'+c.invoiceCount+'</b></span><span>Paid <b>'+money(c.totalPaid)+'</b></span><span>Due <b>'+money(c.outstanding)+'</b></span></div></div>'}).join('')+'</div>'}el.querySelectorAll('.customer-card').forEach(function(card){card.onclick=function(){openDetail(build().find(function(c){return String(c.id)===String(card.getAttribute('data-customer-id'))}))}})}
function openDetail(c){var qs=read(QUOTES).filter(function(q){return keyFor({name:q.customerName,email:q.customerEmail,phone:q.customerPhone})===keyFor(c)}),ins=read(INVOICES).filter(function(i){return keyFor({name:i.customerName,email:i.customerEmail,phone:i.customerPhone})===keyFor(c)}),all=qs.map(function(q){return{type:'Quote',number:q.number,date:q.date,total:q.total,status:q.status||q.quoteStatus||'Pending'}}).concat(ins.map(function(i){return{type:'Invoice',number:i.number,date:i.invoiceDate,total:i.total,status:i.status||'Unpaid'}})).sort(function(a,b){return String(b.date||'').localeCompare(String(a.date||''))});$('customerDetail').innerHTML='<div class="customer-detail"><div class="customer-detail-head"><div><h3>'+esc(c.name)+'</h3><div>'+esc(c.email||'No email')+'</div><div>'+esc(c.phone||'No phone')+'</div><div>'+esc(c.address||'No address')+'</div></div><button class="secondary" id="editCustomerBtn">✏️ Edit</button></div><div class="customer-stat-row"><div class="customer-stat"><span>Total invoiced</span><b>'+money(c.totalInvoiced)+'</b></div><div class="customer-stat"><span>Total paid</span><b>'+money(c.totalPaid)+'</b></div><div class="customer-stat"><span>Outstanding</span><b>'+money(c.outstanding)+'</b></div></div><h4>Recent activity</h4>'+ (all.length?all.slice(0,12).map(function(r){return '<div class="customer-record"><div><b>'+esc(r.type)+' '+esc(r.number)+'</b><small>'+esc(r.date||'')+'</small></div><b>'+money(r.total)+'</b></div>'}).join(''):'<p class="storage-note">No quotes or invoices yet.</p>')+'</div>';$('editCustomerBtn').onclick=function(){editForm(c)}}
function editForm(c){$('customerDetail').innerHTML='<div class="customer-form"><h3 style="margin-top:0">Edit customer</h3><label>Customer name<input id="editCustName" value="'+esc(c.name)+'"></label><label>Phone<input id="editCustPhone" value="'+esc(c.phone)+'"></label><label>Email<input id="editCustEmail" type="email" value="'+esc(c.email)+'"></label><label>Address<textarea id="editCustAddress" rows="3">'+esc(c.address)+'</textarea></label><label>Notes<textarea id="editCustNotes" rows="3" placeholder="Private notes">'+esc(c.notes)+'</textarea></label><div class="customer-form-actions"><button class="secondary" id="cancelCustEdit">Cancel</button><button class="primary" id="saveCustEdit">Save Customer</button></div></div>';$('cancelCustEdit').onclick=function(){openDetail(c)};$('saveCustEdit').onclick=function(){var list=read(KEY),found=list.find(function(x){return String(x.id)===String(c.id)});if(!found)return;found.name=$('editCustName').value.trim()||c.name;found.phone=$('editCustPhone').value.trim();found.email=$('editCustEmail').value.trim();found.address=$('editCustAddress').value.trim();found.notes=$('editCustNotes').value.trim();write(KEY,list);alert('Customer saved.');render();openDetail(build().find(function(x){return String(x.id)===String(found.id)}))}}
function addCustomer(){var c={id:'cust-'+Date.now()+'-'+Math.random().toString(16).slice(2),name:'',email:'',phone:'',address:'',notes:'',createdAt:Date.now()};var list=read(KEY);list.unshift(c);write(KEY,list);render();editForm(c)}
function wire(){styles();ensureScreen();ensureNav();var s=$('customerSearch');if(s&&!s.dataset.wired){s.dataset.wired='1';s.addEventListener('input',render)}var r=$('refreshCustomersBtn');if(r&&!r.dataset.wired){r.dataset.wired='1';r.onclick=render}var n=$('newCustomerBtn');if(n&&!n.dataset.wired){n.dataset.wired='1';n.onclick=addCustomer}document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('[data-screen="customers"]');if(b){e.preventDefault();show()}});}
function start(){wire();setInterval(function(){if($('customers')&&$('customers').classList.contains('active'))render()},5000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
