(function(){
'use strict';
function $(id){return document.getElementById(id)}
function money(v){return new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(Number(v)||0)}
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'})[c]})}
function getQuotes(){try{var q=JSON.parse(localStorage.getItem('tqb_quotes_v6')||'[]');return Array.isArray(q)?q:[]}catch(e){return[]}}
function injectStyles(){if($('tqb-dashboard-style'))return;var s=document.createElement('style');s.id='tqb-dashboard-style';s.textContent=`
@media(min-width:801px){
 body{padding:0 0 0 280px!important;background:#f4f7fb;color:#172033;min-height:100vh}
 .topbar{position:fixed!important;left:0!important;top:0!important;bottom:0!important;width:280px!important;height:100vh!important;background:linear-gradient(180deg,#151b24,#10151d)!important;padding:28px 18px 22px!important;display:flex!important;flex-direction:column!important;align-items:stretch!important;justify-content:flex-start!important;border-right:1px solid #29313d!important;z-index:50!important}
 .topbar .brand{display:flex!important;flex-direction:column!important;align-items:stretch!important;gap:12px!important;margin:0 0 26px!important;padding:0 12px!important}.topbar .brand .logo{width:220px!important;height:220px!important;display:block!important;margin:0 auto!important;overflow:hidden!important;border-radius:28px!important}.topbar .brand .logo img{width:100%!important;height:100%!important;display:block!important;object-fit:cover!important;border-radius:28px!important}.topbar .brand>div:last-child{display:none!important}.topbar .icon-btn{position:absolute!important;opacity:0!important;pointer-events:none!important}
 .bottom-nav{position:fixed!important;left:0!important;top:330px!important;bottom:auto!important;width:280px!important;height:auto!important;background:transparent!important;display:flex!important;flex-direction:column!important;gap:4px!important;padding:0 12px!important;z-index:60!important}
 .bottom-nav .nav{width:100%!important;display:flex!important;align-items:center!important;justify-content:flex-start!important;gap:12px!important;padding:13px 14px!important;border-radius:10px!important;color:#b9c1cd!important;min-height:48px!important;text-align:left!important;font-size:0!important;background:transparent!important;border:0!important}.bottom-nav .nav span{font-size:15px!important;font-weight:600!important}.bottom-nav .nav.active{background:#2b3543!important;color:#fff!important}.bottom-nav .nav span:before{display:inline-block!important;width:24px!important;margin-right:12px!important;text-align:center!important;font-size:19px!important}.bottom-nav .nav:nth-child(1) span:before{content:'⌂'}.bottom-nav .nav:nth-child(2) span:before{content:'＋'}.bottom-nav .nav:nth-child(3) span:before{content:'▤'}.bottom-nav .nav:nth-child(4) span:before{content:'🧾'}.bottom-nav .nav:nth-child(5) span:before{content:'⚙'}
 .sidebar-subscription{position:absolute!important;left:22px!important;right:22px!important;bottom:92px!important;display:block!important;text-decoration:none!important;background:#ffb000!important;color:#111!important;border-radius:10px!important;padding:12px 14px!important;font-size:14px!important;font-weight:800!important;text-align:center!important;box-shadow:0 3px 10px #0002!important}.sidebar-subscription:hover{background:#ffc126!important}
 .sidebar-account{position:absolute!important;left:22px!important;right:22px!important;bottom:22px!important;border-top:1px solid #343c48!important;padding-top:18px!important;color:#fff!important}.sidebar-account b{display:block!important;font-size:15px!important}.sidebar-account span{display:block!important;color:#aab2be!important;font-size:12px!important;margin-top:5px!important}
 main{min-height:100vh}.screen{max-width:none;padding:36px 38px}.screen#dashboard{max-width:1400px;margin:0 auto}.hero{background:transparent;color:#172033;padding:0;margin:0 0 30px;display:flex;align-items:center;justify-content:space-between;border-radius:0}.hero h1{font-size:38px;margin:0 0 6px}.hero p:not(.eyebrow){color:#667085}.hero .primary{margin:0;background:#1677f0;color:#fff;border-radius:10px;padding:15px 24px;font-size:16px;box-shadow:0 3px 10px #1677f033}.eyebrow{color:#1677f0!important;letter-spacing:1.5px}.stats{grid-template-columns:repeat(4,1fr);gap:20px;margin-bottom:26px}.stat{min-height:142px;padding:22px;border:1px solid #e6eaf0;border-radius:14px;box-shadow:0 3px 14px #1720330b;position:relative}.stat span{font-size:15px;color:#667085}.stat b{font-size:32px;margin-top:13px;color:#172033}.stat:before{content:'•';position:absolute;right:22px;top:20px;font-size:44px;line-height:1;color:#dce8f8}.stat:nth-child(2):before{color:#d7f1e0}.stat:nth-child(3):before{color:#faebc7}.stat:nth-child(4):before{color:#f8d9dc}.section-head{margin:12px 0 14px}.section-head h2{font-size:24px}.text-btn{color:#1677f0}#recentQuotes{background:#fff;border:1px solid #e6eaf0;border-radius:14px;box-shadow:0 3px 14px #1720330b;overflow:hidden}.dashboard-table{width:100%;border-collapse:collapse}.dashboard-table th{background:#f6f8fb;text-align:left;padding:13px 18px;font-size:13px;color:#667085}.dashboard-table td{padding:14px 18px;border-top:1px solid #edf0f4;font-size:14px}.dashboard-table td.amount{font-weight:700}.dashboard-table tr{cursor:pointer}.dashboard-table tr:hover{background:#fafcff}.status-pill{display:inline-block;padding:5px 12px;border-radius:999px;font-weight:700;font-size:12px}.status-pending{background:#e6f0ff;color:#1769c2}.status-accepted{background:#dff5e8;color:#148043}.status-declined{background:#fde1e2;color:#d92d20}.dashboard-lower{display:grid;grid-template-columns:minmax(0,2fr) minmax(300px,1fr);gap:22px;margin-top:24px}.quick-actions{background:#fff;border:1px solid #e6eaf0;border-radius:14px;padding:22px;box-shadow:0 3px 14px #1720330b}.quick-actions h2{margin:0 0 16px;font-size:22px}.quick-action{display:grid;grid-template-columns:30px 1fr 15px;align-items:center;gap:12px;padding:14px;border-radius:11px;margin:10px 0;cursor:pointer}.quick-action strong{display:block;font-size:15px}.quick-action span{display:block;font-size:12px;color:#667085;margin-top:3px}.qa-blue{background:#e7f1ff;color:#1769c2}.qa-green{background:#e5f7ed;color:#148043}.qa-yellow{background:#fff2cf;color:#a66700}.qa-purple{background:#eee6ff;color:#6638b8}.feature-card{display:none}#settingsBtn{display:none}
}
@media(max-width:800px){.dashboard-table,.dashboard-lower,.sidebar-account,.sidebar-subscription{display:none}}
`;document.head.appendChild(s)}
function setupSidebar(){var top=document.querySelector('.topbar');if(!top)return;var logo=top.querySelector('.brand .logo');if(logo&&!logo.querySelector('img'))logo.innerHTML='<img src="./icon.svg?v=2" alt="Tradie Quote Buddy logo">';if(!$('tqb-subscription')){var sub=document.createElement('a');sub.id='tqb-subscription';sub.className='sidebar-subscription';sub.href='./subscription.html';sub.textContent='💳 Subscription';top.appendChild(sub)}if(!$('tqb-account')){var a=document.createElement('div');a.id='tqb-account';a.className='sidebar-account';var settings={};try{settings=JSON.parse(localStorage.getItem('tqb_settings_v6')||'{}')}catch(e){}a.innerHTML='<b>'+esc(settings.businessName||'Your Business Name')+'</b><span>↪ Log out</span>';top.appendChild(a)}}
function statusFor(q){var s=String(q.status||q.quoteStatus||'').toLowerCase();if(s.indexOf('accept')>=0)return ['Accepted','status-accepted'];if(s.indexOf('declin')>=0||s.indexOf('reject')>=0)return ['Declined','status-declined'];return ['Pending','status-pending']}
function renderDashboard(){var d=$('dashboard');if(!d)return;var stats=d.querySelector('.stats');if(!stats)return;var quotes=getQuotes(),accepted=0,declined=0,i;for(i=0;i<quotes.length;i++){var st=statusFor(quotes[i])[0];if(st==='Accepted')accepted++;if(st==='Declined')declined++}var statEls=stats.querySelectorAll('.stat');if(statEls[0]){statEls[0].querySelector('span').textContent='Total quotes';statEls[0].querySelector('b').textContent=quotes.length}if(statEls[1]){statEls[1].querySelector('span').textContent='Accepted';statEls[1].querySelector('b').textContent=accepted}if(statEls[2]){statEls[2].querySelector('span').textContent='Pending';statEls[2].querySelector('b').textContent=Math.max(0,quotes.length-accepted-declined)}if(statEls[3]){statEls[3].querySelector('span').textContent='Declined';statEls[3].querySelector('b').textContent=declined}var list=$('recentQuotes');if(!list)return;var recent=quotes.slice(0,5);if(!recent.length){list.innerHTML='<div class="empty">No quotes yet.<br><br>Tap <b>New Quote</b> to create your first one.</div>';return}var html='<table class="dashboard-table"><thead><tr><th>Quote #</th><th>Customer</th><th>Total</th><th>Status</th><th>Date</th></tr></thead><tbody>';recent.forEach(function(q){var st=statusFor(q);html+='<tr data-quote-id="'+esc(q.id)+'"><td><b>'+esc(q.number||'')+'</b></td><td>'+esc(q.customerName||'Unnamed customer')+'</td><td class="amount">'+money(q.total)+'</td><td><span class="status-pill '+st[1]+'">'+st[0]+'</span></td><td>'+esc(q.date||'')+'</td></tr>'});html+='</tbody></table>';list.innerHTML=html;list.querySelectorAll('tr[data-quote-id]').forEach(function(row){row.onclick=function(){var id=this.getAttribute('data-quote-id'),cards=document.querySelectorAll('.quote-card');for(var i=0;i<cards.length;i++)if(cards[i].getAttribute('data-id')===id){cards[i].click();break}}})}
function addQuickActions(){var dash=$('dashboard');if(!dash||$('tqb-dashboard-lower'))return;var lower=document.createElement('div');lower.id='tqb-dashboard-lower';lower.className='dashboard-lower';lower.innerHTML='<div></div><div class="quick-actions"><h2>Quick Actions</h2><div class="quick-action qa-blue" data-action="new"><div>▤</div><div><strong>Create New Quote</strong><span>Start a new quote for a customer</span></div><b>›</b></div><div class="quick-action qa-green" data-action="customers"><div>♟</div><div><strong>Manage Customers</strong><span>Use saved customer details</span></div><b>›</b></div><div class="quick-action qa-yellow" data-action="materials"><div>▣</div><div><strong>Manage Materials</strong><span>Update your materials and prices</span></div><b>›</b></div><div class="quick-action qa-purple" data-action="quotes"><div>◷</div><div><strong>View All Quotes</strong><span>See your quote history</span></div><b>›</b></div></div>';dash.appendChild(lower);lower.querySelectorAll('.quick-action').forEach(function(x){x.onclick=function(){var a=this.getAttribute('data-action');if(a==='new'&&$('newQuoteBtn'))$('newQuoteBtn').click();else if(a==='quotes'&&$('viewAllBtn'))$('viewAllBtn').click();else if((a==='customers'||a==='materials')&&document.querySelector('[data-screen="saved"]'))document.querySelector('[data-screen="saved"]').click()}})}
window.refreshTQBDashboard=renderDashboard;
function start(){injectStyles();setupSidebar();addQuickActions();renderDashboard();var list=$('recentQuotes');if(list){new MutationObserver(function(){setTimeout(renderDashboard,0)}).observe(list,{childList:true,subtree:true)}}document.addEventListener('click',function(e){var nav=e.target.closest&&e.target.closest('.nav');if(nav&&nav.getAttribute('data-screen')==='dashboard')setTimeout(renderDashboard,30)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
