(function(){
'use strict';
function $(id){return document.getElementById(id)}
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'})[c]})}
function money(v){return new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(Number(v)||0)}
function quotes(){try{var q=JSON.parse(localStorage.getItem('tqb_quotes_v6')||'[]');return Array.isArray(q)?q:[]}catch(e){return[]}}
function settings(){try{return JSON.parse(localStorage.getItem('tqb_settings_v6')||'{}')}catch(e){return{}}}
function statusFor(q){var s=String(q.status||q.quoteStatus||'').toLowerCase();if(s.indexOf('accept')>=0)return['Accepted','status-accepted'];if(s.indexOf('declin')>=0||s.indexOf('reject')>=0)return['Declined','status-declined'];return['Pending','status-pending']}
function css(){if($('tqb-sidebar-style'))return;var s=document.createElement('style');s.id='tqb-sidebar-style';s.textContent=`
@media(min-width:801px){
body{padding:0 0 0 270px!important;background:#f4f6f8!important}
.topbar{position:fixed!important;left:0!important;top:0!important;bottom:0!important;width:270px!important;height:100vh!important;display:block!important;background:#111!important;color:#fff!important;padding:20px 16px!important;z-index:1000!important;box-shadow:none!important;border:0!important}
.topbar .brand{display:block!important;margin:0!important;padding:0!important}.topbar .brand .logo{width:96px!important;height:96px!important;margin:0 auto 14px!important;display:block!important}.topbar .brand .logo img{width:100%!important;height:100%!important;object-fit:cover!important;border-radius:18px!important}.topbar .brand>div:last-child{text-align:center!important}.topbar .brand strong{font-size:18px!important}.topbar .brand span{font-size:11px!important;color:#aaa!important}.topbar .icon-btn{display:none!important}
.bottom-nav{position:fixed!important;left:16px!important;top:175px!important;right:auto!important;bottom:auto!important;width:238px!important;height:auto!important;display:flex!important;flex-direction:column!important;gap:5px!important;padding:0!important;background:transparent!important;color:#bfc5ce!important;z-index:1100!important}.bottom-nav .nav{width:100%!important;height:48px!important;min-height:48px!important;display:flex!important;align-items:center!important;justify-content:flex-start!important;gap:13px!important;padding:0 15px!important;border:0!important;border-radius:9px!important;background:transparent!important;color:#bfc5ce!important;font-size:0!important;text-align:left!important}.bottom-nav .nav span{font-size:15px!important;font-weight:600!important;color:inherit!important}.bottom-nav .nav.active{background:#2b3543!important;color:#ffb000!important}.bottom-nav .nav:before{display:block!important;width:22px!important;flex:0 0 22px!important;text-align:center!important;font-size:19px!important}.bottom-nav .nav:nth-child(1):before{content:'⌂'}.bottom-nav .nav:nth-child(2):before{content:'＋'}.bottom-nav .nav:nth-child(3):before{content:'▤'}.bottom-nav .nav:nth-child(4):before{content:'🧾'}.bottom-nav .nav:nth-child(5):before{content:'⚙'}
.screen{max-width:none!important;padding:36px 42px!important}.screen#dashboard{max-width:1120px!important;margin:0 auto!important}.stats{grid-template-columns:repeat(4,1fr)!important}.feature-card{display:block!important}
.sidebar-subscription{position:absolute!important;left:16px!important;right:16px!important;bottom:72px!important;display:block!important;background:#ffb000!important;color:#111!important;border-radius:9px!important;padding:12px!important;text-align:center!important;font-weight:800!important;text-decoration:none!important}.sidebar-account{position:absolute!important;left:16px!important;right:16px!important;bottom:18px!important;border-top:1px solid #333!important;padding-top:12px!important;color:#fff!important}.sidebar-account b{display:block!important;font-size:14px!important}.sidebar-account span{display:block!important;color:#999!important;font-size:11px!important;margin-top:4px!important}
.hero .primary{background:#ffb000!important;color:#111!important}
}
@media(max-width:800px){.sidebar-subscription,.sidebar-account{display:none!important}}
`;document.head.appendChild(s)}
function sidebar(){var top=document.querySelector('.topbar');if(!top)return;var logo=top.querySelector('.brand .logo');if(logo&&!logo.querySelector('img'))logo.innerHTML='<img src="./icon.svg?v=2" alt="Tradie Quote Buddy logo">';if(!$('tqb-subscription')){var sub=document.createElement('a');sub.id='tqb-subscription';sub.className='sidebar-subscription';sub.href='./subscription.html';sub.textContent='💳 Subscription';top.appendChild(sub)}if(!$('tqb-account')){var a=document.createElement('div');a.id='tqb-account';a.className='sidebar-account';var st=settings();a.innerHTML='<b>'+esc(st.businessName||'Your Business Name')+'</b><span>↪ Log out</span>';top.appendChild(a)}}
function nav(){var n=document.querySelector('.bottom-nav');if(!n)return;var inv=n.querySelector('[data-screen="invoices"]');if(!inv){inv=document.createElement('button');inv.className='nav';inv.setAttribute('data-screen','invoices');inv.innerHTML='🧾<span>Invoices</span>'}var home=n.querySelector('[data-screen="dashboard"]'),newQ=n.querySelector('[data-screen="quoteForm"]'),quotesNav=n.querySelector('[data-screen="saved"]'),settingsNav=n.querySelector('[data-screen="settings"]');[home,newQ,quotesNav,inv,settingsNav].forEach(function(x){if(x)n.appendChild(x)})}
function removeQuickActions(){var x=$('tqb-dashboard-lower');if(x)x.remove()}
function render(){var d=$('dashboard');if(!d)return;var qs=quotes(),a=0,dec=0;qs.forEach(function(q){var st=statusFor(q)[0];if(st==='Accepted')a++;if(st==='Declined')dec++});var stats=d.querySelectorAll('.stat');if(stats[0]){stats[0].querySelector('span').textContent='Total quotes';stats[0].querySelector('b').textContent=qs.length}if(stats[1]){stats[1].querySelector('span').textContent='Accepted';stats[1].querySelector('b').textContent=a}if(stats[2]){stats[2].querySelector('span').textContent='Pending';stats[2].querySelector('b').textContent=Math.max(0,qs.length-a-dec)}if(stats[3]){stats[3].querySelector('span').textContent='Declined';stats[3].querySelector('b').textContent=dec}var list=$('recentQuotes');if(!list)return;if(!qs.length){list.innerHTML='<div class="empty">No quotes yet.<br><br>Tap <b>New Quote</b> to create your first one.</div>';return}var html='<table class="dashboard-table"><thead><tr><th>Quote #</th><th>Customer</th><th>Total</th><th>Status</th><th>Date</th></tr></thead><tbody>';qs.slice(0,5).forEach(function(q){var st=statusFor(q);html+='<tr data-quote-id="'+esc(q.id)+'"><td><b>'+esc(q.number||'')+'</b></td><td>'+esc(q.customerName||'Unnamed customer')+'</td><td class="amount">'+money(q.total)+'</td><td><span class="status-pill '+st[1]+'">'+st[0]+'</span></td><td>'+esc(q.date||'')+'</td></tr>'});html+='</tbody></table>';list.innerHTML=html;list.querySelectorAll('tr[data-quote-id]').forEach(function(row){row.onclick=function(){var id=this.getAttribute('data-quote-id'),cards=document.querySelectorAll('.quote-card');for(var i=0;i<cards.length;i++)if(cards[i].getAttribute('data-id')===id){cards[i].click();break}}})}
window.refreshTQBDashboard=render;
function start(){css();sidebar();nav();removeQuickActions();render();setTimeout(function(){nav();removeQuickActions()},100);document.addEventListener('click',function(e){var n=e.target.closest&&e.target.closest('[data-screen="dashboard"]');if(n)setTimeout(render,50)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
