(function(){
'use strict';
if(window.__dustyDevicePairingLoaded)return;
window.__dustyDevicePairingLoaded=true;
var API='https://cychngcvhgtfuahavlqq.supabase.co/rest/v1/rpc/';
var ANON='sb_publishable_nc_WEOT-I9hR5oH9hEMURQ_mG92V_VA';
var KEY='tqb_square_owner_key_v1';
function owner(){try{return localStorage.getItem(KEY)||''}catch(e){return''}}
function valid(k){return /^[a-f0-9]{64}$/i.test(String(k||''))}
function ensureOwner(){var k=owner();if(!valid(k)){var a=new Uint8Array(32);crypto.getRandomValues(a);k=Array.from(a).map(function(b){return b.toString(16).padStart(2,'0')}).join('');localStorage.setItem(KEY,k)}return k}
function rpc(name,body){return fetch(API+name,{method:'POST',headers:{'Content-Type':'application/json','apikey':ANON,'Authorization':'Bearer '+ANON},body:JSON.stringify(body||{})}).then(function(r){return r.text().then(function(t){var d={};try{d=t?JSON.parse(t):{}}catch(e){d={}}if(!r.ok)throw new Error(d.message||d.error||'Pairing request failed.');return d})})}
function styles(){if(document.getElementById('tqb-pairing-style'))return;var s=document.createElement('style');s.id='tqb-pairing-style';s.textContent='.tqb-pair-card{margin:24px 0;padding:20px;border:1px solid #e1e5ea;border-radius:14px;background:#fff;box-shadow:0 2px 8px #0000000b}.tqb-pair-card h3{margin:0 0 7px;font-size:18px}.tqb-pair-card p{margin:7px 0;color:#69717c;font-size:13px;line-height:1.45}.tqb-pair-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:14px}.tqb-pair-actions button{border:0;border-radius:9px;padding:11px 15px;font-weight:800;cursor:pointer}.tqb-pair-primary{background:#171717;color:#fff}.tqb-pair-secondary{background:#f1f3f5;color:#171717}.tqb-pair-code{display:none;margin-top:14px;padding:14px;border-radius:10px;background:#fff8df;border:1px solid #ffd66b;text-align:center}.tqb-pair-code strong{display:block;font:900 28px/1.1 Arial;letter-spacing:4px;color:#171717}.tqb-pair-code small{display:block;margin-top:7px;color:#69717c}.tqb-pair-form{display:none;margin-top:14px}.tqb-pair-form input{width:100%;box-sizing:border-box;padding:12px;border:1px solid #ccd2d9;border-radius:9px;font-size:18px;letter-spacing:3px;text-transform:uppercase}.tqb-pair-msg{margin-top:10px;font-size:13px;font-weight:700}.tqb-pair-success{color:#166534}.tqb-pair-error{color:#991b1b}@media(max-width:600px){.tqb-pair-actions{flex-direction:column}.tqb-pair-actions button{width:100%}}';document.head.appendChild(s)}
function build(){if(document.getElementById('tqb-device-pairing'))return;var form=document.getElementById('settingsForm');if(!form)return;ensureOwner();var card=document.createElement('section');card.id='tqb-device-pairing';card.className='tqb-pair-card';card.innerHTML='<h3>📱 Connect another device</h3><p>Use a temporary pairing code to connect your phone, tablet or another computer to this DustyBoots business. Your code expires after 10 minutes and can only be used once.</p><div class="tqb-pair-actions"><button type="button" class="tqb-pair-primary" id="tqbGeneratePair">Generate pairing code</button><button type="button" class="tqb-pair-secondary" id="tqbShowClaim">Enter pairing code</button></div><div class="tqb-pair-code" id="tqbPairCode"><strong id="tqbPairCodeValue"></strong><small>Enter this code on the device you want to connect.</small></div><div class="tqb-pair-form" id="tqbPairForm"><input id="tqbPairInput" maxlength="12" inputmode="text" autocomplete="off" placeholder="12-character code"><div class="tqb-pair-actions"><button type="button" class="tqb-pair-primary" id="tqbClaimPair">Connect this device</button></div></div><div class="tqb-pair-msg" id="tqbPairMsg"></div>';form.appendChild(card);document.getElementById('tqbGeneratePair').onclick=function(){var btn=this;btn.disabled=true;btn.textContent='Generating…';rpc('tqb_create_pairing_code',{p_owner_key:ensureOwner()}).then(function(d){var code=typeof d==='string'?d:(d&&d[0]);if(!code)throw new Error('Could not create a pairing code.');document.getElementById('tqbPairCodeValue').textContent=code;document.getElementById('tqbPairCode').style.display='block';msg('Pairing code ready. It expires in 10 minutes.',true)}).catch(function(e){msg(e.message,false)}).finally(function(){btn.disabled=false;btn.textContent='Generate pairing code'})};document.getElementById('tqbShowClaim').onclick=function(){var f=document.getElementById('tqbPairForm');f.style.display=f.style.display==='block'?'none':'block';if(f.style.display==='block')document.getElementById('tqbPairInput').focus()};document.getElementById('tqbClaimPair').onclick=function(){var input=document.getElementById('tqbPairInput'),code=(input.value||'').replace(/\s+/g,'').toUpperCase();if(!/^[A-F0-9]{12}$/.test(code)){msg('Enter the 12-character pairing code.',false);return}var btn=this;btn.disabled=true;btn.textContent='Connecting…';rpc('tqb_claim_pairing_code',{p_code:code}).then(function(d){var k=typeof d==='string'?d:(d&&d[0]);if(!valid(k))throw new Error('The pairing response was invalid.');localStorage.setItem(KEY,k);msg('✓ Device connected. Reloading DustyBoots…',true);setTimeout(function(){location.reload()},700)}).catch(function(e){msg(e.message,false)}).finally(function(){btn.disabled=false;btn.textContent='Connect this device'})};function msg(t,ok){var el=document.getElementById('tqbPairMsg');if(!el)return;el.textContent=t;el.className='tqb-pair-msg '+(ok?'tqb-pair-success':'tqb-pair-error')}}
function init(){styles();build()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();setTimeout(init,500);setTimeout(init,1500)
})();
