(function(){
'use strict';
var KEY='tqb_invoices_v1';
var STATUS='https://cychngcvhgtfuahavlqq.supabase.co/functions/v1/square-payment-status';
function read(){try{var x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function save(x){try{localStorage.setItem(KEY,JSON.stringify(x))}catch(e){}}
function currentId(){var view=document.getElementById('invoiceView');if(!view)return null;var no=view.querySelector('.invoice-meta b');if(!no)return null;var n=(no.textContent||'').trim();var list=read();var inv=list.find(function(x){return String(x.number)===n});return inv?inv.id:null}
function updateStatus(inv){var view=document.getElementById('invoiceView');if(!view)return;view.querySelectorAll('.invoice-status').forEach(function(el){el.textContent=inv.status});var actions=view.querySelector('.invoice-actions');if(actions){var b=actions.querySelector('#markPaidBtn');if(inv.status==='Paid'){if(b){b.textContent='✓ Paid';b.disabled=true;b.style.opacity='.7'}var existing=view.querySelector('#paidDateNote');if(!existing){existing=document.createElement('div');existing.id='paidDateNote';existing.style.cssText='max-width:850px;margin:0 auto 12px;padding:10px 14px;border-radius:10px;background:#ecfdf3;color:#166534;font-weight:700;font-size:13px';existing.textContent='Paid on '+new Date(inv.paidAt||Date.now()).toLocaleDateString('en-AU');actions.parentNode.insertBefore(existing,actions.nextSibling)}}else if(b){b.textContent='💰 Mark as Paid';b.disabled=false;b.style.opacity='1'}}}
function syncOne(inv){if(!inv||(!inv.id&&!inv.number)||String(inv.status||'').toLowerCase()==='paid')return Promise.resolve(false);var qs=inv.id?'?invoice_id='+encodeURIComponent(inv.id):'?invoice_number='+encodeURIComponent(inv.number);if(inv.squarePaymentLinkId)qs+='&payment_link_id='+encodeURIComponent(inv.squarePaymentLinkId);return fetch(STATUS+qs,{cache:'no-store'}).then(function(r){return r.json().catch(function(){return null})}).then(function(x){if(!x||String(x.status||'').toLowerCase()!=='paid')return false;var list=read(),found=list.find(function(v){return String(v.id)===String(inv.id)||(inv.number&&String(v.number)===String(inv.number))});if(!found||String(found.status||'').toLowerCase()==='paid')return false;found.status='Paid';found.paidAt=found.paidAt||Date.now();found.paidSource='square';if(x.square_payment_link_id&&!found.squarePaymentLinkId)found.squarePaymentLinkId=x.square_payment_link_id;if(x.square_order_id&&!found.squareOrderId)found.squareOrderId=x.square_order_id;save(list);updateStatus(found);if(typeof window.renderList==='function')window.renderList();if(typeof window.refreshTQBDashboard==='function')window.refreshTQBDashboard();return true}).catch(function(){return false})}
function syncAll(){var list=read();return Promise.all(list.filter(function(x){return String(x.status||'').toLowerCase()!=='paid'&&(x.id||x.number)}).map(syncOne))}
function addPaidButton(){var view=document.getElementById('invoiceView');if(!view)return;var actions=view.querySelector('.invoice-actions');if(!actions||actions.querySelector('#markPaidBtn'))return;var id=currentId();if(!id)return;var inv=read().find(function(x){return String(x.id)===String(id)});if(!inv)return;var b=document.createElement('button');b.className='primary';b.id='markPaidBtn';b.textContent=inv.status==='Paid'?'✓ Paid':'💰 Mark as Paid';b.disabled=inv.status==='Paid';b.style.opacity=inv.status==='Paid'?'.7':'1';actions.insertBefore(b,actions.querySelector('#sendInvoiceBtn')||actions.firstChild);b.onclick=function(){var list=read(),found=list.find(function(x){return String(x.id)===String(id)});if(!found||found.status==='Paid')return;if(!confirm('Mark '+found.number+' as paid?\n\nThis will record a manual payment on this device.'))return;found.status='Paid';found.paidAt=Date.now();save(list);updateStatus(found);if(typeof window.renderList==='function')window.renderList();if(typeof window.refreshTQBDashboard==='function')window.refreshTQBDashboard()};updateStatus(inv);syncOne(inv)}
function deleteInvoice(id){var list=read(),inv=list.find(function(x){return String(x.id)===String(id)});if(!inv){alert('Could not find this invoice. Please refresh and try again.');return}if(!confirm('Delete invoice '+inv.number+'?\n\nThis will permanently remove the invoice from this device.'))return;save(list.filter(function(x){return String(x.id)!==String(id)}));location.reload()}
function addDeleteButton(){var view=document.getElementById('invoiceView');if(!view)return;var actions=view.querySelector('.invoice-actions');if(!actions||actions.querySelector('#deleteInvoiceBtn'))return;var id=currentId();if(!id)return;var b=document.createElement('button');b.type='button';b.id='deleteInvoiceBtn';b.className='danger';b.textContent='🗑️ Delete Invoice';b.onclick=function(){deleteInvoice(id)};actions.appendChild(b)}
function addListDeleteButtons(){var cards=document.querySelectorAll('.invoice-card');for(var i=0;i<cards.length;i++){var card=cards[i];if(card.querySelector('.invoice-delete-list-btn'))continue;var id=card.getAttribute('data-invoice-id');if(!id)continue;var b=document.createElement('button');b.type='button';b.className='secondary invoice-delete-list-btn';b.textContent='🗑️ Delete Invoice';b.style.cssText='margin-top:12px;width:100%;color:#c62828;font-weight:800';b.onclick=function(e){e.preventDefault();e.stopPropagation();deleteInvoice(this.parentElement.getAttribute('data-invoice-id'))};card.appendChild(b)}}
function watch(){var observer=new MutationObserver(function(){setTimeout(function(){addPaidButton();addDeleteButton();addListDeleteButtons()},0)});observer.observe(document.body,{childList:true,subtree:true});addPaidButton();addDeleteButton();addListDeleteButtons();syncAll();setInterval(syncAll,5000);window.addEventListener('focus',syncAll)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch);else watch();
})();
