(function(){
'use strict';
var KEY='tqb_invoices_v1';
var QUOTES_KEY='tqb_quotes_v6';
var SETTINGS_KEY='tqb_settings_v6';
function read(){try{var x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function write(x){try{localStorage.setItem(KEY,JSON.stringify(x));return true}catch(e){return false}}
function paid(x){return String(x&&x.status||'').toLowerCase()==='paid'}
function numberFromView(){var v=document.getElementById('invoiceView');if(!v)return '';var el=v.querySelector('[data-invoice-number],.invoice-number,#invoiceNumber');var t=el?(el.textContent||el.value||''):(v.textContent||'');var m=t.match(/INV-\d+/i);return m?m[0]:''}
function current(){var n=numberFromView();if(!n)return null;return read().find(function(x){return String(x.number).toUpperCase()===String(n).toUpperCase()})||null}
function buttons(v){return Array.from(v.querySelectorAll('button'))}
function findButton(v,rx,id){return v.querySelector(id)||buttons(v).find(function(b){return rx.test((b.textContent||'').trim())})}
function injectStyle(){if(document.getElementById('dusty-invoice-layout'))return;var s=document.createElement('style');s.id='dusty-invoice-layout';s.textContent='.dusty-invoice-actions{display:grid!important;grid-template-columns:1fr 1fr!important;gap:10px!important;width:100%!important;max-width:680px!important;margin:0 auto 14px!important}.dusty-invoice-actions>button{width:100%!important;min-height:52px!important;border:0!important;border-radius:12px!important;font-weight:800!important;font-size:15px!important;cursor:pointer!important}.dusty-invoice-actions .dusty-send{grid-column:1/-1!important;background:#ffb000!important;color:#111!important}.dusty-invoice-actions .dusty-paid{background:#16a34a!important;color:#fff!important}.dusty-invoice-actions .dusty-delete{background:#ffe8e8!important;color:#b42318!important}.dusty-invoice-actions .dusty-more{grid-column:1/-1!important;background:#eef0f4!important;color:#172033!important}.dusty-more-menu{display:none!important;grid-column:1/-1!important;background:#f7f8fa!important;border-radius:12px!important;padding:8px!important;gap:8px!important}.dusty-more-menu.open{display:grid!important;grid-template-columns:1fr 1fr!important}.dusty-more-menu button{background:#fff!important;color:#172033!important;border:1px solid #ddd!important}.dusty-more-menu .dusty-full{grid-column:1/-1!important}@media(max-width:600px){.dusty-invoice-actions{gap:8px!important}.dusty-more-menu.open{grid-template-columns:1fr!important}.dusty-more-menu button{grid-column:1/-1!important}}';document.head.appendChild(s)}
function layout(v){
 injectStyle();
 var send=findButton(v,/^\s*(send invoice|send)\b/i,'#sendInvoiceBtn');
 if(!send)return;
 var box=send.parentElement;
 if(!box)return;
 box.classList.add('dusty-invoice-actions');
 var paidBtn=findButton(v,/(mark as paid|mark paid|paid)/i,'#markPaidBtn');
 var del=findButton(v,/(delete invoice|delete)/i,'#deleteInvoiceBtn');
 send.classList.add('dusty-send');send.type='button';
 if(paidBtn){paidBtn.classList.add('dusty-paid');paidBtn.type='button';paidBtn.disabled=false;paidBtn.style.pointerEvents='auto'}
 if(del){del.classList.add('dusty-delete');del.type='button'}
 var more=box.querySelector('.dusty-more');
 if(!more){more=document.createElement('button');more.type='button';more.className='dusty-more';more.textContent='••• More';box.appendChild(more)}
 var menu=box.querySelector('.dusty-more-menu');
 if(!menu){menu=document.createElement('div');menu.className='dusty-more-menu';box.appendChild(menu)}
 Array.from(box.children).forEach(function(el){if(el.tagName==='BUTTON'&&el!==send&&el!==paidBtn&&el!==del&&el!==more&&!menu.contains(el))menu.appendChild(el)});
 more.onclick=function(e){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();menu.classList.toggle('open');more.textContent=menu.classList.contains('open')?'✕ Less':'••• More'};
 update(v,current());
}
function update(v,inv){if(!v||!inv)return;v.querySelectorAll('.invoice-status').forEach(function(s){s.textContent=inv.status||'Unpaid';s.setAttribute('aria-label',inv.status||'Unpaid')});var b=findButton(v,/(mark as paid|mark paid|paid)/i,'#markPaidBtn');if(b)b.textContent=paid(inv)?'↩ Mark as Unpaid':'💰 Mark as Paid'}
function togglePaid(){var inv=current();if(!inv)return;var list=read();var x=list.find(function(i){return String(i.number).toUpperCase()===String(inv.number).toUpperCase()});if(!x)return;if(paid(x)){x.status='Unpaid';delete x.paidAt;delete x.paidSource;delete x.paidMethod}else{x.status='Paid';x.paidAt=Date.now();x.paidSource='manual';x.paidMethod='Manual payment'}if(!write(list))return;var v=document.getElementById('invoiceView');update(v,x);if(typeof window.renderList==='function')window.renderList();if(typeof window.refreshTQBDashboard==='function')window.refreshTQBDashboard()}
function handler(e){var t=e.target&&e.target.closest?e.target.closest('button'):null;if(!t)return;var label=(t.textContent||'').trim();if(t.id==='markPaidBtn'||/^(💰\s*)?mark as paid$/i.test(label)||/^(↩\s*)?mark as unpaid$/i.test(label)){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();togglePaid()}}
function fullData(){var quotes=[],settings={},invoices=read();try{quotes=JSON.parse(localStorage.getItem(QUOTES_KEY)||'[]');if(!Array.isArray(quotes))quotes=[]}catch(e){}try{settings=JSON.parse(localStorage.getItem(SETTINGS_KEY)||'{}')||{}}catch(e){}return {version:9,app:'DustyBoots Invoicing',exportedAt:new Date().toISOString(),quotes:quotes,settings:settings,invoices:invoices}}
function downloadData(){var blob=new Blob([JSON.stringify(fullData(),null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='dustyboots-full-backup.json';document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(url)},1500)}
function mergeByIdOrNumber(oldList,newList){var out=Array.isArray(oldList)?oldList.slice():[],index={};out.forEach(function(x,i){if(x&&x.id!=null)index['id:'+String(x.id)]=i;if(x&&x.number!=null)index['num:'+String(x.number).toUpperCase()]=i});(Array.isArray(newList)?newList:[]).forEach(function(x){if(!x)return;var k=x.id!=null?'id:'+String(x.id):(x.number!=null?'num:'+String(x.number).toUpperCase():'');if(k&&index[k]!=null)out[index[k]]=x;else{out.push(x);if(k)index[k]=out.length-1}});return out}
function restoreData(file){var r=new FileReader();r.onload=function(){try{var data=JSON.parse(r.result);if(!data||!Array.isArray(data.quotes)||!Array.isArray(data.invoices))throw new Error('This is not a DustyBoots full backup');var oldQuotes=[];try{oldQuotes=JSON.parse(localStorage.getItem(QUOTES_KEY)||'[]')}catch(e){}var oldInvoices=read();localStorage.setItem(QUOTES_KEY,JSON.stringify(mergeByIdOrNumber(oldQuotes,data.quotes)));localStorage.setItem(KEY,JSON.stringify(mergeByIdOrNumber(oldInvoices,data.invoices)));if(data.settings&&typeof data.settings==='object')localStorage.setItem(SETTINGS_KEY,JSON.stringify(data.settings));alert('Full backup restored. Your quotes and invoices are now in this app.');location.reload()}catch(err){alert('Restore failed: '+err.message)}};r.onerror=function(){alert('Could not read the backup file.')};r.readAsText(file)}
function dataTools(){var settings=document.getElementById('settings');if(!settings||document.getElementById('dusty-data-tools'))return;if(!settings.querySelector('button'))return;var box=document.createElement('div');box.id='dusty-data-tools';box.style.cssText='margin:20px 0;padding:16px;border:1px solid #ddd;border-radius:14px;background:#f7f8fa';box.innerHTML='<b style="display:block;font-size:17px;margin-bottom:6px">Backup & Restore</b><div style="font-size:14px;margin-bottom:12px">Back up quotes, invoices and business settings so your data can move safely between the browser and installed app.</div><button id="dustyExportBtn" type="button" style="width:100%;min-height:48px;border:0;border-radius:10px;background:#172033;color:#fff;font-weight:800;margin-bottom:8px">Export Full Backup</button><button id="dustyImportBtn" type="button" style="width:100%;min-height:48px;border:1px solid #ccc;border-radius:10px;background:#fff;color:#172033;font-weight:800">Import Full Backup</button><input id="dustyImportFile" type="file" accept="application/json,.json" style="display:none">';settings.appendChild(box);document.getElementById('dustyExportBtn').onclick=function(e){e.preventDefault();downloadData()};document.getElementById('dustyImportBtn').onclick=function(e){e.preventDefault();document.getElementById('dustyImportFile').click()};document.getElementById('dustyImportFile').onchange=function(){if(this.files&&this.files[0])restoreData(this.files[0]);this.value=''}}
function patch(){var v=document.getElementById('invoiceView');if(v)layout(v);dataTools()}
function start(){document.addEventListener('click',handler,true);patch();new MutationObserver(patch).observe(document.body,{childList:true,subtree:true});setInterval(patch,1000);try{if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js?v=61',{updateViaCache:'none'}).then(function(reg){try{reg.update()}catch(e){}}).catch(function(){})}}catch(e){}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
