(function(){
'use strict';
var KEY='tqb_invoices_v1';
var CREATE='https://cychngcvhgtfuahavlqq.supabase.co/functions/v1/square-create-payment-link';
var OWNER_KEY='tqb_square_owner_key_v1';
function read(){try{var x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function save(x){try{localStorage.setItem(KEY,JSON.stringify(x));return true}catch(e){return false}}
function invoiceNumber(){var text=document.body?document.body.innerText:'';var m=text.match(/INV-\d+/i);return m?m[0]:''}
function current(){var n=invoiceNumber();if(!n)return null;return read().find(function(x){return String(x.number||'').toUpperCase()===n.toUpperCase()})||null}
function isPaid(x){return String(x&&x.status||'').toLowerCase()==='paid'}
function manual(x){return isPaid(x)&&String(x.paidSource||'').toLowerCase()!=='square'}
function style(){if(document.getElementById('tqb-invoice-layout-fix'))return;var s=document.createElement('style');s.id='tqb-invoice-layout-fix';s.textContent='.invoice-actions{display:grid!important;grid-template-columns:1fr 1fr!important;gap:8px!important;width:100%!important;max-width:900px!important;margin:0 auto 18px!important}.invoice-actions button{width:100%!important;min-width:0!important;min-height:54px!important;padding:12px 10px!important;border:0!important;border-radius:14px!important;font-size:15px!important;font-weight:800!important;cursor:pointer!important}.invoice-actions #sendInvoiceBtn{grid-column:auto!important;background:#ffb000!important;color:#111!important;order:1!important}.invoice-actions #markPaidBtn{background:#16a34a!important;color:#fff!important;order:2!important}.invoice-actions #invoiceEditBtn{background:#eef0f4!important;color:#172033!important;order:3!important}.invoice-actions #deleteInvoiceBtn{background:#ffe8e8!important;color:#b42318!important;order:4!important}.invoice-actions #invoiceMoreBtn{grid-column:1/-1!important;background:#eef0f4!important;color:#172033!important;order:5!important}.invoice-actions .tqb-more-menu{grid-column:1/-1!important;display:none!important;background:#f7f8fa!important;border-radius:14px!important;padding:10px!important;gap:8px!important;order:6!important}.invoice-actions .tqb-more-menu.open{display:grid!important;grid-template-columns:1fr 1fr!important}.invoice-actions .tqb-more-menu button{background:#fff!important;color:#172033!important;border:1px solid #e1e4e8!important}.invoice-actions .tqb-more-menu #squareInvoiceBtn,.invoice-actions .tqb-more-menu #setupSquareBtn{grid-column:1/-1!important;background:#20252b!important;color:#fff!important}.tqb-paid-menu{display:none!important;position:absolute!important;z-index:50!important;left:0!important;right:0!important;top:calc(100% + 6px)!important;background:#fff!important;border:1px solid #d9dde5!important;border-radius:14px!important;padding:8px!important;box-shadow:0 10px 30px rgba(0,0,0,.16)!important}.tqb-paid-menu.open{display:grid!important;grid-template-columns:1fr!important}.tqb-paid-menu button{background:#fff!important;color:#172033!important;border:1px solid #e1e4e8!important;margin:0!important}.tqb-paid-wrap{position:relative!important}.invoice-actions #markPaidBtn.tqb-paid-open{border-radius:14px 14px 8px 8px!important}@media(max-width:600px){.invoice-actions{gap:8px!important}.invoice-actions button{min-height:54px!important;font-size:15px!important}.invoice-actions .tqb-more-menu.open{grid-template-columns:1fr!important}}';document.head.appendChild(s)}
function actionBox(v){if(!v)return null;var a=v.querySelector('.invoice-actions');if(a)return a;var bs=Array.from(v.querySelectorAll('button'));var send=bs.find(function(b){return /Send Invoice/i.test(b.textContent||'')});if(send&&send.parentElement){send.parentElement.classList.add('invoice-actions');return send.parentElement}return null}
function layout(v){var a=actionBox(v);if(!a)return;var more=a.querySelector('#invoiceMoreBtn');if(!more){more=document.createElement('button');more.type='button';more.id='invoiceMoreBtn';more.textContent='••• More';a.appendChild(more)}var menu=a.querySelector('.tqb-more-menu');if(!menu){menu=document.createElement('div');menu.className='tqb-more-menu';a.appendChild(menu)}var keep={sendInvoiceBtn:1,deleteInvoiceBtn:1,markPaidBtn:1,invoiceMoreBtn:1,invoiceEditBtn:1};Array.from(a.querySelectorAll('button')).forEach(function(b){if(!keep[b.id]&&!menu.contains(b))menu.appendChild(b)});more.onclick=function(e){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();menu.classList.toggle('open');more.textContent=menu.classList.contains('open')?'✕ Less':'••• More'};if(!a.querySelector('#invoiceEditBtn')){var edit=document.createElement('button');edit.type='button';edit.id='invoiceEditBtn';edit.textContent='✏️ Edit Invoice';edit.onclick=function(e){e.preventDefault();if(!document.querySelector('script[data-invoice-editor]')){var sc=document.createElement('script');sc.src='./invoice-edit.js?v=11';sc.dataset.invoiceEditor='1';document.head.appendChild(sc)}};a.insertBefore(edit,more)}setupPaidMenu(a)}
function setupPaidMenu(a){var b=a.querySelector('#markPaidBtn');if(!b)return;var wrap=a.querySelector('.tqb-paid-wrap');if(!wrap){wrap=document.createElement('div');wrap.className='tqb-paid-wrap';wrap.style.gridColumn='auto';wrap.style.order='2';b.parentNode.insertBefore(wrap,b);wrap.appendChild(b)}var menu=wrap.querySelector('.tqb-paid-menu');if(!menu){menu=document.createElement('div');menu.className='tqb-paid-menu';menu.innerHTML='<button type="button" data-method="Cash">💵 Cash</button><button type="button" data-method="Bank transfer">🏦 Bank transfer</button><button type="button" data-method="Card / EFTPOS">💳 Card / EFTPOS</button><button type="button" data-method="Other">Other</button>';wrap.appendChild(menu);Array.from(menu.querySelectorAll('button')).forEach(function(x){x.onclick=function(e){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();markPaid(x.dataset.method);menu.classList.remove('open')}})}b.onclick=function(e){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();var inv=current();if(inv&&isPaid(inv)){markPaid(null);return}menu.classList.toggle('open')};b.onpointerup=function(e){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation()};b.ontouchend=function(e){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation()}}
function updateView(inv){var v=document.getElementById('invoiceView');if(!v||!inv)return;v.querySelectorAll('.invoice-status').forEach(function(s){var st=inv.status||'Unpaid';if(s.textContent!==st)s.textContent=st;if(s.getAttribute('aria-label')!==st)s.setAttribute('aria-label',st);if(isPaid(inv)){if(s.style.background!=='rgb(236, 253, 243)')s.style.background='#ecfdf3';if(s.style.color!=='rgb(22, 101, 52)')s.style.color='#166534'}});var b=v.querySelector('#markPaidBtn');if(b){b.type='button';b.disabled=false;b.style.pointerEvents='auto';b.style.cursor='pointer';b.style.opacity='1';var txt=isPaid(inv)?'↩ Mark as Unpaid':'💰 Mark as Paid';if(b.textContent!==txt)b.textContent=txt}}
function refresh(){if(typeof window.refreshTQBDashboard==='function')window.refreshTQBDashboard();if(typeof window.renderList==='function')window.renderList()}
function markPaid(method){var inv=current();if(!inv)return;var list=read(),live=list.find(function(x){return String(x.number)===String(inv.number)});if(!live)return;if(isPaid(live)){if(!manual(live))return;if(!confirm('Mark '+(live.number||'this invoice')+' as unpaid?\n\nThe payment method and paid date will be cleared.'))return;live.status='Unpaid';delete live.paidAt;delete live.paidSource;delete live.paidMethod;delete live.paymentMethod;delete live.paymentDate}else{live.status='Paid';live.paidAt=Date.now();live.paidSource='manual';live.paidMethod=method||'Other';live.paymentMethod=method||'Other';live.paymentDate=new Date().toISOString().slice(0,10)}if(!save(list))return;updateView(live);refresh()}
function squareOwner(){var k=localStorage.getItem(OWNER_KEY)||'';if(!/^[a-f0-9]{64}$/i.test(k)){var a=new Uint8Array(32);crypto.getRandomValues(a);k=Array.from(a).map(function(b){return b.toString(16).padStart(2,'0')}).join('');localStorage.setItem(OWNER_KEY,k)}return k}
function prepareSquare(inv){if(!inv||inv.squareCheckoutUrl)return Promise.resolve(inv);return fetch(CREATE,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({owner_key:squareOwner(),invoice_id:String(inv.id||''),invoice_number:String(inv.number||''),amount_cents:Math.round(Number(inv.total||0)*100),currency:'AUD',name:(inv.businessName||'Tradie Quote Buddy')+' - '+(inv.number||'Invoice')})}).then(function(r){return r.json().then(function(d){return{ok:r.ok,data:d}})}).then(function(x){if(!x.ok||!x.data.checkout_url)throw new Error(x.data&&x.data.error||'Square could not create the payment link.');var list=read(),found=list.find(function(v){return String(v.id)===String(inv.id)});if(found){found.squareCheckoutUrl=x.data.checkout_url;found.squarePaymentLinkId=x.data.payment_link_id||'';found.squareOrderId=x.data.order_id||'';found.squarePaymentLinkCreatedAt=Date.now();save(list);Object.assign(inv,found)}return inv})}
var squareBusy=false;
function squareSend(e){if(squareBusy)return;var b=e.target&&e.target.closest?e.target.closest('#sendInvoiceBtn'):null;if(!b)return;var inv=current();if(!inv||inv.squareCheckoutUrl)return;squareBusy=true;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();var old=b.textContent;b.disabled=true;b.textContent='⏳ Preparing Card Payment…';prepareSquare(inv).then(function(){b.disabled=false;b.textContent=old;squareBusy=false;b.click()}).catch(function(err){b.disabled=false;b.textContent=old;squareBusy=false;alert('We could not prepare the card payment for this invoice.\n\n'+(err&&err.message?err.message:err))})}
function patch(){style();var v=document.getElementById('invoiceView');if(!v)return;layout(v);updateView(current())}
function start(){patch();window.addEventListener('click',squareSend,true);var queued=false;var observer=new MutationObserver(function(){if(queued)return;queued=true;setTimeout(function(){queued=false;patch()},0)});observer.observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
