(function(){
'use strict';
var KEY='tqb_invoices_v1',STYLE='tqb-invoice-delete-style';
function $(id){return document.getElementById(id)}
function read(){try{var x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function save(x){localStorage.setItem(KEY,JSON.stringify(x))}
function addStyles(){if($(STYLE))return;var s=document.createElement('style');s.id=STYLE;s.textContent='.invoice-delete-btn{border:0;border-radius:12px;padding:13px 17px;background:#e53935;color:#fff;font-weight:800;cursor:pointer;font-size:15px;min-height:46px}.invoice-delete-btn:hover{filter:brightness(.95)}.invoice-card-actions{display:flex;gap:8px;margin-top:12px}.invoice-card-actions button{flex:1}';document.head.appendChild(s)}
function getVisibleInvoice(){var view=$('invoiceView');if(!view)return null;var el=view.querySelector('.invoice-meta b');var number=el?(el.textContent||'').trim():'';if(!number){var text=view.textContent||'',m=text.match(/INV-\d{3}/);number=m?m[0]:''}if(!number)return null;var list=read();for(var i=0;i<list.length;i++)if(String(list[i].number||'')===number)return list[i];return null}
function deleteInvoice(id){var list=read(),inv=null;for(var i=0;i<list.length;i++)if(String(list[i].id)===String(id)){inv=list[i];break}if(!inv){alert('Could not find this invoice. Please refresh the app and try again.');return}if(!confirm('Delete invoice '+(inv.number||'')+'?\n\nThis will permanently remove the invoice from this device.'))return;save(list.filter(function(x){return String(x.id)!==String(id)}));var view=$('invoiceView'),invoiceList=$('invoiceList');if(view)view.innerHTML='';if(invoiceList){invoiceList.style.display='grid';if(typeof window.renderList==='function')window.renderList();else renderListFallback()}else if(typeof window.renderList==='function')window.renderList();window.dispatchEvent(new Event('tqb:invoicesChanged'))}
function addDetailDelete(){var view=$('invoiceView'),actions;if(!view)return;actions=view.querySelector('.invoice-actions');if(!actions||actions.querySelector('.invoice-delete-btn'))return;var inv=getVisibleInvoice();if(!inv)return;var b=document.createElement('button');b.type='button';b.className='invoice-delete-btn';b.textContent='🗑️ Delete Invoice';b.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();deleteInvoice(inv.id)});actions.appendChild(b)}
function addCardDeletes(){var cards=document.querySelectorAll('.invoice-card');for(var i=0;i<cards.length;i++){var card=cards[i];if(card.querySelector('.invoice-delete-btn'))continue;var id=card.getAttribute('data-invoice-id');if(!id)continue;var actions=document.createElement('div');actions.className='invoice-card-actions';var b=document.createElement('button');b.type='button';b.className='invoice-delete-btn';b.textContent='🗑️ Delete Invoice';b.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();deleteInvoice(id)});actions.appendChild(b);card.appendChild(actions)}}
function renderListFallback(){var container=$('invoiceList');if(!container)return;var list=read();if(!list.length){container.innerHTML='<div class="empty">No invoices yet.</div>';return}container.innerHTML=list.map(function(inv){return '<div class="invoice-card" data-invoice-id="'+esc(inv.id)+'"><div class="row"><b>'+esc(inv.number||'Invoice')+'</b><b>$'+Number(inv.total||0).toFixed(2)+'</b></div><small>'+esc(inv.customerName||'')+' · '+esc(inv.quoteNumber||'')+' · '+esc(inv.invoiceDate||'')+'</small><div style="margin-top:10px"><span class="invoice-status">'+esc(inv.status||'Unpaid')+'</span></div></div>'}).join('');var cards=container.querySelectorAll('.invoice-card');for(var i=0;i<cards.length;i++){(function(card){card.onclick=function(){var current=read(),id=card.getAttribute('data-invoice-id');var inv=current.find(function(x){return String(x.id)===String(id)});if(typeof window.showInvoice==='function')window.showInvoice(inv)}})(cards[i])}addCardDeletes()}
function esc(v){return String(v==null?'':v).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;')}
function run(){addStyles();addDetailDelete();addCardDeletes()}
function start(){run();setInterval(run,300);document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('.invoice-delete-btn');if(b)e.stopPropagation()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
