(function(){
'use strict';
var INVOICES_KEY='tqb_invoices_v1';
function $(id){return document.getElementById(id)}
function money(v){return new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(Number(v)||0)}
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'})[c]})}
function readInvoices(){try{var x=JSON.parse(localStorage.getItem(INVOICES_KEY)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function saveInvoices(list){localStorage.setItem(INVOICES_KEY,JSON.stringify(list))}
function settings(){try{return JSON.parse(localStorage.getItem('tqb_settings_v6')||'{}')}catch(e){return{}}}
function quotes(){try{var x=JSON.parse(localStorage.getItem('tqb_quotes_v6')||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function saveQuotes(list){localStorage.setItem('tqb_quotes_v6',JSON.stringify(list))}
function findQuoteByNumber(n){var list=quotes();for(var i=0;i<list.length;i++)if(String(list[i].number||'')===String(n||''))return list[i];return null}
function nextInvoiceNumber(){var list=readInvoices(),max=0;list.forEach(function(x){var m=String(x.number||'').match(/^INV-(\d{3})$/);if(m)max=Math.max(max,Number(m[1])||0)});return 'INV-'+String(max+1).padStart(3,'0')}
function datePlus(dateStr,days){var p=String(dateStr||'').split('/'),d;if(p.length===3)d=new Date(Number(p[2]),Number(p[1])-1,Number(p[0]));else d=new Date(dateStr);if(isNaN(d.getTime()))d=new Date();d.setDate(d.getDate()+Number(days||0));return d.toLocaleDateString('en-AU')}
function getCurrentQuote(){var preview=$('quotePreview');if(!preview)return null;var n=preview.querySelector('.paper-meta b'),num=n?(n.textContent||'').trim():'';return findQuoteByNumber(num)}
function isAccepted(q){var s=String(q&& (q.status||q.quoteStatus)||'').toLowerCase();return s.indexOf('accept')>=0}
function markConverted(q,inv){var list=quotes();for(var i=0;i<list.length;i++)if(String(list[i].id)===String(q.id)){list[i].status='Accepted';list[i].quoteStatus='Accepted';list[i].invoiceId=inv.id;list[i].invoiceNumber=inv.number;list[i].convertedToInvoiceAt=Date.now();break}saveQuotes(list)}
function updateConvertButton(){var b=$('convertInvoiceBtn');if(!b)return;var q=getCurrentQuote();if(!q)return;b.disabled=!isAccepted(q);b.title=isAccepted(q)?'Convert this accepted quote to an invoice':'Only accepted quotes can be converted to an invoice';b.textContent=isAccepted(q)?'🧾 Convert to Invoice':'🧾 Awaiting Customer Acceptance';b.style.opacity=isAccepted(q)?'1':'0.55';b.style.cursor=isAccepted(q)?'pointer':'not-allowed'}
function convert(q){if(!q)return;if(!isAccepted(q)){alert('This quote must be accepted by the customer before it can be converted to an invoice.');return}var existing=readInvoices().find(function(x){return String(x.quoteId)===String(q.id)});if(existing){alert(q.number+' has already been converted to '+existing.number+'.');showInvoice(existing);return}if(!confirm('Convert '+q.number+' to an invoice?\n\nThe invoice will include payment terms.'))return;var s=settings(),days=Math.max(0,Number(q.paymentTermsDays)||7),issued=new Date().toLocaleDateString('en-AU');var inv={id:String(Date.now())+'-'+Math.random().toString(16).slice(2),number:nextInvoiceNumber(),quoteId:q.id,quoteNumber:q.number,status:'Unpaid',invoiceDate:issued,dueDate:datePlus(issued,days),paymentTermsDays:days,businessName:s.businessName||'Your Business Name',abn:s.abn||'',businessPhone:s.businessPhone||'',businessEmail:s.businessEmail||'',businessAddress:s.businessAddress||'',customerName:q.customerName||'',customerPhone:q.customerPhone||'',customerEmail:q.customerEmail||'',customerAddress:q.customerAddress||'',jobDescription:q.jobDescription||'',items:Array.isArray(q.items)?q.items.map(function(x){return Object.assign({},x)}):[],labourHours:Number(q.labourHours)||0,hourlyRate:Number(q.hourlyRate)||0,labour:Number(q.labour)||0,subtotal:Number(q.subtotal)||0,discount:Number(q.discount)||0,gst:Number(q.gst)||0,total:Number(q.total)||0,createdAt:Date.now()};var list=readInvoices();list.unshift(inv);saveInvoices(list);markConverted(q,inv);alert('Invoice '+inv.number+' created from '+q.number+'.');showInvoice(inv)}
function addStyles(){if($('tqb-invoice-style'))return;var s=document.createElement('style');s.id='tqb-invoice-style';s.textContent=`#invoices .invoice-list{display:grid;gap:12px;max-width:1100px}.invoice-card{background:#fff;border:1px solid #e6eaf0;border-radius:14px;padding:18px;box-shadow:0 3px 14px #1720330b;cursor:pointer}.invoice-card:hover{background:#fafcff}.invoice-card .row{display:flex;justify-content:space-between;gap:12px}.invoice-card small{display:block;color:#667085;margin-top:5px}.invoice-status{display:inline-block;padding:5px 11px;border-radius:999px;background:#fff2cf;color:#8a5a00;font-size:12px;font-weight:800}.invoice-paper{background:#fff;max-width:850px;margin:0 auto;padding:38px;border-radius:10px;box-shadow:0 3px 18px #17203312}.invoice-paper-head{display:flex;justify-content:space-between;gap:25px;border-bottom:2px solid #172033;padding-bottom:20px}.invoice-paper h1{margin:0 0 7px;font-size:27px}.invoice-paper h2{margin:0 0 8px;font-size:27px}.invoice-meta{text-align:right}.invoice-meta b{font-size:17px}.invoice-block{margin-top:24px;line-height:1.5}.invoice-table{width:100%;border-collapse:collapse;margin-top:22px}.invoice-table th,.invoice-table td{padding:10px 8px;border-bottom:1px solid #e5e7eb;text-align:left}.invoice-table th:not(:first-child),.invoice-table td:not(:first-child){text-align:right}.invoice-totals{width:300px;margin:20px 0 0 auto}.invoice-totals div{display:flex;justify-content:space-between;padding:6px 0}.invoice-totals .grand{border-top:2px solid #172033;font-size:20px;font-weight:800;margin-top:4px;padding-top:12px}.invoice-payment{margin-top:28px;padding:18px;border:1px solid #e5e7eb;border-radius:12px;background:#f8fafc}.invoice-actions{display:flex;gap:10px;max-width:850px;margin:0 auto 14px}.invoice-actions button{flex:1}.invoice-note{color:#667085;font-size:12px;margin-top:16px}@media(max-width:600px){.invoice-paper{padding:20px}.invoice-paper-head{flex-direction:column}.invoice-meta{text-align:left}.invoice-totals{width:100%}}@media print{body{background:#fff!important;padding:0!important}.topbar,.bottom-nav,.section-head,.invoice-actions{display:none!important}.screen#invoices{display:block!important;padding:0}.invoice-paper{box-shadow:none;border-radius:0;max-width:none}}`;document.head.appendChild(s)}
function ensureScreen(){if($('invoices'))return;var main=document.querySelector('main');if(!main)return;var sec=document.createElement('section');sec.id='invoices';sec.className='screen';sec.innerHTML='<div class="section-head"><button class="back-btn" data-back>← Back</button><h2>Invoices</h2><button class="text-btn" id="invoiceRefresh">Refresh</button></div><div id="invoiceList" class="invoice-list"></div><div id="invoiceView"></div>';main.appendChild(sec)}
function ensureNav(){var nav=document.querySelector('.bottom-nav');if(!nav)return;var b=nav.querySelector('[data-screen="invoices"]');if(!b){b=document.createElement('button');b.className='nav';b.setAttribute('data-screen','invoices');b.innerHTML='🧾<span>Invoices</span>'}var home=nav.querySelector('[data-screen="dashboard"]'),newQ=nav.querySelector('[data-screen="quoteForm"]'),saved=nav.querySelector('[data-screen="saved"]'),settingsNav=nav.querySelector('[data-screen="settings"]');[home,newQ,saved,b,settingsNav].forEach(function(x){if(x)nav.appendChild(x)})}
function activateInvoices(){ensureScreen();document.querySelectorAll('.screen').forEach(function(x){x.classList.toggle('active',x.id==='invoices')});document.querySelectorAll('.nav').forEach(function(x){x.classList.toggle('active',x.getAttribute('data-screen')==='invoices')});window.scrollTo(0,0);renderList()}
function addConvertButton(){var actions=$('editQuoteBtn')&&$('editQuoteBtn').parentElement;if(!actions||$('convertInvoiceBtn'))return;var b=document.createElement('button');b.type='button';b.className='primary';b.id='convertInvoiceBtn';b.textContent='🧾 Convert to Invoice';actions.appendChild(b);b.addEventListener('click',function(){convert(getCurrentQuote())});updateConvertButton()}
function renderList(){var el=$('invoiceList');if(!el)return;var list=readInvoices();if(!list.length){el.innerHTML='<div class="empty">No invoices yet.<br><br>Open an accepted quote and tap <b>Convert to Invoice</b>.</div>';return}el.innerHTML=list.map(function(x){return '<div class="invoice-card" data-invoice-id="'+esc(x.id)+'"><div class="row"><b>'+esc(x.number)+'</b><b>'+money(x.total)+'</b></div><small>'+esc(x.customerName)+' · '+esc(x.quoteNumber||'')+' · '+esc(x.invoiceDate)+'</small><div style="margin-top:10px"><span class="invoice-status">'+esc(x.status)+'</span></div></div>'}).join('');el.querySelectorAll('.invoice-card').forEach(function(card){card.onclick=function(){var list=readInvoices(),id=this.getAttribute('data-invoice-id');showInvoice(list.find(function(x){return String(x.id)===String(id)}))}})}
function showInvoice(inv){if(!inv)return;ensureScreen();var view=$('invoiceView'),list=$('invoiceList');if(list)list.style.display='none';view.innerHTML='<div class="invoice-actions"><button class="secondary" id="invoiceBackList">← Invoices</button><button class="primary" id="printInvoice">📄 Print / Save PDF</button></div><div class="invoice-paper"><div class="invoice-paper-head"><div><h1>'+esc(inv.businessName)+'</h1><div>'+esc(inv.businessAddress)+'</div><div>'+esc(inv.businessPhone)+'</div><div>'+esc(inv.businessEmail)+'</div>'+(inv.abn?'<div>ABN '+esc(inv.abn)+'</div>':'')+'</div><div class="invoice-meta"><h2>INVOICE</h2><b>'+esc(inv.number)+'</b><div>Issued: '+esc(inv.invoiceDate)+'</div><div>Due: '+esc(inv.dueDate)+'</div><div style="margin-top:8px"><span class="invoice-status">'+esc(inv.status)+'</span></div></div></div><div class="invoice-block"><b>Bill to</b><br>'+esc(inv.customerName)+'<br>'+esc(inv.customerPhone)+'<br>'+esc(inv.customerEmail)+'<br>'+esc(inv.customerAddress).replace(/\n/g,'<br>')+'</div><div class="invoice-block"><b>Job</b><br>'+esc(inv.jobDescription).replace(/\n/g,'<br>')+'</div><table class="invoice-table"><thead><tr><th>Description</th><th>Qty</th><th>Unit price</th><th>Amount</th></tr></thead><tbody>'+(inv.items||[]).map(function(item){var qty=item.qty==null?1:Number(item.qty)||0,unit=item.unitPrice==null?Number(item.amount)||0:Number(item.unitPrice)||0;return '<tr><td>'+esc(item.description)+'</td><td>'+qty+'</td><td>'+money(unit)+'</td><td>'+money(qty*unit)+'</td></tr>'}).join('')+(inv.labourHours?'<tr><td>Labour</td><td>'+inv.labourHours+' hrs</td><td>'+money(inv.hourlyRate)+'/hr</td><td>'+money(inv.labour)+'</td></tr>':'')+'</tbody></table><div class="invoice-totals"><div><span>Subtotal</span><span>'+money(inv.subtotal)+'</span></div>'+(inv.discount>0?'<div><span>Discount</span><span>-'+money(inv.discount)+'</span></div>':'')+'<div><span>GST</span><span>'+money(inv.gst)+'</span></div><div class="grand"><span>Total due</span><span>'+money(inv.total)+'</span></div></div><div class="invoice-payment"><b>Payment terms</b><br>Payment due within '+esc(inv.paymentTermsDays)+' days, by '+esc(inv.dueDate)+'.<div class="invoice-note">Thanks for your business.</div></div></div>';$('invoiceBackList').onclick=function(){view.innerHTML='';list.style.display='grid';renderList()};$('printInvoice').onclick=function(){window.print()}}
function start(){addStyles();ensureScreen();ensureNav();addConvertButton();var p=$('quotePreview');if(p)new MutationObserver(function(){setTimeout(function(){addConvertButton();updateConvertButton()},0)}).observe(p,{childList:true,subtree:true});document.addEventListener('click',function(e){var nav=e.target.closest&&e.target.closest('[data-screen="invoices"]');if(nav){e.preventDefault();e.stopPropagation();activateInvoices()}var ref=e.target.closest&&e.target.closest('#invoiceRefresh');if(ref)renderList()});setInterval(updateConvertButton,2000);renderList()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
