(function(){
'use strict';
var KEY='tqb_invoices_v1',STYLE='tqb-invoice-delete-style';
function $(id){return document.getElementById(id)}
function read(){try{var x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function save(x){localStorage.setItem(KEY,JSON.stringify(x))}
function addStyles(){if($(STYLE))return;var s=document.createElement('style');s.id=STYLE;s.textContent='.invoice-delete-btn{border:0;border-radius:10px;padding:13px 17px;background:#e53935;color:#fff;font-weight:800;cursor:pointer;font-size:15px;min-height:46px}.invoice-card-actions{display:flex;gap:8px;margin-top:12px}.invoice-card-actions button{flex:1}.invoice-delete-btn:hover{filter:brightness(.95)}';document.head.appendChild(s)}
function deleteInvoice(id){var list=read(),inv=null;for(var i=0;i<list.length;i++)if(String(list[i].id)===String(id)){inv=list[i];break}if(!inv){alert('Could not find this invoice. Please refresh and try again.');return}if(!confirm('Delete invoice '+(inv.number||'')+'?\n\nThis will permanently remove the invoice from this device.'))return;save(list.filter(function(x){return String(x.id)!==String(id)}));var view=$('invoiceView'),invoiceList=$('invoiceList');if(view)view.innerHTML='';if(invoiceList){invoiceList.style.display='grid';}if(typeof window.renderList==='function')window.renderList();else location.reload()}
function addToCards(){var cards=document.querySelectorAll('.invoice-card');for(var i=0;i<cards.length;i++){var card=cards[i];if(card.querySelector('.invoice-delete-btn'))continue;var id=card.getAttribute('data-invoice-id');if(!id)continue;var actions=document.createElement('div');actions.className='invoice-card-actions';var b=document.createElement('button');b.type='button';b.className='invoice-delete-btn';b.textContent='🗑️ Delete Invoice';b.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();deleteInvoice(this.parentElement.parentElement.getAttribute('data-invoice-id'))});actions.appendChild(b);card.appendChild(actions)}}
function addToDetail(){var view=$('invoiceView');if(!view||view.querySelector('#deleteInvoiceBtn'))return;var actions=view.querySelector('.invoice-actions');if(!actions)return;var paper=view.querySelector('.invoice-paper'),numberEl=paper&&paper.querySelector('.invoice-meta b'),number=numberEl?(numberEl.textContent||'').trim():'';var list=read(),id=null;for(var i=0;i<list.length;i++){if(String(list[i].number||'')===number){id=list[i].id;break}}if(!id)return;var b=document.createElement('button');b.type='button';b.id='deleteInvoiceBtn';b.className='invoice-delete-btn';b.textContent='🗑️ Delete Invoice';b.addEventListener('click',function(){deleteInvoice(id)});actions.appendChild(b)}
function run(){addStyles();addToCards();addToDetail()}
function start(){var observer=new MutationObserver(function(){window.requestAnimationFrame(run)});observer.observe(document.body,{childList:true,subtree:true});run()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
