(function(){
'use strict';
var KEY='tqb_invoices_v1';
function read(){try{var x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function save(x){localStorage.setItem(KEY,JSON.stringify(x))}
function currentId(){var view=document.getElementById('invoiceView');if(!view)return null;var no=view.querySelector('.invoice-meta b');if(!no)return null;var n=(no.textContent||'').trim();var list=read();var inv=list.find(function(x){return String(x.number)===n});return inv?inv.id:null}
function updateStatus(inv){var view=document.getElementById('invoiceView');if(!view)return;view.querySelectorAll('.invoice-status').forEach(function(el){el.textContent=inv.status});var actions=view.querySelector('.invoice-actions');if(actions){var b=actions.querySelector('#markPaidBtn');if(inv.status==='Paid'){if(b){b.textContent='✓ Paid';b.disabled=true;b.style.opacity='.7'}var existing=view.querySelector('#paidDateNote');if(!existing){existing=document.createElement('div');existing.id='paidDateNote';existing.style.cssText='max-width:850px;margin:0 auto 12px;padding:10px 14px;border-radius:10px;background:#ecfdf3;color:#166534;font-weight:700;font-size:13px';existing.textContent='Paid on '+new Date(inv.paidAt||Date.now()).toLocaleDateString('en-AU');actions.parentNode.insertBefore(existing,actions.nextSibling)}}else if(b){b.textContent='💰 Mark as Paid';b.disabled=false;b.style.opacity='1'}}}
function addPaidButton(){var view=document.getElementById('invoiceView');if(!view)return;var actions=view.querySelector('.invoice-actions');if(!actions||actions.querySelector('#markPaidBtn'))return;var id=currentId();if(!id)return;var inv=read().find(function(x){return String(x.id)===String(id)});if(!inv)return;var b=document.createElement('button');b.className='primary';b.id='markPaidBtn';b.textContent=inv.status==='Paid'?'✓ Paid':'💰 Mark as Paid';b.disabled=inv.status==='Paid';b.style.opacity=inv.status==='Paid'?'.7':'1';actions.insertBefore(b,actions.querySelector('#sendInvoiceBtn')||actions.firstChild);b.onclick=function(){var list=read(),found=list.find(function(x){return String(x.id)===String(id)});if(!found||found.status==='Paid')return;if(!confirm('Mark '+found.number+' as paid?'))return;found.status='Paid';found.paidAt=Date.now();save(list);updateStatus(found)};updateStatus(inv)}
function deleteInvoice(id){var list=read(),inv=list.find(function(x){return String(x.id)===String(id)});if(!inv){alert('Could not find this invoice. Please refresh and try again.');return}if(!confirm('Delete invoice '+inv.number+'?\n\nThis will permanently remove the invoice from this device.'))return;save(list.filter(function(x){return String(x.id)!==String(id)}));var view=document.getElementById('invoiceView'),listEl=document.getElementById('invoiceList');if(view)view.innerHTML='';if(listEl){listEl.style.display='grid';listEl.innerHTML=''}location.reload()}
function addDeleteButton(){var view=document.getElementById('invoiceView');if(!view)return;var actions=view.querySelector('.invoice-actions');if(!actions||actions.querySelector('#deleteInvoiceBtn'))return;var id=currentId();if(!id)return;var b=document.createElement('button');b.type='button';b.id='deleteInvoiceBtn';b.className='danger';b.textContent='🗑️ Delete Invoice';b.onclick=function(){deleteInvoice(id)};actions.appendChild(b)}
function addListDeleteButtons(){var cards=document.querySelectorAll('.invoice-card');for(var i=0;i<cards.length;i++){var card=cards[i];if(card.querySelector('.invoice-delete-list-btn'))continue;var id=card.getAttribute('data-invoice-id');if(!id)continue;var b=document.createElement('button');b.type='button';b.className='secondary invoice-delete-list-btn';b.textContent='🗑️ Delete Invoice';b.style.cssText='margin-top:12px;width:100%;color:#c62828;font-weight:800';b.onclick=function(e){e.preventDefault();e.stopPropagation();deleteInvoice(this.parentElement.getAttribute('data-invoice-id'))};card.appendChild(b)}}
function watch(){var observer=new MutationObserver(function(){setTimeout(function(){addPaidButton();addDeleteButton();addListDeleteButtons()},0)});observer.observe(document.body,{childList:true,subtree:true});addPaidButton();addDeleteButton();addListDeleteButtons()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',watch);else watch();
})();