(function(){
'use strict';
var KEY='tqb_invoices_v1',STYLE='tqb-invoice-delete-style';
function $(id){return document.getElementById(id)}
function read(){try{var x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function addStyles(){if($(STYLE))return;var s=document.createElement('style');s.id=STYLE;s.textContent='.invoice-delete-btn{border:0;border-radius:12px;padding:13px 17px;background:#e53935;color:#fff;font-weight:800;cursor:pointer;font-size:15px;min-height:46px}.invoice-delete-btn:hover{filter:brightness(.95)}#invoiceList .invoice-card-actions{display:none!important}';document.head.appendChild(s)}
function getVisibleInvoice(){var view=$('invoiceView');if(!view)return null;var el=view.querySelector('.invoice-meta b');var number=el?(el.textContent||'').trim():'';if(!number){var text=view.textContent||'',m=text.match(/INV-\d{3}/);number=m?m[0]:''}if(!number)return null;var list=read();for(var i=0;i<list.length;i++)if(String(list[i].number||'')===number)return list[i];return null}
function deleteInvoice(id){var list=read(),inv=null;for(var i=0;i<list.length;i++)if(String(list[i].id)===String(id)){inv=list[i];break}if(!inv){alert('Could not find this invoice. Please refresh the app and try again.');return}if(!confirm('Delete invoice '+(inv.number||'')+'?\n\nThis will permanently remove the invoice from this device.'))return;localStorage.setItem(KEY,JSON.stringify(list.filter(function(x){return String(x.id)!==String(id)})));var view=$('invoiceView'),invoiceList=$('invoiceList');if(view)view.innerHTML='';if(invoiceList){invoiceList.style.display='grid';if(typeof window.renderList==='function')window.renderList()}window.dispatchEvent(new Event('tqb:invoicesChanged'))}
function addDetailDelete(){var view=$('invoiceView'),actions;if(!view)return;actions=view.querySelector('.invoice-actions');if(!actions||actions.querySelector('.invoice-delete-btn'))return;var inv=getVisibleInvoice();if(!inv)return;var b=document.createElement('button');b.type='button';b.className='invoice-delete-btn';b.textContent='🗑️ Delete Invoice';b.addEventListener('click',function(e){e.preventDefault();e.stopPropagation();deleteInvoice(inv.id)});actions.appendChild(b)}
function run(){addStyles();addDetailDelete();var list=document.querySelectorAll('#invoiceList .invoice-card-actions');for(var i=0;i<list.length;i++)list[i].remove()}
function start(){run();if(window.MutationObserver){var o=new MutationObserver(function(){addDetailDelete();var list=document.querySelectorAll('#invoiceList .invoice-card-actions');for(var i=0;i<list.length;i++)list[i].remove()});o.observe(document.body,{childList:true,subtree:true})}setInterval(run,1000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();