(function(){
'use strict';
var KEY='tqb_invoices_v1';
function read(){try{var x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function paid(x){return String(x&&x.status||'').toLowerCase()==='paid'}
function invoiceNumber(){var text=document.body?document.body.innerText:'';var m=text.match(/INV-\d+/i);return m?m[0]:''}
function current(){var n=invoiceNumber();if(!n)return null;return read().find(function(x){return String(x.number||'').toUpperCase()===n.toUpperCase()})||null}
function injectStyle(){if(document.getElementById('dusty-invoice-layout'))return;var s=document.createElement('style');s.id='dusty-invoice-layout';s.textContent='.dusty-invoice-actions{display:grid!important;grid-template-columns:1fr 1fr!important;gap:10px!important;width:100%!important;max-width:850px!important;margin:0 auto 14px!important}.dusty-invoice-actions>button{width:100%!important;min-width:0!important;min-height:52px!important;border:0!important;border-radius:12px!important;font-weight:800!important;font-size:15px!important;cursor:pointer!important}.dusty-invoice-actions .dusty-send{grid-column:1/-1!important;background:#ffb000!important;color:#111!important}.dusty-invoice-actions .dusty-paid{background:#16a34a!important;color:#fff!important}.dusty-invoice-actions .dusty-more{grid-column:1/-1!important;background:#eef0f4!important;color:#172033!important}.dusty-more-menu{display:none!important;grid-column:1/-1!important;background:#f7f8fa!important;border-radius:12px!important;padding:8px!important;gap:8px!important}.dusty-more-menu.open{display:grid!important;grid-template-columns:1fr 1fr!important}.dusty-more-menu button{background:#fff!important;color:#172033!important;border:1px solid #ddd!important;width:100%!important;min-width:0!important}.dusty-more-menu .dusty-full{grid-column:1/-1!important}@media(max-width:600px){.dusty-invoice-actions{grid-template-columns:1fr 1fr!important;gap:8px!important}.dusty-more-menu.open{grid-template-columns:1fr!important}.dusty-more-menu button{grid-column:1/-1!important}}';document.head.appendChild(s)}
function buttons(){return Array.from(document.querySelectorAll('button'))}
function find(rx,id){return (id&&document.getElementById(id))||buttons().find(function(b){return rx.test((b.textContent||'').trim())})}
function findBox(send){if(!send)return null;var box=send.closest('.invoice-actions,.action-row');if(box)return box;var p=send.parentElement;while(p&&p!==document.body){if(p.querySelectorAll('button').length>=3)return p;p=p.parentElement}return null}
function moveSquare(menu){if(!menu)return;var b=buttons().find(function(x){var t=(x.textContent||'').trim();return /pay by square|set up pay by square|square payment/i.test(t) && !menu.contains(x)});if(b){b.classList.add('dusty-full');menu.appendChild(b)}}
function layout(){injectStyle();var send=find(/^\s*(📧\s*)?send invoice\b/i,'sendInvoiceBtn');if(!send)return;var box=findBox(send);if(!box)return;box.classList.add('dusty-invoice-actions');send.classList.add('dusty-send');send.type='button';var paidBtn=find(/mark as paid|mark paid|mark as unpaid|↩/i,'markPaidBtn');if(paidBtn&&box.contains(paidBtn)){paidBtn.classList.add('dusty-paid');paidBtn.type='button';paidBtn.disabled=false;paidBtn.style.pointerEvents='auto'}var more=box.querySelector('.dusty-more');if(!more){more=document.createElement('button');more.type='button';more.className='dusty-more';more.textContent='••• More';box.appendChild(more)}var menu=box.querySelector('.dusty-more-menu');if(!menu){menu=document.createElement('div');menu.className='dusty-more-menu';box.appendChild(menu)}Array.from(box.children).forEach(function(el){if(el.tagName==='BUTTON'&&el!==send&&el!==paidBtn&&el!==more&&!menu.contains(el))menu.appendChild(el)});moveSquare(menu);more.onclick=function(e){e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();menu.classList.toggle('open');more.textContent=menu.classList.contains('open')?'✕ Less':'••• More'};updateStatus()}
function updateStatus(){var inv=current();if(!inv)return;document.querySelectorAll('.invoice-status').forEach(function(s){s.textContent=inv.status||'Unpaid';s.setAttribute('aria-label',inv.status||'Unpaid')});var b=document.getElementById('markPaidBtn');if(b){b.textContent=paid(inv)?'↩ Mark as Unpaid':'💰 Mark as Paid';b.disabled=false;b.style.pointerEvents='auto'}}
function togglePaid(e){var b=e.target&&e.target.closest?e.target.closest('#markPaidBtn'):null;if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();var inv=current();if(!inv)return;var list=read(),x=list.find(function(i){return String(i.number||'').toUpperCase()===String(inv.number||'').toUpperCase()});if(!x)return;if(paid(x)){x.status='Unpaid';delete x.paidAt;delete x.paidSource;delete x.paidMethod}else{x.status='Paid';x.paidAt=Date.now();x.paidSource='manual';x.paidMethod='Manual payment'}localStorage.setItem(KEY,JSON.stringify(list));updateStatus();if(typeof window.renderList==='function')window.renderList();if(typeof window.refreshTQBDashboard==='function')window.refreshTQBDashboard()}
function start(){injectStyle();layout();new MutationObserver(function(){layout()}).observe(document.body,{childList:true,subtree:true});setInterval(layout,1000)}
document.addEventListener('click',togglePaid,true);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();