(function(){
'use strict';
var KEY='tqb_invoices_v1';
function read(){try{var x=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function save(x){try{localStorage.setItem(KEY,JSON.stringify(x))}catch(e){}}
function dateOnly(v){var s=String(v||'').trim(),m=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})$/);if(m)return new Date(Number(m[3]),Number(m[2])-1,Number(m[1]));var d=new Date(s);return isNaN(d.getTime())?null:new Date(d.getFullYear(),d.getMonth(),d.getDate())}
function today(){var d=new Date();return new Date(d.getFullYear(),d.getMonth(),d.getDate())}
function daysToDue(inv){var d=dateOnly(inv&&inv.dueDate);if(!d)return null;return Math.round((d.getTime()-today().getTime())/86400000)}
function status(inv){if(String(inv&&inv.status||'').toLowerCase()==='paid')return'Paid';var n=daysToDue(inv);if(n===null)return'Unpaid';if(n<0)return'Overdue';if(n===0)return'Due today';if(n<=3)return'Due soon';return'Unpaid'}
function styleBadge(b,s){b.textContent=s;b.removeAttribute('aria-label');b.style.fontWeight='800';b.style.cursor='default';if(s==='Paid'){b.style.background='#ecfdf3';b.style.color='#166534';b.setAttribute('aria-label','Paid')}else if(s==='Overdue'){b.style.background='#fee2e2';b.style.color='#b42318'}else if(s==='Due today'){b.style.background='#ffedd5';b.style.color='#c2410c'}else if(s==='Due soon'){b.style.background='#fff7cc';b.style.color='#8a5a00'}else{b.style.background='#fff2cf';b.style.color='#8a5a00'}}
function addStyles(){if(document.getElementById('tqb-overdue-style'))return;var s=document.createElement('style');s.id='tqb-overdue-style';s.textContent='.tqb-overdue-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:0 0 16px}.tqb-overdue-box{background:#fff;border:1px solid #e6eaf0;border-radius:12px;padding:13px}.tqb-overdue-box span{display:block;color:#667085;font-size:11px}.tqb-overdue-box b{display:block;margin-top:5px;font-size:18px}.tqb-overdue-box.overdue{border-color:#fecaca}.tqb-overdue-box.today{border-color:#fed7aa}.tqb-overdue-box.soon{border-color:#fde68a}.tqb-overdue-box.paid{border-color:#bbf7d0}.tqb-overdue-note{margin-top:6px;font-size:12px;color:#667085}.tqb-customer-overdue{margin-top:10px;color:#b42318;font-weight:800;font-size:12px}.tqb-history-status{display:inline-block;margin-left:6px;padding:3px 7px;border-radius:999px;font-size:10px;font-weight:800}.tqb-history-status.overdue{background:#fee2e2;color:#b42318}.tqb-history-status.today{background:#ffedd5;color:#c2410c}.tqb-history-status.soon{background:#fff7cc;color:#8a5a00}.tqb-history-status.paid{background:#ecfdf3;color:#166534}@media(max-width:650px){.tqb-overdue-summary{grid-template-columns:1fr 1fr}}
';document.head.appendChild(s)}
function normaliseInvoices(){var list=read(),changed=false;list.forEach(function(inv){var s=status(inv),old=inv.tqbDueStatus||'';if(old!==s){inv.tqbDueStatus=s;changed=true}});if(changed)save(list);return list}
function renderSummary(list){var host=document.getElementById('invoiceList');if(!host||!document.getElementById('invoices'))return;var old=document.getElementById('tqb-overdue-summary');if(old)old.remove();var counts={Overdue:0,'Due today':0,'Due soon':0,Paid:0};list.forEach(function(x){var s=status(x);if(counts[s]!=null)counts[s]++});var box=document.createElement('div');box.id='tqb-overdue-summary';box.className='tqb-overdue-summary';box.innerHTML='<div class="tqb-overdue-box overdue"><span>Overdue</span><b>'+counts.Overdue+'</b></div><div class="tqb-overdue-box today"><span>Due today</span><b>'+counts['Due today']+'</b></div><div class="tqb-overdue-box soon"><span>Due soon</span><b>'+counts['Due soon']+'</b></div><div class="tqb-overdue-box paid"><span>Paid</span><b>'+counts.Paid+'</b></div>';host.parentNode.insertBefore(box,host)}
function updateCards(list){var cards=document.querySelectorAll('.invoice-card');for(var i=0;i<cards.length;i++){var card=cards[i],id=card.getAttribute('data-invoice-id'),inv=list.find(function(x){return String(x.id)===String(id)});if(!inv)continue;var badge=card.querySelector('.invoice-status');if(!badge)continue;var s=status(inv);styleBadge(badge,s);var old=card.querySelector('.tqb-overdue-note');if(old)old.remove();if(s!=='Paid'&&s!=='Unpaid'){var note=document.createElement('div');note.className='tqb-overdue-note';note.textContent=s==='Overdue'?'Payment is overdue by '+Math.abs(daysToDue(inv))+' day'+(Math.abs(daysToDue(inv))===1?'':'s'):s==='Due today'?'Payment is due today':'Payment due '+inv.dueDate;badge.parentNode.appendChild(note)}}}
function addCustomerOverdue(){var cards=document.querySelectorAll('.customer-card');if(!cards.length)return;var list=read(),customers;try{customers=JSON.parse(localStorage.getItem('tqb_customers_v1')||'[]')}catch(e){customers=[]}for(var i=0;i<cards.length;i++){var card=cards[i],id=card.getAttribute('data-customer-id'),existing=card.querySelector('.tqb-customer-overdue');if(existing)existing.remove();var c=customers.find(function(x){return String(x.id)===String(id)});if(!c)continue;var invoices=list.filter(function(inv){return String(inv.customerEmail||'').toLowerCase()===String(c.email||'').toLowerCase()||String(inv.customerPhone||'')===String(c.phone||'')||String(inv.customerName||'').trim().toLowerCase()===String(c.name||'').trim().toLowerCase()});var overdue=invoices.filter(function(inv){return status(inv)==='Overdue'}).reduce(function(a,x){return a+(Number(x.total)||0)},0);if(overdue>0){var n=document.createElement('div');n.className='tqb-customer-overdue';n.textContent='🔴 Overdue: '+new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(overdue);card.appendChild(n)}}}
function updateCustomerHistory(list){var rows=document.querySelectorAll('.customer-record');for(var i=0;i<rows.length;i++){var row=rows[i],bold=row.querySelector('b');if(!bold)continue;var text=(bold.textContent||''),m=text.match(/INV-\d+/);if(!m)continue;var inv=list.find(function(x){return String(x.number)===m[0]});if(!inv)continue;var s=status(inv),old=row.querySelector('.tqb-history-status');if(old)old.remove();if(s==='Overdue'||s==='Due today'||s==='Due soon'||s==='Paid'){var span=document.createElement('span');span.className='tqb-history-status '+(s==='Overdue'?'overdue':s==='Due today'?'today':s==='Due soon'?'soon':'paid');span.textContent=s;bold.parentNode.appendChild(span)}}}
function run(){addStyles();var list=normaliseInvoices();renderSummary(list);updateCards(list);addCustomerOverdue();updateCustomerHistory(list)}
function start(){run();setInterval(run,15000);window.addEventListener('focus',run);document.addEventListener('click',function(e){if(e.target.closest&&e.target.closest('[data-screen="invoices"], [data-screen="customers"]'))setTimeout(run,300)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
