(function(){
'use strict';
var QKEY='tqb_quotes_v6',SKEY='tqb_settings_v6',DEFAULT_VALIDITY=30,DEFAULT_TERMS=7;
function read(k,f){try{var r=localStorage.getItem(k);return r?JSON.parse(r):f;}catch(e){return f;}}
function write(q,s){try{localStorage.setItem(QKEY,JSON.stringify(q));localStorage.setItem(SKEY,JSON.stringify(s));}catch(e){}}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c];});}
function datePlus(dateStr,days){var p=String(dateStr||'').split('/'),d;if(p.length===3)d=new Date(Number(p[2]),Number(p[1])-1,Number(p[0]));else d=new Date(dateStr);if(isNaN(d.getTime()))d=new Date();d.setDate(d.getDate()+Number(days||0));return d.toLocaleDateString('en-AU');}
function addFields(){var form=document.getElementById('quoteFormEl');if(!form||document.getElementById('quoteTermsRow'))return;var h=document.createElement('h3');h.textContent='Quote terms';var row=document.createElement('div');row.className='grid2';row.id='quoteTermsRow';row.innerHTML='<label>Quote valid for (days)<input id="validityDays" type="number" min="1" step="1" value="'+DEFAULT_VALIDITY+'"></label><label>Payment due within (days)<input id="paymentTermsDays" type="number" min="0" step="1" value="'+DEFAULT_TERMS+'"></label>';var gst=document.getElementById('gstEnabled');gst.parentNode.parentNode.insertBefore(h,gst.parentNode);gst.parentNode.parentNode.insertBefore(row,gst.parentNode);}
function defaults(){var a=document.getElementById('validityDays'),b=document.getElementById('paymentTermsDays');if(a)a.value=DEFAULT_VALIDITY;if(b)b.value=DEFAULT_TERMS;}
function setForQuote(q){var a=document.getElementById('validityDays'),b=document.getElementById('paymentTermsDays');if(a)a.value=q&&q.validityDays!=null?q.validityDays:DEFAULT_VALIDITY;if(b)b.value=q&&q.paymentTermsDays!=null?q.paymentTermsDays:DEFAULT_TERMS;}
function enhancePreview(){var paper=document.getElementById('quotePreview');if(!paper)return;var meta=paper.querySelector('.paper-meta b'),number=meta?meta.textContent:'';var quotes=read(QKEY,[]),q=null,i;for(i=0;i<quotes.length;i++)if(String(quotes[i].number)===String(number)){q=quotes[i];break;}if(!q)return;var old=paper.querySelector('.terms-block');if(old)old.remove();var block=document.createElement('div');block.className='terms-block';var validity=q.validityDays==null?DEFAULT_VALIDITY:Number(q.validityDays),payment=q.paymentTermsDays==null?DEFAULT_TERMS:Number(q.paymentTermsDays);block.innerHTML='<div><b>Quote validity</b><br>Valid until '+esc(datePlus(q.date,validity))+' ('+validity+' days)</div><div><b>Payment terms</b><br>Payment due within '+payment+' days</div>';var thanks=paper.querySelector('.thanks');if(thanks)paper.insertBefore(block,thanks);else paper.appendChild(block);}
function captureSavedQuote(){setTimeout(function(){var quotes=read(QKEY,[]);if(!quotes.length)return;var q=quotes[0],a=document.getElementById('validityDays'),b=document.getElementById('paymentTermsDays');for(var i=1;i<quotes.length;i++)if((Number(quotes[i].savedAt)||0)>(Number(q.savedAt)||0))q=quotes[i];q.validityDays=Math.max(1,Number(a&&a.value)||DEFAULT_VALIDITY);q.paymentTermsDays=Math.max(0,Number(b&&b.value)||DEFAULT_TERMS);write(quotes,read(SKEY,{}));enhancePreview();},0);}
function init(){addFields();defaults();var form=document.getElementById('quoteFormEl');if(form)form.addEventListener('submit',captureSavedQuote);var newBtn=document.getElementById('newQuoteBtn');if(newBtn)newBtn.addEventListener('click',function(){setTimeout(defaults,0);});var navs=document.querySelectorAll('.nav'),i;for(i=0;i<navs.length;i++)if(navs[i].getAttribute('data-screen')==='quoteForm')navs[i].addEventListener('click',function(){setTimeout(defaults,0);});var edit=document.getElementById('editQuoteBtn');if(edit)edit.addEventListener('click',function(){var paper=document.getElementById('quotePreview'),meta=paper.querySelector('.paper-meta b'),n=meta?meta.textContent:'';setTimeout(function(){var qs=read(QKEY,[]);for(var j=0;j<qs.length;j++)if(String(qs[j].number)===String(n)){setForQuote(qs[j]);break;}},0);});document.addEventListener('click',function(e){var card=e.target.closest?e.target.closest('.quote-card'):null;if(card)setTimeout(enhancePreview,50);});setTimeout(enhancePreview,500);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
