(function(){
'use strict';
var ENDPOINT='https://cychngcvhgtfuahavlqq.supabase.co/functions/v1/create-quote-pdf';
var QUOTES_KEY='tqb_quotes_v6';
var INVOICES_KEY='tqb_invoices_v1';
function readQuotes(){try{var q=JSON.parse(localStorage.getItem(QUOTES_KEY)||'[]');return Array.isArray(q)?q:[]}catch(e){return[]}}
function saveQuotes(q){try{localStorage.setItem(QUOTES_KEY,JSON.stringify(q))}catch(e){}}
function readInvoices(){try{var q=JSON.parse(localStorage.getItem(INVOICES_KEY)||'[]');return Array.isArray(q)?q:[]}catch(e){return[]}}
function saveInvoices(q){try{localStorage.setItem(INVOICES_KEY,JSON.stringify(q))}catch(e){}}
function settings(){try{return JSON.parse(localStorage.getItem('tqb_settings_v6')||'{}')}catch(e){return{}}}
function statusText(q){var s=String(q.status||q.quoteStatus||'').toLowerCase();if(s.indexOf('accept')>=0)return'Accepted';if(s.indexOf('declin')>=0||s.indexOf('reject')>=0)return'Declined';return'Pending'}
function datePlus(dateStr,days){var p=String(dateStr||'').split('/'),d;if(p.length===3)d=new Date(Number(p[2]),Number(p[1])-1,Number(p[0]));else d=new Date(dateStr);if(isNaN(d.getTime()))d=new Date();d.setDate(d.getDate()+Number(days||0));return d.toLocaleDateString('en-AU')}
function nextInvoiceNumber(){var list=readInvoices(),max=0;list.forEach(function(x){var m=String(x.number||'').match(/^INV-(\d{3})$/);if(m)max=Math.max(max,Number(m[1])||0)});return'INV-'+String(max+1).padStart(3,'0')}
function bankFromSettings(){var s=settings();return{bankName:s.bankName||'',bankAccountName:s.bankAccountName||'',bankBsb:s.bankBsb||'',bankAccountNumber:s.bankAccountNumber||'',bankPayId:s.bankPayId||'',bankReference:s.bankReference||'Use invoice number as reference'}}
function findInvoice(q){var list=readInvoices();for(var i=0;i<list.length;i++)if(String(list[i].quoteId)===String(q.id)||String(list[i].quoteNumber)===String(q.number))return list[i];return null}
function convertAcceptedQuote(q){if(!q||statusText(q)!=='Accepted'||!q.id||!q.number)return null;var existing=findInvoice(q);if(existing)return existing;var s=settings(),bank=bankFromSettings(),days=Math.max(0,Number(q.paymentTermsDays)||7),issued=new Date().toLocaleDateString('en-AU');var inv={id:String(Date.now())+'-'+Math.random().toString(16).slice(2),number:nextInvoiceNumber(),quoteId:q.id,quoteNumber:q.number,status:'Unpaid',invoiceDate:issued,dueDate:datePlus(issued,days),paymentTermsDays:days,businessName:s.businessName||'Your Business Name',abn:s.abn||'',businessPhone:s.businessPhone||'',businessEmail:s.businessEmail||'',businessAddress:s.businessAddress||'',bankName:bank.bankName,bankAccountName:bank.bankAccountName,bankBsb:bank.bankBsb,bankAccountNumber:bank.bankAccountNumber,bankPayId:bank.bankPayId,bankReference:bank.bankReference,customerName:q.customerName||'',customerPhone:q.customerPhone||'',customerEmail:q.customerEmail||'',customerAddress:q.customerAddress||'',jobDescription:q.jobDescription||'',items:Array.isArray(q.items)?q.items.map(function(x){return Object.assign({},x)}):[],labourHours:Number(q.labourHours)||0,hourlyRate:Number(q.hourlyRate)||0,labour:Number(q.labour)||0,subtotal:Number(q.subtotal)||0,discount:Number(q.discount)||0,total:Number(q.total)||0,gst:Number(q.gst)||0,createdAt:Date.now()};var list=readInvoices();list.unshift(inv);saveInvoices(list);return inv}
function updatePreview(q){var p=document.getElementById('quotePreview');if(!p||!window.currentQuote||String(window.currentQuote.id)!==String(q.id))return;var el=p.querySelector('.tqb-live-status');if(!el){el=document.createElement('div');el.className='tqb-live-status';p.appendChild(el)}var st=statusText(q);el.textContent='Customer response: '+st;el.style.cssText='margin-top:18px;padding:10px 14px;border-radius:10px;font-weight:700;text-align:center;background:'+(st==='Accepted'?'#dff5e8':st==='Declined'?'#fde1e2':'#e6f0ff')+';color:'+(st==='Accepted'?'#148043':st==='Declined'?'#d92d20':'#1769c2')+';'}
function refreshDashboard(){if(typeof window.refreshTQBDashboard==='function')window.refreshTQBDashboard()}
function checkQuote(q,quoteList,index){if(!q.responseToken||!q.number)return Promise.resolve(false);var url=ENDPOINT+'?quoteNumber='+encodeURIComponent(q.number)+'&responseToken='+encodeURIComponent(q.responseToken);return fetch(url,{cache:'no-store'}).then(function(r){if(!r.ok)return null;return r.json()}).then(function(data){var decision=String(data&&data.decision||'').trim();if(decision!=='Accepted'&&decision!=='Declined')return false;var old=statusText(q);q.status=decision;q.quoteStatus=decision;q.respondedAt=data.responded_at||q.respondedAt||new Date().toISOString();if(decision==='Accepted'){var inv=convertAcceptedQuote(q);if(inv){q.invoiceId=inv.id;q.invoiceNumber=inv.number;q.convertedToInvoiceAt=q.convertedToInvoiceAt||Date.now();if(window.currentQuote&&String(window.currentQuote.id)===String(q.id))window.currentQuote=q;quoteList.splice(index,1);saveQuotes(quoteList);refreshDashboard();if(window.currentQuote&&String(window.currentQuote.id)===String(q.id)){updatePreview(q)}return true}}quoteList[index]=q;saveQuotes(quoteList);if(window.currentQuote&&String(window.currentQuote.id)===String(q.id))window.currentQuote=q;updatePreview(q);refreshDashboard();return old!==decision}).catch(function(){return false})}
function sync(){var quoteList=readQuotes(),jobs=[];for(var i=0;i<quoteList.length;i++)if(quoteList[i].responseToken)jobs.push(checkQuote(quoteList[i],quoteList,i));return Promise.all(jobs)}
function start(){sync();setInterval(sync,15000);document.addEventListener('click',function(e){if(e.target.closest&&e.target.closest('.nav'))setTimeout(sync,250);});window.addEventListener('focus',sync)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
