(function(){
'use strict';
var ENDPOINT='https://cychngcvhgtfuahavlqq.supabase.co/functions/v1/create-quote-pdf';
var QUOTES_KEY='tqb_quotes_v6';
var INVOICES_KEY='tqb_invoices_v1';
function readQuotes(){try{var q=JSON.parse(localStorage.getItem(QUOTES_KEY)||'[]');return Array.isArray(q)?q:[]}catch(e){return[]}}
function saveQuotes(q){try{localStorage.setItem(QUOTES_KEY,JSON.stringify(q))}catch(e){}}
function readInvoices(){try{var q=JSON.parse(localStorage.getItem(INVOICES_KEY)||'[]');return Array.isArray(q)?q:[]}catch(e){return[]}}
function saveInvoices(q){try{localStorage.setItem(INVOICES_KEY,JSON.stringify(q))}catch(e){}}
function settings(){try{return JSON.parse(localStorage.getItem('tqb_settings_v6')||'{}')}catch(e){return{}}}
function statusText(q){var s=String(q.status||q.quoteStatus||'').toLowerCase();if(s.indexOf('accept')>=0)return'Accepted';if(s.indexOf('declin')>=0||s.indexOf('reject')>=0)return'Declined';return'Pending'}
function datePlus(dateStr,days){var p=String(dateStr||'').split('/'),d;if(p.length===3)d=new Date(Number(p[2]),Number(p[1])-1,Number(p[0]));else d=new Date(dateStr);if(isNaN(d.getTime()))d=new Date();d.setDate(d.getDate()+Number(days||0));return d.toLocaleDateString('en-AU')}
function nextInvoiceNumber(){var list=readInvoices(),max=0;list.forEach(function(x){var m=String(x.number||'').match(/^INV-(\d{3})$/);if(m)max=Math.max(max,Number(m[1])||0)});return'INV-'+String(max+1).padStart(3,'0')}
function bankFromSettings(){var s=settings();return{bankName:s.bankName||'',bankAccountName:s.bankAccountName||'',bankBsb:s.bankBsb||'',bankAccountNumber:s.bankAccountNumber||'',bankPayId:s.bankPayId||'',bankReference:s.bankReference||'Use invoice number as reference'}}
function findInvoice(q){var list=readInvoices();for(var i=0;i<list.length;i++)if(String(list[i].quoteId)===String(q.id)||String(list[i].quoteNumber)===String(q.number))return list[i];return null}
function convertAcceptedQuote(q){if(!q||statusText(q)!=='Accepted'||!q.id||!q.number)return null;var existing=findInvoice(q);if(existing)return existing;var s=settings(),bank=bankFromSettings(),days=Math.max(0,Number(q.paymentTermsDays)||7),issued=new Date().toLocaleDateString('en-AU');var inv={id:String(Date.now())+'-'+Math.random().toString(16).slice(2),number:nextInvoiceNumber(),quoteId:q.id,quoteNumber:q.number,status:'Unpaid',invoiceDate:issued,dueDate:datePlus(issued,days),paymentTermsDays:days,businessName:s.businessName||'Your Business Name',abn:s.abn||'',businessPhone:s.businessPhone||'',businessEmail:s.businessEmail||'',businessAddress:s.businessAddress||'',bankName:bank.bankName,bankAccountName:bank.bankAccountName,bankBsb:bank.bankBsb,bankAccountNumber:bank.bankAccountNumber,bankPayId:bank.bankPayId,bankReference:bank.bankReference,customerName:q.customerName||'',customerPhone:q.customerPhone||'',customerEmail:q.customerEmail||'',customerAddress:q.customerAddress||'',jobDescription:q.jobDescription||'',items:Array.isArray(q.items)?q.items.map(function(x){return Object.assign({},x)}):[],labourHours:Number(q.labourHours)||0,hourlyRate:Number(q.hourlyRate)||0,labour:Number(q.labour)||0,subtotal:Number(q.subtotal)||0,discount:Number(q.discount)||0,total:Number(q.total)||0,gst:Number(q.gst)||0,createdAt:Date.now()};var list=readInvoices();list.unshift(inv);saveInvoices(list);return inv}
function updatePreview(q){var p=document.getElementById('quotePreview');if(!p||!window.currentQuote||String(window.currentQuote.id)!==String(q.id))return;var el=p.querySelector('.tqb-live-status');if(!el){el=document.createElement('div');el.className='tqb-live-status';p.appendChild(el)}var st=statusText(q);el.textContent='Customer response: '+st;el.style.cssText='margin-top:18px;padding:10px 14px;border-radius:10px;font-weight:700;text-align:center;background:'+(st==='Accepted'?'#dff5e8':st==='Declined'?'#fde1e2':'#e6f0ff')+';color:'+(st==='Accepted'?'#148043':st==='Declined'?'#d92d20':'#1769c2')+';'}
function refreshDashboard(){if(typeof window.refreshTQBDashboard==='function')window.refreshTQBDashboard()}
function checkQuote(q,quoteList,index){if(!q.responseToken||!q.number)return Promise.resolve(false);var url=ENDPOINT+'?quoteNumber='+encodeURIComponent(q.number)+'&responseToken='+encodeURIComponent(q.responseToken);return fetch(url,{cache:'no-store'}).then(function(r){if(!r.ok)return null;return r.json()}).then(function(data){var decision=String(data&&data.decision||'').trim();if(decision!=='Accepted'&&decision!=='Declined')return false;var old=statusText(q);q.status=decision;q.quoteStatus=decision;q.respondedAt=data.responded_at||q.respondedAt||new Date().toISOString();if(decision==='Accepted'){var inv=convertAcceptedQuote(q);if(inv){q.invoiceId=inv.id;q.invoiceNumber=inv.number;q.convertedToInvoiceAt=q.convertedToInvoiceAt||Date.now();if(window.currentQuote&&String(window.currentQuote.id)===String(q.id))window.currentQuote=q;quoteList.splice(index,1);saveQuotes(quoteList);refreshDashboard();if(window.currentQuote&&String(window.currentQuote.id)===String(q.id)){updatePreview(q)}return true}}quoteList[index]=q;saveQuotes(quoteList);if(window.currentQuote&&String(window.currentQuote.id)===String(q.id))window.currentQuote=q;updatePreview(q);refreshDashboard();return old!==decision}).catch(function(){return false})}
function sync(){var quoteList=readQuotes(),jobs=[];for(var i=0;i<quoteList.length;i++)if(quoteList[i].responseToken)jobs.push(checkQuote(quoteList[i],quoteList,i));return Promise.all(jobs)}
var CUSTOMERS_KEY='tqb_customers_v1';
var DELETED_CUSTOMERS_KEY='tqb_deleted_customers_v2';
function readCustomers(){try{var x=JSON.parse(localStorage.getItem(CUSTOMERS_KEY)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function saveCustomers(x){try{localStorage.setItem(CUSTOMERS_KEY,JSON.stringify(x))}catch(e){}}
function readDeletedCustomers(){try{var x=JSON.parse(localStorage.getItem(DELETED_CUSTOMERS_KEY)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function saveDeletedCustomers(x){try{localStorage.setItem(DELETED_CUSTOMERS_KEY,JSON.stringify(x))}catch(e){}}
function norm(v){return String(v||'').trim().toLowerCase().replace(/\s+/g,' ')}
function phoneKey(v){var d=String(v||'').replace(/\D/g,'');if(d.indexOf('61')===0&&d.length===11)d='0'+d.slice(2);return d}
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'})[c]})}
function customerKey(c){var email=norm(c.email),phone=phoneKey(c.phone),name=norm(c.name);if(phone&&email)return email+'|'+phone;if(phone)return phone;if(email)return email+'|'+name;return name}
function isDeletedCustomer(c){var k=customerKey(c),n=norm(c.name),p=phoneKey(c.phone),e=norm(c.email);return readDeletedCustomers().some(function(x){return (x.id&&c.id&&String(x.id)===String(c.id))||(x.key&&x.key===k)||(!x.key&&norm(x.name)===n&&phoneKey(x.phone)===p&&norm(x.email)===e)})}
function clearDeletedCustomer(c){var k=customerKey(c),list=readDeletedCustomers(),next=list.filter(function(x){return !((x.id&&c.id&&String(x.id)===String(c.id))||(x.key&&x.key===k))});if(next.length!==list.length)saveDeletedCustomers(next)}
function rebuildCustomers(){var list=readCustomers().filter(function(c){return !isDeletedCustomer(c)}),quotes=readQuotes(),invoices=readInvoices(),out=list.slice();function addRecord(r){var name=String(r.customerName||'').trim();if(!name)return;var probe={name:name,email:r.customerEmail,phone:r.customerPhone};if(isDeletedCustomer(probe))return;var key=customerKey(probe),found=null;for(var i=0;i<out.length;i++){if(customerKey(out[i])===key){found=out[i];break}}if(!found){found={id:'cust-'+Date.now()+'-'+Math.random().toString(16).slice(2),name:name,email:String(r.customerEmail||'').trim(),phone:String(r.customerPhone||'').trim(),address:String(r.customerAddress||'').trim(),notes:'',createdAt:Date.now()};out.push(found)}else{if(!found.email&&r.customerEmail)found.email=String(r.customerEmail).trim();if(!found.phone&&r.customerPhone)found.phone=String(r.customerPhone).trim();if(!found.address&&r.customerAddress)found.address=String(r.customerAddress).trim()}}quotes.forEach(addRecord);invoices.forEach(addRecord);saveCustomers(out);return out}
function ensureCustomerStyles(){if(document.getElementById('tqb-customer-style'))return;var s=document.createElement('style');s.id='tqb-customer-style';s.textContent='.customers-wrap{max-width:1100px;margin:0 auto}.customers-toolbar{display:flex;gap:10px;margin-bottom:14px}.customers-toolbar input{margin:0;flex:1}.customer-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.customer-card{background:#fff;border:1px solid #e6eaf0;border-radius:14px;padding:18px;cursor:pointer;box-shadow:0 3px 14px #1720330b}.customer-card:hover{background:#fafcff}.customer-card .row{display:flex;justify-content:space-between;gap:12px}.customer-card small{display:block;color:#667085;margin-top:5px}.customer-metrics{display:flex;gap:16px;flex-wrap:wrap;margin-top:14px;font-size:12px;color:#475467}.customer-metrics b{color:#111}.customer-detail{margin-top:14px;background:#fff;border-radius:14px;padding:20px;border:1px solid #e6eaf0}.customer-detail-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.customer-detail h3{margin:0 0 5px;font-size:22px}.customer-record{padding:12px 0;border-top:1px solid #eee;display:flex;justify-content:space-between;gap:12px}.customer-record small{display:block;color:#667085;margin-top:3px}.customer-stat-row{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:16px 0}.customer-stat{background:#f8fafc;border:1px solid #e5e7eb;border-radius:11px;padding:13px}.customer-stat span{display:block;color:#667085;font-size:11px}.customer-stat b{display:block;margin-top:5px;font-size:17px}.customer-form{margin-top:14px;background:#fff;border:1px solid #e6eaf0;border-radius:14px;padding:18px}.customer-form-actions{display:flex;gap:10px}.customer-form-actions button{flex:1}.customer-actions{display:flex;gap:10px;margin:0 0 18px}.customer-actions button{flex:1}.customer-picker{background:#fff;border:1px solid #e6eaf0;border-radius:14px;padding:14px;margin-bottom:14px}.customer-picker label{margin:0}.customer-picker select{margin-top:7px}.customer-picker .hint{margin:8px 0 0;color:#667085;font-size:12px}@media(max-width:650px){.customer-grid{grid-template-columns:1fr}.customer-stat-row{grid-template-columns:1fr 1fr}.customers-toolbar{flex-direction:column}.customer-actions{flex-direction:column}}';document.head.appendChild(s)}
function ensureCustomerScreen(){if(document.getElementById('customers'))return;var main=document.querySelector('main');if(!main)return;var sec=document.createElement('section');sec.id='customers';sec.className='screen';sec.innerHTML='<div class="section-head"><button class="back-btn" data-back>← Back</button><h2>Customers</h2><button class="primary" id="newCustomerBtn">＋ Add Customer</button></div><div class="customers-wrap"><div class="customers-toolbar"><input id="customerSearch" placeholder="Search customers by name, phone or email"><button class="secondary" id="refreshCustomersBtn">Refresh</button></div><div id="customerList"></div><div id="customerDetail"></div></div>';main.appendChild(sec)}
function customerStats(c){var qs=readQuotes().filter(function(q){return customerKey({name:q.customerName,email:q.customerEmail,phone:q.customerPhone})===customerKey(c)}),ins=readInvoices().filter(function(i){return customerKey({name:i.customerName,email:i.customerEmail,phone:i.customerPhone})===customerKey(c)});var invoiced=ins.reduce(function(a,i){return a+(Number(i.total)||0)},0),paid=ins.filter(function(i){return String(i.status||'').toLowerCase()==='paid'}).reduce(function(a,i){return a+(Number(i.total)||0)},0);return{quotes:qs,invoices:ins,invoiced:invoiced,paid:paid,due:Math.max(0,invoiced-paid)}}
function money2(v){return new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(Number(v)||0)}
function openCustomer(c){if(!c)return;var st=customerStats(c),all=st.quotes.map(function(q){return{type:'Quote',number:q.number,date:q.date,total:q.total,status:q.status||q.quoteStatus||'Pending'}}).concat(st.invoices.map(function(i){return{type:'Invoice',number:i.number,date:i.invoiceDate,total:i.total,status:i.status||'Unpaid'}})).sort(function(a,b){return String(b.date||'').localeCompare(String(a.date||''))});document.getElementById('customerDetail').innerHTML='<div class="customer-detail"><div class="customer-detail-head"><div><h3>'+esc(c.name)+'</h3><div>'+esc(c.email||'No email')+'</div><div>'+esc(c.phone||'No phone')+'</div><div>'+esc(c.address||'No address')+'</div></div><button class="secondary" id="editCustomerBtn">✏️ Edit</button></div><div class="customer-actions"><button class="primary" id="newQuoteForCustomerBtn">＋ New Quote for '+esc(c.name)+'</button>'+(c.email?'<button class="secondary" id="emailCustomerBtn">✉️ Email Customer</button>':'')+'</div>'+(c.notes?'<div class="storage-note" style="margin-bottom:16px"><b>Notes:</b> '+esc(c.notes)+'</div>':'')+'<div class="customer-stat-row"><div class="customer-stat"><span>Total invoiced</span><b>'+money2(st.invoiced)+'</b></div><div class="customer-stat"><span>Total paid</span><b>'+money2(st.paid)+'</b></div><div class="customer-stat"><span>Outstanding</span><b>'+money2(st.due)+'</b></div></div><h4>Recent activity</h4>'+ (all.length?all.slice(0,12).map(function(r){return'<div class="customer-record"><div><b>'+esc(r.type)+' '+esc(r.number)+'</b><small>'+esc(r.date||'')+' · '+esc(r.status)+'</small></div><b>'+money2(r.total)+'</b></div>'}).join(''):'<p class="storage-note">No quotes or invoices yet.</p>')+'</div>';document.getElementById('editCustomerBtn').onclick=function(){editCustomer(c)};document.getElementById('newQuoteForCustomerBtn').onclick=function(){var nav=document.querySelector('[data-screen="quoteForm"]');if(nav)nav.click();setTimeout(function(){var sel=document.getElementById('quoteCustomerSelect');if(sel){sel.value=String(c.id);sel.dispatchEvent(new Event('change',{bubbles:true}))}else{var n=document.getElementById('customerName'),p=document.getElementById('customerPhone'),e=document.getElementById('customerEmail'),a=document.getElementById('customerAddress');if(n)n.value=c.name;if(p)p.value=c.phone||'';if(e)e.value=c.email||'';if(a)a.value=c.address||''}},100)};var emailBtn=document.getElementById('emailCustomerBtn');if(emailBtn)emailBtn.onclick=function(){window.location.href='mailto:'+encodeURIComponent(c.email)}}
function renderCustomers(){ensureCustomerScreen();ensureCustomerStyles();var list=rebuildCustomers(),search=norm(document.getElementById('customerSearch')&&document.getElementById('customerSearch').value),filtered=list.filter(function(c){return !search||[c.name,c.email,c.phone,c.address].some(function(v){return norm(v).indexOf(search)>=0})}),el=document.getElementById('customerList');if(!el)return;if(!filtered.length){el.innerHTML='<div class="empty">No customers found.<br><br>Customers are created automatically from quotes and invoices.</div>';return}el.innerHTML='<div class="customer-grid">'+filtered.map(function(c){var st=customerStats(c);return'<div class="customer-card" data-customer-id="'+esc(c.id)+'"><div class="row"><b>'+esc(c.name)+'</b><b>'+money2(st.invoiced)+'</b></div><small>'+esc(c.phone||c.email||'No contact details')+'</small><div class="customer-metrics"><span>Quotes <b>'+st.quotes.length+'</b></span><span>Invoices <b>'+st.invoices.length+'</b></span><span>Paid <b>'+money2(st.paid)+'</b></span><span>Due <b>'+money2(st.due)+'</b></span></div></div>'}).join('')+'</div>';el.querySelectorAll('.customer-card').forEach(function(card){card.onclick=function(){openCustomer(list.find(function(c){return String(c.id)===String(card.getAttribute('data-customer-id'))}))}})}
function editCustomer(c){document.getElementById('customerDetail').innerHTML='<div class="customer-form"><h3 style="margin-top:0">Edit customer</h3><label>Customer name<input id="editCustName" value="'+esc(c.name)+'"></label><label>Phone<input id="editCustPhone" value="'+esc(c.phone)+'"></label><label>Email<input id="editCustEmail" type="email" value="'+esc(c.email)+'"></label><label>Address<textarea id="editCustAddress" rows="3">'+esc(c.address)+'</textarea></label><label>Notes<textarea id="editCustNotes" rows="3">'+esc(c.notes)+'</textarea></label><div class="customer-form-actions"><button class="secondary" id="cancelCustEdit">Cancel</button><button class="primary" id="saveCustEdit">Save Customer</button></div></div>';document.getElementById('cancelCustEdit').onclick=function(){openCustomer(c)};document.getElementById('saveCustEdit').onclick=function(){var list=readCustomers(),f=list.find(function(x){return String(x.id)===String(c.id)});if(!f)return;f.name=document.getElementById('editCustName').value.trim()||c.name;f.phone=document.getElementById('editCustPhone').value.trim();f.email=document.getElementById('editCustEmail').value.trim();f.address=document.getElementById('editCustAddress').value.trim();f.notes=document.getElementById('editCustNotes').value.trim();clearDeletedCustomer(f);saveCustomers(list);renderCustomers();openCustomer(list.find(function(x){return String(x.id)===String(f.id)}))}}
function addCustomer(){var c={id:'cust-'+Date.now()+'-'+Math.random().toString(16).slice(2),name:'',email:'',phone:'',address:'',notes:'',createdAt:Date.now()};var list=readCustomers();list.unshift(c);saveCustomers(list);renderCustomers();editCustomer(c)}
function showCustomers(){ensureCustomerScreen();ensureCustomerStyles();document.querySelectorAll('.screen').forEach(function(x){x.classList.toggle('active',x.id==='customers')});document.querySelectorAll('.nav').forEach(function(x){x.classList.toggle('active',x.getAttribute('data-screen')==='customers')});renderCustomers();window.scrollTo(0,0)}
function customerPicker(){var form=document.getElementById('quoteFormEl'),name=document.getElementById('customerName');if(!form||!name||document.getElementById('quoteCustomerPicker'))return;ensureCustomerStyles();var wrap=document.createElement('div');wrap.id='quoteCustomerPicker';wrap.className='customer-picker';wrap.innerHTML='<label>Existing customer<select id="quoteCustomerSelect"><option value="">＋ New customer / enter details below</option></select></label><p class="hint">Choose a saved customer to fill their contact details automatically.</p>';form.insertBefore(wrap,name.closest('label'));var sel=document.getElementById('quoteCustomerSelect');var list=rebuildCustomers().filter(function(c){return c.name});list.sort(function(a,b){return norm(a.name).localeCompare(norm(b.name))});list.forEach(function(c){var o=document.createElement('option');o.value=c.id;o.textContent=c.name+(c.phone?' · '+c.phone:'');sel.appendChild(o)});sel.onchange=function(){var c=readCustomers().find(function(x){return String(x.id)===String(sel.value)});if(!c)return;name.value=c.name;document.getElementById('customerPhone').value=c.phone||'';document.getElementById('customerEmail').value=c.email||'';document.getElementById('customerAddress').value=c.address||'';[name,document.getElementById('customerPhone'),document.getElementById('customerEmail'),document.getElementById('customerAddress')].forEach(function(x){if(x)x.dispatchEvent(new Event('input',{bubbles:true}))})}}
function syncCustomerFromQuote(){var name=document.getElementById('customerName');if(!name||!norm(name.value))return;var data={name:name.value.trim(),phone:(document.getElementById('customerPhone')||{}).value||'',email:(document.getElementById('customerEmail')||{}).value||'',address:(document.getElementById('customerAddress')||{}).value||''},list=readCustomers(),key=customerKey(data),found=null;clearDeletedCustomer(data);for(var i=0;i<list.length;i++)if(customerKey(list[i])===key){found=list[i];break}if(!found){found={id:'cust-'+Date.now()+'-'+Math.random().toString(16).slice(2),name:data.name,email:data.email.trim(),phone:data.phone.trim(),address:data.address.trim(),notes:'',createdAt:Date.now()};list.push(found)}else{found.name=data.name;found.email=data.email.trim();found.phone=data.phone.trim();found.address=data.address.trim()}saveCustomers(list)}
function wireCustomers(){ensureCustomerScreen();ensureCustomerStyles();var nav=document.querySelector('[data-screen="customers"]');if(nav&&!nav.dataset.customerWired){nav.dataset.customerWired='1';nav.addEventListener('click',function(e){e.preventDefault();showCustomers()})}var search=document.getElementById('customerSearch');if(search&&!search.dataset.customerWired){search.dataset.customerWired='1';search.addEventListener('input',renderCustomers)}var refresh=document.getElementById('refreshCustomersBtn');if(refresh&&!refresh.dataset.customerWired){refresh.dataset.customerWired='1';refresh.onclick=renderCustomers}var add=document.getElementById('newCustomerBtn');if(add&&!add.dataset.customerWired){add.dataset.customerWired='1';add.onclick=addCustomer}customerPicker();var form=document.getElementById('quoteFormEl');if(form&&!form.dataset.customerCapture){form.dataset.customerCapture='1';form.addEventListener('submit',syncCustomerFromQuote,true)}}
function start(){wireCustomers();sync();setInterval(function(){wireCustomers();if(document.getElementById('customers')&&document.getElementById('customers').classList.contains('active'))renderCustomers()},15000);document.addEventListener('click',function(e){if(e.target.closest&&e.target.closest('.nav'))setTimeout(function(){wireCustomers();sync()},250)});window.addEventListener('focus',function(){wireCustomers();sync()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();