(function(){
'use strict';
var ITEMS_KEY='tqb_items_services_v1';
function readItems(){try{var x=JSON.parse(localStorage.getItem(ITEMS_KEY)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function money(v){return new Intl.NumberFormat('en-AU',{style:'currency',currency:'AUD'}).format(Number(v)||0)}
function esc(v){return String(v==null?'':v).replace(/[&<>\"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#039;'})[c]})}
function menu(){var m=document.getElementById('tqb-custom-item-menu');if(!m){m=document.createElement('div');m.id='tqb-custom-item-menu';m.style.cssText='position:fixed;z-index:5000;background:#fff;border:1px solid #dfe4e9;border-radius:12px;box-shadow:0 12px 30px #0003;max-height:280px;overflow:auto;display:none;padding:6px;box-sizing:border-box';document.body.appendChild(m)}return m}
function close(){var m=document.getElementById('tqb-custom-item-menu');if(m)m.style.display='none'}
function show(input){var m=menu(),list=readItems(),r=input.getBoundingClientRect(),w=Math.max(280,r.width);m.innerHTML='';m.style.width=Math.min(460,w)+'px';m.style.left=Math.max(8,Math.min(r.left,window.innerWidth-Math.min(460,w)-8))+'px';m.style.top=Math.min(r.bottom+5,window.innerHeight-290)+'px';list.forEach(function(x){var b=document.createElement('button');b.type='button';b.style.cssText='display:block;width:100%;border:0;background:#fff;text-align:left;padding:10px 12px;border-radius:8px;cursor:pointer';b.innerHTML='<b>'+esc(x.name||'Unnamed item')+'</b><small style="display:block;color:#737b86;margin-top:2px">'+esc(x.type||'Service')+' · '+esc(x.unit||'each')+' · '+money(x.price)+'</small>';b.onclick=function(){input.value=x.name||'';var row=input.closest('.item');if(row){var q=row.querySelector('.item-qty'),u=row.querySelector('.item-unit');if(q&&!q.value)q.value=1;if(u)u.value=Number(x.price)||0;if(u)u.dispatchEvent(new Event('input',{bubbles:true}))}input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));close()};m.appendChild(b)});var custom=document.createElement('div');custom.textContent=list.length?'＋ Type a custom item':'No saved items yet. Type a custom item';custom.style.cssText='padding:11px 12px;border-top:1px solid #edf0f3;color:#b66e00;font-weight:800;cursor:pointer';custom.onclick=function(){close();input.focus()};m.appendChild(custom);m.style.display='block'}
function normalize(){var rows=document.querySelectorAll('#lineItems .item');rows.forEach(function(row){var sel=row.querySelector('.quote-catalogue-select');var input=row.querySelector('.item-desc');if(sel&&input){input.style.display='block';input.style.width='100%';input.style.margin='0';input.placeholder='Material or other cost';sel.remove()}if(input&&!input.dataset.customDropdown){input.dataset.customDropdown='1';input.setAttribute('autocomplete','off');input.addEventListener('focus',function(){show(this)});input.addEventListener('click',function(){show(this)});input.addEventListener('blur',function(){setTimeout(close,180)})}})}
function reorder(){var n=document.querySelector('.bottom-nav');if(!n)return;['dashboard','quoteForm','saved','invoices','customers','itemsServices','payments','reports','settings'].forEach(function(id){var b=n.querySelector('[data-screen="'+id+'"]');if(b)n.appendChild(b)})}
function run(){normalize();reorder()}
function start(){run();setTimeout(run,100);setTimeout(run,500);setTimeout(run,1200);setInterval(run,1000);document.addEventListener('click',function(e){if(!e.target.closest('#tqb-custom-item-menu')&&!e.target.closest('.item-desc'))close()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
